// services/app/web/pages/Home.tsx
import { useCallback, useLayoutEffect, useState } from 'react';
import { clearInitialStory, hasInitialHome } from '@/web/initial-story';
import { usePageData } from '@/web/use-page-data';
import type { HomeCore, HomeInsights } from '@/web/home-resource';
import ClaimBanner from '@/components/ClaimBanner';
import { DatabasePlus } from 'lucide-react';
import GetStarted from '@/components/GetStarted';
import Landing from '@/components/Landing';
import { ShellFrame } from '@/web/Shell';
import LoginForm from '@/components/LoginForm';
import SharedWithYou from '@/components/SharedWithYou';
import Shelf from '@/components/Shelf';
import WorkspaceLayout, { HOME_WORKSPACE_COLUMN, WorkspaceSkeleton } from '@/components/WorkspaceLayout';
import { PAGE_COLUMN } from '@/components/ui';
import { useSession } from '@/web/session';

/**
 * THE EMPTY LIBRARY IS THE ONLY PAGE THAT SAYS WHAT TO DO FIRST.
 *
 * Signed in with nothing published, the page leads with the act, keeps the
 * same panel every other surface shows, and then keeps dataset creation and
 * recovery links available.
 */
function FirstArtifact() {
  // The greeting rides the session the chrome already read — a name is worth
  // no second request, and a page that has not learned it yet simply greets
  // nobody rather than flashing a placeholder in.
  const { session } = useSession();
  const name = session?.user?.email?.split('@')[0] ?? '';
  const greeting = `${name ? `hi ${name}, l` : 'l'}et\u2019s create your first artifact!`;
  return (
    <>
      <div className="mb-8 sm:mb-10">
        {/* SERIF STATES, MONO LABELS, SANS EXPLAINS — the landing's rule, and
          * this is the page making a claim in its own words. The accessible
          * name is the line itself: an aria-label that says something else
          * would REPLACE what a screen reader hears. */}
        <h1
          aria-label={greeting}
          className="font-serif text-[clamp(1.6rem,3.4vw,2.25rem)] leading-[1.15] font-medium tracking-[-0.01em] text-fg"
        >
          {greeting}
        </h1>
        <p className="mt-1.5 font-sans text-sm text-muted">
          Hand an agent the instruction below along with what artifact you want, and follow along.
        </p>
      </div>
    </>
  );
}

export function HomePage() {
  const [publicInitial, setPublicInitial] = useState(hasInitialHome);
  const { session, reload } = useSession();
  const core = usePageData<HomeCore>('/api/page/home?part=core');
  const insights = usePageData<HomeInsights>('/api/page/home?part=insights', { enabled: !!core.data?.signedIn });
  const load = useCallback(() => { void core.refresh(true); void insights.refresh(true); }, [core.refresh, insights.refresh]);
  const wrongAccount = (core.data?.signedIn && core.data.accountId !== session?.user?.id)
    || (insights.data && (!insights.data.signedIn || insights.data.accountId !== session?.user?.id));
  const state = { core: wrongAccount ? null : core.data, insights: wrongAccount ? null : insights.data, error: wrongAccount ? new Error('Account changed') : core.error, insightsError: !!insights.error };
  const home = state.core;
  useLayoutEffect(() => { clearInitialStory(); }, []);
  useLayoutEffect(() => {
    if (home || (session && session.kind !== 'none')) setPublicInitial(false);
  }, [home, session]);
  // Preserve the server's real landing across startup fetches. Any resolved
  // account/anonymous identity supersedes that one-use eligibility verdict.
  if (!home && publicInitial && (!session || session.kind === 'none')) return <Landing />;
  if (!home) return <ShellFrame><main className={`${HOME_WORKSPACE_COLUMN} mt-8 pb-24`}>
    {state.error ? <div role="alert"><p>Could not load your workspace.</p><button aria-label="Retry workspace" onClick={session ? load : reload}>Try again</button></div> : <WorkspaceSkeleton />}
  </main></ShellFrame>;
  if (!home.signedIn) {
    if (home.drafts?.length) {
      return (
        <ShellFrame><main className={`${PAGE_COLUMN} mt-8 pb-24`}>
          <div className="mb-6 flex flex-wrap items-baseline justify-start gap-x-4 gap-y-1">
            <h1 className="font-mono text-sm tracking-[0.14em] text-fg uppercase">Drafts held by this browser · </h1>
            <a className="font-sans text-sm text-accent underline underline-offset-2" href="/login">Log in to keep them</a>
          </div>
          <Shelf actions="full" rows={home.drafts} />
          <div className="mt-8"><GetStarted /></div>
          {/* Keeping the drafts is the second act, so it follows the panel
            * rather than competing with it. */}
          <div className="reveal mt-3 rounded-[6px] border border-edge bg-surface px-4 pt-4 pb-4">
            <h2 className="mb-2.5 font-mono text-[11px] tracking-[0.14em] text-muted uppercase">Log in</h2>
            <LoginForm />
          </div>
        </main></ShellFrame>
      );
    }
    // A stranger has nothing to log into yet: the landing proves the product
    // and hands over the instruction; the page menu keeps the login door.
    return <Landing />;
  }
  const empty = home.artifacts.length === 0 && home.shared.length === 0 && !state.insights?.stats?.assets;
  return (
    <ShellFrame><main className={`${empty ? PAGE_COLUMN : HOME_WORKSPACE_COLUMN} mt-8 pb-24`}>
      {empty ? (
        <>
          <FirstArtifact />
          <div className="mb-6"><GetStarted /></div>
        </>
      ) : null}
      {/* Kept outside the empty/full branch so a successful claim can report
        * its result while the page refreshes into the dashboard. */}
      <ClaimBanner />
      {state.error && <div role="alert">Could not refresh your workspace. <button aria-label="Retry workspace" onClick={load}>Try again</button></div>}
      {empty && <div className="mb-4 flex justify-end"><a href="/datasets/new" aria-label="Create dataset" className="inline-flex items-center gap-1.5 rounded border border-edge-bright px-3 py-1.5 font-mono text-xs text-accent hover:border-accent"><DatabasePlus aria-hidden="true" size={13} strokeWidth={1.75} />Create dataset</a></div>}
      {!empty && (
        <WorkspaceLayout workspace={home} insights={state.insights} insightsError={state.insightsError} onCreated={load}>
          {home.artifacts.length > 0 && <Shelf actions="full" assets={false} scopeParentId={null} rows={home.artifacts.map((row) => ({ ...row, views: state.insights?.views?.[row.id], sparkline: state.insights?.sparklines[row.id] ?? null })) as never} />}
          <SharedWithYou items={home.shared} />
        </WorkspaceLayout>
      )}
      {/* A bare account has no right rail, but it may already follow people
        * and it may have just emptied itself into Trash. Keep both recovery
        * surfaces reachable until the workspace—and its rail—exists. */}
      {empty && (
        <>
          <p className="mt-8">
            <a
              href="/trash"
              aria-label="Trash"
              className="font-mono text-[10px] text-faint no-underline transition-colors hover:text-accent"
            >
              trash
            </a>
          </p>
        </>
      )}
    </main></ShellFrame>
  );
}

// services/app/solid/pages/Home.tsx
/* @jsxImportSource solid-js */
import { createEffect, createMemo, createSignal, onMount, Show, type JSX } from 'solid-js';
import { Navigate } from '@solidjs/router';
import DatabasePlus from 'lucide-solid/icons/database-plus';
import type { HomeCore, HomeInsights } from '@/web/home-resource';
import { clearInitialStory } from '@/web/initial-story';
import { PAGE_COLUMN } from '../components/ui';
import GetStarted from '../components/GetStarted';
import ClaimBanner from '../components/ClaimBanner';
import SharedWithYou from '../components/SharedWithYou';
import Shelf from '../components/Shelf';
import WorkspaceLayout, { HOME_WORKSPACE_COLUMN, WorkspaceSkeleton } from '../components/WorkspaceLayout';
import { usePageData } from '../lib/use-page-data';
import { useSession } from '../lib/session';

export function HomePage(): JSX.Element {
  const { session, sessionError, reload } = useSession();
  // "My artifacts"'s own search box (Shelf) also narrows "Shared with you" below it, the way one
  // search box on a page reads as one search to whoever is typing into it.
  const [sharedQuery, setSharedQuery] = createSignal('');
  const core = usePageData<HomeCore>('/api/page/home?part=core');
  const insights = usePageData<HomeInsights>('/api/page/home?part=insights', { enabled: () => Boolean(core.data()?.signedIn) });
  createEffect(() => { if (sessionError()) { core.invalidate(); insights.invalidate(); } });
  const load = () => { void core.refresh(true); void insights.refresh(true); };
  const wrongAccount = createMemo(() => {
    const current = session(); const home = core.data(); const detail = insights.data();
    return Boolean(home?.signedIn && home.accountId !== current?.user?.id) || Boolean(detail && (!detail.signedIn || detail.accountId !== current?.user?.id));
  });
  const home = () => wrongAccount() ? null : core.data();
  const account = () => { const value = home(); return value?.signedIn ? value : null; };
  const detail = () => wrongAccount() ? null : insights.data();
  const empty = () => Boolean(account() && account()!.artifacts.length === 0 && account()!.shared.length === 0 && !detail()?.stats?.assets);
  const failed = () => wrongAccount() || Boolean(core.error());
  const greeting = () => { const name = session()?.user?.email?.split('@')[0] ?? ''; return `${name ? `hi ${name}, l` : 'l'}et’s create your first artifact!`; };
  onMount(clearInitialStory);
  return <Show when={!(session() && session()!.kind !== 'account') && !(home() && !home()!.signedIn)} fallback={<Navigate href="/login" />}>
    <Show when={account()} fallback={<main class={`${HOME_WORKSPACE_COLUMN} mt-8 pb-24`}><Show when={failed()} fallback={<WorkspaceSkeleton />}><div role="alert"><p>Could not load your workspace.</p><button type="button" aria-label="Retry workspace" onClick={session() ? load : reload}>Try again</button></div></Show></main>}>
      {workspace => <main class={`${empty() ? PAGE_COLUMN : HOME_WORKSPACE_COLUMN} mt-8 pb-24`}>
        <Show when={empty()}><div class="mb-8 sm:mb-10"><h1 aria-label={greeting()} class="font-serif text-[clamp(1.6rem,3.4vw,2.25rem)] leading-[1.15] font-medium tracking-[-0.01em] text-fg">{greeting()}</h1><p class="mt-1.5 font-sans text-sm text-muted">Hand an agent the instruction below along with what artifact you want, and follow along.</p></div><div class="mb-6"><GetStarted /></div></Show>
        <ClaimBanner />
        <Show when={failed()}><div role="alert">Could not refresh your workspace. <button type="button" aria-label="Retry workspace" onClick={load}>Try again</button></div></Show>
        <Show when={empty()}><div class="mb-4 flex justify-end"><a href="/datasets/new" aria-label="Create dataset" class="inline-flex items-center gap-1.5 rounded border border-edge-bright px-3 py-1.5 font-mono text-xs text-accent"><DatabasePlus size={13} />Create dataset</a></div><p class="mt-8"><a href="/trash" aria-label="Trash" class="font-mono text-[10px] text-faint">trash</a></p></Show>
        <Show when={!empty()}><WorkspaceLayout workspace={workspace()} insights={detail()} insightsError={Boolean(insights.error())} onCreated={load}>
          <Show when={workspace().artifacts.length}><Shelf rows={workspace().artifacts.map(row => ({ ...row, views: detail()?.views?.[row.id], sparkline: detail()?.sparklines[row.id] ?? undefined }))} actions="full" assets={false} scopeParentId={null} onQuery={setSharedQuery} /></Show>
          <SharedWithYou items={workspace().shared} query={sharedQuery()} />
        </WorkspaceLayout></Show>
      </main>}
    </Show>
  </Show>;
}
