// services/app/components/AnnotationRail.tsx
/**
 * The comment rail's FRAME, apart from the comment layer itself.
 *
 * The layer (components/AnnotationLayer) is an on-demand chunk — only people
 * who may comment ever mount it, and a reader must not download it
 * (lib/__tests__/reader-bundle-hygiene). If someone opens comments before that
 * chunk lands, AnnotationLayerOnDemand draws THIS frame at once, busy, and the
 * layer draws the same frame when it arrives, so the rail does not move.
 */
import { createPortal } from 'react-dom';
import MobileSheet from '@/components/MobileSheet';
import { RIGHT_RAIL_W } from '@/lib/story/edit-bar';

/**
 * The conversation's two homes: the fixed right rail on
 * desktop — the page narrows the document by its width — and a bottom sheet
 * on a phone. The content between them is identical; this wrapper is the only
 * thing that knows the difference.
 */
export function RailChrome({ phone, host, topOffset, rightInset, onClose, header, children, busy = false }: {
  phone: boolean;
  /** The editor's panel, when it hosts the rail: rendered into it, not as a column of its own. */
  host?: HTMLElement;
  topOffset: number;
  rightInset: number;
  onClose: () => void;
  /** The title row + close control — pinned above the scroll in BOTH homes:
      the way out must stay reachable however long the list gets. */
  header: React.ReactNode;
  children: React.ReactNode;
  /** The layer's code is still downloading (AnnotationLayerOnDemand). */
  busy?: boolean;
}) {
  const ariaBusy = busy || undefined;
  if (phone) {
    return (
      <MobileSheet label="Annotation sidebar" onClose={onClose} size="half" header={header}>
        <div aria-busy={ariaBusy} className="flex flex-col gap-2.5">{children}</div>
      </MobileSheet>
    );
  }
  if (host) {
    return createPortal(
      <section data-capture-chrome aria-label="Annotation sidebar" aria-busy={ariaBusy} className="flex min-h-0 flex-1 flex-col gap-2.5 bg-bg p-2.5">
        <div className="shrink-0">{header}</div>
        <div className="flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto">{children}</div>
      </section>,
      host,
    );
  }
  return (
    <aside
      data-capture-chrome aria-label="Annotation sidebar" aria-busy={ariaBusy}
      className="fixed bottom-0 z-20 flex flex-col gap-2.5 border-l border-edge bg-bg p-2.5"
      style={{ top: topOffset, right: rightInset, width: RIGHT_RAIL_W }}
    >
      <div className="shrink-0">{header}</div>
      <div className="flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto">{children}</div>
    </aside>
  );
}

// services/app/solid/document/AnnotationRail.tsx
/* @jsxImportSource solid-js */
/**
 * The comment rail's FRAME, apart from the layer itself.
 *
 * The conversation has three homes: the fixed right rail on desktop (the page narrows the document
 * by its width), the editor's panel when it hosts the rail (rendered into it, not as a column of its
 * own), and a half-height bottom sheet on a phone. The content is identical; this wrapper is the
 * only thing that knows the difference. The header — title and the way out — is pinned above the
 * scroll in every home, however long the list gets.
 */
import { Show, type JSX } from 'solid-js';
import { Portal } from 'solid-js/web';
import MobileSheet from '../components/MobileSheet';
import { RIGHT_RAIL_W } from '@/lib/story/reader/edit-bar';

export function RailChrome(props: {
  phone: boolean;
  /** The editor's panel, when it hosts the rail. */
  host?: HTMLElement;
  topOffset: number;
  rightInset: number;
  onClose: () => void;
  header: JSX.Element;
  children: JSX.Element;
  /** The layer's code is still arriving. */
  busy?: boolean;
}): JSX.Element {
  const ariaBusy = () => props.busy || undefined;
  return <Show when={!props.phone} fallback={
    <MobileSheet label="Annotation sidebar" onClose={props.onClose} size="half" header={props.header}>
      <div aria-busy={ariaBusy()} class="flex flex-col gap-2.5">{props.children}</div>
    </MobileSheet>
  }>
    <Show when={props.host} fallback={
      <aside data-capture-chrome aria-label="Annotation sidebar" aria-busy={ariaBusy()}
        class="fixed bottom-0 z-20 flex flex-col gap-2.5 border-l border-edge bg-bg p-2.5"
        style={{ top: `${props.topOffset}px`, right: `${props.rightInset}px`, width: `${RIGHT_RAIL_W}px` }}>
        <div class="shrink-0">{props.header}</div>
        <div class="flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto">{props.children}</div>
      </aside>
    }>{(host) => (
      <Portal mount={host()} ref={(wrapper: HTMLElement) => { wrapper.style.display = 'contents'; }}>
        <section data-capture-chrome aria-label="Annotation sidebar" aria-busy={ariaBusy()} class="flex min-h-0 flex-1 flex-col gap-2.5 bg-bg p-2.5">
          <div class="shrink-0">{props.header}</div>
          <div class="flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto">{props.children}</div>
        </section>
      </Portal>
    )}</Show>
  </Show>;
}
