// services/app/solid/components/AvatarCircle.tsx
/* @jsxImportSource solid-js */
import { createEffect, createSignal, Show, type JSX } from 'solid-js';
import { LoaderCircle, UserRound } from 'lucide-solid';
import { DEFAULT_UPLOAD_MAX_BYTES } from '@artifactbin/contracts';
import { pageDataChanged, profileChanged } from '@/web/page-data-events';
import { Avatar } from './Avatar';

const REFUSALS: Record<string, string> = {
  unsupported_image: 'that file is not a picture this can use — PNG, JPEG, WebP, GIF or AVIF',
  image_too_large: `that picture is over ${DEFAULT_UPLOAD_MAX_BYTES / 1_000_000} MB — pick a smaller one`,
  image_unreadable: 'that picture could not be read — try exporting it again',
};
export const AVATAR_ACCEPT = 'image/png,image/jpeg,image/webp,image/gif,image/avif';

export function AvatarCircle(props: { image: string | null; initial: string; userId: string; onChange: (image: string | null) => void; onRemove?: () => void }): JSX.Element {
  let picker!: HTMLInputElement;
  const [answer, setAnswer] = createSignal<{ image: string | null; over: string | null } | null>(null);
  const [pending, setPending] = createSignal<'upload' | 'remove' | null>(null);
  const [status, setStatus] = createSignal<string | null>(null);
  createEffect(() => { if (answer() && answer()!.over !== props.image) setAnswer(null); });
  const image = () => answer()?.over === props.image ? answer()!.image : props.image;
  const pick = () => { if (!pending()) picker.click(); };
  const send = async (action: 'upload' | 'remove', init: RequestInit) => {
    setPending(action); setStatus(null);
    const response = await fetch('/api/my/profile/image', { credentials: 'same-origin', ...init }).catch(() => null);
    const body = response ? await response.json().catch(() => ({})) as { image?: string | null; error?: string } : null;
    setPending(null);
    if (!response || !body) { setStatus('could not reach the server'); return; }
    if (!response.ok) { setStatus(REFUSALS[body.error ?? ''] ?? 'could not save that picture'); return; }
    const next = action === 'upload' ? body.image ?? null : null;
    setAnswer({ image: next, over: props.image });
    pageDataChanged(); profileChanged();
    if (action === 'remove' && props.onRemove) props.onRemove(); else props.onChange(next);
  };
  return <div>
    <div class="flex flex-col items-center gap-3 text-center min-[400px]:flex-row min-[400px]:gap-5 min-[400px]:text-left">
      <div data-avatar-circle="" aria-hidden="true" tabIndex={-1} onClick={pick} class={`relative flex size-24 shrink-0 items-center justify-center overflow-hidden rounded-full text-muted ${pending() ? '' : 'cursor-pointer'} ${image() ? 'border border-edge' : 'border-2 border-dashed border-edge-bright bg-raised hover:border-muted'}`}>
        <Show when={image()} fallback={<Show when={pending() !== 'upload'}><UserRound class="size-10" strokeWidth={1.5} /></Show>}><Avatar image={image()} initial={props.initial} userId={props.userId} /></Show>
        <Show when={pending() === 'upload'}><span class={`absolute inset-0 flex items-center justify-center ${image() ? 'bg-black/55 text-white' : ''}`}><LoaderCircle class="size-8 animate-spin" /></span></Show>
      </div>
      <div class="min-w-0"><div class="flex flex-wrap justify-center gap-2 min-[400px]:justify-start">
        <button type="button" aria-busy={pending() === 'upload'} disabled={!!pending()} onClick={pick} class="inline-flex cursor-pointer items-center gap-1.5 rounded-[4px] border border-fg bg-fg px-3 py-1.5 font-mono text-xs font-semibold text-bg disabled:opacity-50">{pending() === 'upload' ? 'Uploading…' : image() ? 'Change photo' : 'Upload a photo'}</button>
        <Show when={image() && props.onRemove}><button type="button" aria-label="Remove photo" disabled={!!pending()} onClick={() => void send('remove', { method: 'DELETE' })} class="rounded-[4px] border border-edge-bright px-3 py-1.5 font-mono text-xs">Remove photo</button></Show>
      </div><Show when={status()}><p role="status" class="mt-2 text-xs text-danger">{status()}</p></Show></div>
    </div>
    <input ref={picker} type="file" accept={AVATAR_ACCEPT} class="sr-only" tabIndex={-1} aria-hidden="true" onChange={event => { const file = event.currentTarget.files?.[0]; if (file) void send('upload', { method: 'PUT', headers: { 'Content-Type': file.type || 'application/octet-stream' }, body: file }); event.currentTarget.value = ''; }} />
  </div>;
}

// services/app/components/AvatarCircle.tsx
'use client';

/**
 * THE PROFILE-PICTURE UPLOADER — the welcome page's first row and the top of
 * the account page, one component so those two screens never drift into two
 * different pictures of the same thing.
 *
 * NO PICTURE LOOKS EMPTY. A person without one sees a dashed, empty circle and
 * a labelled "Upload a photo" button, never the generated initial: a coloured
 * letter here reads as "picture already set", and people skipped it. Everywhere
 * ELSE (app bar, profile header, comments) keeps the initial through
 * `components/Avatar`, so people without pictures still look distinct.
 *
 * THE BUTTON IS THE CONTROL. It carries the name ("Upload a photo" / "Change
 * photo"), takes the focus and opens the picker on Enter/Space. The circle is a
 * larger pointer shortcut to the same picker and nothing more: hidden from the
 * accessibility tree and out of the tab order, so there are never two controls
 * answering to one name.
 *
 * With a picture, the circle draws it through `components/Avatar` — the same
 * face the app bar uses, initial beneath, so a picture whose address fails
 * never leaves a broken-image glyph.
 *
 * The bytes go straight to `PUT /api/my/profile/image` as the file's own type;
 * the server re-encodes and answers with the new address, which is swapped in
 * place. Every refusal it can make is a sentence here, because "400" on a
 * profile page is not something a person can act on — and a refusal leaves
 * whatever was showing before exactly as it was.
 */
import { useRef, useState } from 'react';
import { LoaderCircle, Upload, UserRound } from 'lucide-react';
import { DEFAULT_UPLOAD_MAX_BYTES } from '@artifactbin/contracts';
import Avatar from '@/components/Avatar';
import { pageDataChanged, profileChanged } from '@/web/page-data-events';

const MAX_MB = DEFAULT_UPLOAD_MAX_BYTES / 1_000_000;

/** The three refusals `lib/avatars` makes, as sentences. */
const REFUSALS: Record<string, string> = {
  unsupported_image: 'that file is not a picture this can use — PNG, JPEG, WebP, GIF or AVIF',
  image_too_large: `that picture is over ${MAX_MB} MB — pick a smaller one`,
  image_unreadable: 'that picture could not be read — try exporting it again',
};

/** What the file picker offers; the same set the server accepts, and no SVG. */
export const AVATAR_ACCEPT = 'image/png,image/jpeg,image/webp,image/gif,image/avif';

/** The kit's button shape (`components/ui` Button), in the two weights this needs. */
const BUTTON = 'inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-[4px] border px-3 py-1.5 font-mono text-xs font-semibold transition-colors disabled:cursor-default disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent';
const SOLID = `${BUTTON} border-fg bg-fg text-bg hover:opacity-90`;
const OUTLINED = `${BUTTON} border-edge-bright bg-transparent hover:border-accent hover:text-accent`;

export default function AvatarCircle({ image, initial, userId, onChange, onRemove }: {
  /** The picture's address, or null for the empty uploader. */
  image: string | null;
  /** The name whose initial `Avatar` keeps beneath a picture, in case its address fails. */
  initial: string;
  /** Whose picture: the colour behind that fallback initial comes from this. */
  userId: string;
  /** The new address (or null), once the server has taken it. */
  onChange: (image: string | null) => void;
  /**
   * When given, a "Remove" button is offered beside "Change photo", and this is
   * what a successful removal reports to instead of `onChange(null)` — one call
   * per action, so a page that offers removal never handles it twice. The
   * DELETE itself stays here: a page opts into the affordance, not into the door.
   */
  onRemove?: () => void;
}) {
  const picker = useRef<HTMLInputElement>(null);
  // WHICH request is in flight, not a flag: only an upload is "Uploading…".
  const [pending, setPending] = useState<'upload' | 'remove' | null>(null);
  const [status, setStatus] = useState<string | null>(null);
  const busy = pending !== null;
  const uploading = pending === 'upload';

  const send = async (action: 'upload' | 'remove', init: RequestInit): Promise<{ image?: string | null; error?: string } | null> => {
    setPending(action);
    setStatus(null);
    const res = await fetch('/api/my/profile/image', { credentials: 'same-origin', ...init }).catch(() => null);
    setPending(null);
    if (!res) { setStatus('could not reach the server'); return null; }
    const body = (await res.json().catch(() => ({}))) as { image?: string | null; error?: string };
    if (!res.ok) { setStatus(REFUSALS[body.error ?? ''] ?? 'could not save that picture'); return null; }
    // Anything that draws this person elsewhere is now stale — the app bar's
    // face included, which is the session's to re-read.
    pageDataChanged();
    profileChanged();
    return body;
  };

  const upload = async (file: File) => {
    // The FILE's type, not a guess: the server sniffs the bytes anyway, and a
    // header it can read is one less thing for it to refuse.
    const body = await send('upload', { method: 'PUT', headers: { 'Content-Type': file.type || 'application/octet-stream' }, body: file });
    if (body) onChange(body.image ?? null);
  };

  const remove = async () => {
    const body = await send('remove', { method: 'DELETE' });
    if (!body) return;
    if (onRemove) onRemove(); else onChange(null);
  };

  const pick = () => { if (!busy) picker.current?.click(); };

  return (
    <div>
      {/* Circle left, controls right; stacked and centred on a narrow phone. */}
      <div className="flex flex-col items-center gap-3 text-center min-[400px]:flex-row min-[400px]:gap-5 min-[400px]:text-left">
        {/*
          * A pointer shortcut to the same picker, NOT a second control: the
          * button beside it is the one with the name and the focus.
          */}
        <div
          data-avatar-circle=""
          aria-hidden="true"
          tabIndex={-1}
          onClick={pick}
          className={`relative flex size-24 shrink-0 items-center justify-center overflow-hidden rounded-full text-muted ${
            busy ? '' : 'cursor-pointer'
          } ${image ? 'border border-edge' : 'border-2 border-dashed border-edge-bright bg-raised hover:border-muted'}`}
        >
          {image ? <Avatar image={image} initial={initial} userId={userId} /> : !uploading && <UserRound className="size-10" strokeWidth={1.5} />}
          {uploading && (
            <span className={`absolute inset-0 flex items-center justify-center ${image ? 'bg-black/55 text-white' : ''}`}>
              <LoaderCircle className="size-8 animate-spin" />
            </span>
          )}
        </div>

        <div className="min-w-0">
          <div className="flex flex-wrap justify-center gap-2 min-[400px]:justify-start">
            <button
              type="button"
              aria-busy={uploading}
              disabled={busy}
              onClick={pick}
              className={image ? `${OUTLINED} text-fg` : SOLID}
            >
              {uploading
                ? 'Uploading…'
                : image
                  ? 'Change photo'
                  : <><Upload aria-hidden="true" className="size-3.5" />Upload a photo</>}
            </button>
            {onRemove && image && (
              <button
                type="button"
                // The visible word, plus what it removes: "Remove" alone is ambiguous
                // among the account page's other controls.
                aria-label="Remove photo"
                onClick={() => void remove()}
                disabled={busy}
                className={`${OUTLINED} text-muted`}
              >
                Remove
              </button>
            )}
          </div>
          {!image && <p className="mt-2 text-xs text-muted">PNG, JPEG, WebP, GIF or AVIF · up to {MAX_MB} MB</p>}
        </div>
      </div>
      {status && <p role="status" className="mt-3 text-center font-mono text-xs text-danger min-[400px]:text-left">{status}</p>}
      {/*
        * Hidden from everyone, including the accessibility tree: the BUTTON is
        * the control and carries the name.
        */}
      <input
        ref={picker}
        type="file"
        accept={AVATAR_ACCEPT}
        aria-hidden="true"
        tabIndex={-1}
        className="hidden"
        onChange={(e) => {
          const file = e.target.files?.[0];
          // Cleared so choosing the SAME file twice still fires a change.
          e.target.value = '';
          if (file) void upload(file);
        }}
      />
    </div>
  );
}
