// services/app/solid/components/DatasetPolicies.tsx
/* @jsxImportSource solid-js */
import { createMemo, createSignal, For, onMount, Show, type JSX } from 'solid-js';
import { parse as parseYaml } from 'yaml';
import { parseDatasetAccessPolicy } from '@artifactbin/utils/dataset-grants';
import type { DatasetAccessPolicy, DatasetOperation, DatasetTablePolicy, InsertPermission, UpdatePermission, DeletePermission } from '@artifactbin/contracts';
import { Button } from './ui';
import { PolicyConditions } from './PolicyConditions';

type Table = { schema: string; name: string; columns: Array<{ name: string }> };
type PolicyState = { canManage?: boolean; policy: DatasetAccessPolicy | null; revision: number; tables: Table[]; writtenBy: Array<{ id: string; title: string | null; mutations: string[] }> };
type Permission = InsertPermission | UpdatePermission | DeletePermission;
const operations: DatasetOperation[] = ['insert', 'update', 'delete'];
const blank = (tables: Table[]): DatasetAccessPolicy => ({ version: 1, enforcement: 'enabled', tables: tables.map(table => ({ table: { schema: table.schema, name: table.name } })) });
const pretty = (value: unknown) => JSON.stringify(value, null, 2);
const control = 'w-full rounded border border-edge bg-surface px-3 py-2 text-sm text-fg';

/** The server remains the admission and validation boundary for every policy write. */
export function DatasetPolicies(props: { artifactId: string; expanded?: boolean }): JSX.Element {
  const [open, setOpen] = createSignal(Boolean(props.expanded));
  return <div>
    <Show when={!props.expanded}><Button variant="ghost" aria-expanded={open()} onClick={() => setOpen(value => !value)}>Manage access policies</Button></Show>
    <Show when={open()}><PolicyEditor artifactId={props.artifactId} /></Show>
  </div>;
}

function PolicyEditor(props: { artifactId: string }): JSX.Element {
  const [state, setState] = createSignal<PolicyState | null>(null);
  const [draft, setDraft] = createSignal<DatasetAccessPolicy | null>(null);
  const [source, setSource] = createSignal<string | null>(null);
  const [tableIndex, setTableIndex] = createSignal(0);
  const [error, setError] = createSignal('');
  const [notice, setNotice] = createSignal('');
  const [saving, setSaving] = createSignal(false);
  const [deniedText, setDeniedText] = createSignal('');
  onMount(() => {
    let alive = true;
    void fetch(`/api/my/artifacts/${encodeURIComponent(props.artifactId)}/policy`).then(async response => {
      if (!response.ok) throw new Error('Dataset edit access is required to inspect its data rules.');
      return response.json() as Promise<PolicyState>;
    }).then(value => { if (!alive) return; setState(value); setDraft(value.policy ?? blank(value.tables)); setDeniedText((value.policy?.execution?.functions?.deny ?? []).join(', ')); })
      .catch(cause => { if (alive) setError(cause instanceof Error ? cause.message : 'Could not load policies.'); });
    return () => { alive = false; };
  });
  const change = (policy: DatasetAccessPolicy | null) => { setDraft(policy); setNotice(''); setError(''); };
  const selected = createMemo(() => draft()?.tables?.[tableIndex()]);
  const columns = createMemo(() => state()?.tables.find(table => table.schema === selected()?.table.schema && table.name === selected()?.table.name)?.columns ?? []);
  const permission = (op: DatasetOperation): Permission | undefined => selected()?.[`${op}_permissions`]?.find(entry => entry.role === 'viewer')?.permission as Permission | undefined;
  const setPermission = (op: DatasetOperation, value: Permission | null) => {
    const policy = draft(), table = selected(); if (!policy || !table) return;
    const field = `${op}_permissions` as const;
    const previous = table[field]?.find(entry => entry.role === 'viewer');
    const remaining = (table[field] ?? []).filter(entry => entry.role !== 'viewer');
    const nextTable: DatasetTablePolicy = { ...table, [field]: value ? [...remaining, { ...previous, role: 'viewer', permission: value }] : remaining };
    change({ ...policy, tables: (policy.tables ?? []).map((entry, index) => index === tableIndex() ? nextTable : entry) } as DatasetAccessPolicy);
  };
  const save = async () => {
    const loaded = state(); if (!loaded) return;
    setSaving(true); setError('');
    try {
      const policy = draft() ? parseDatasetAccessPolicy(draft()) : null;
      const response = await fetch(`/api/my/artifacts/${encodeURIComponent(props.artifactId)}/policy`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ policy, expectedPolicyRevision: loaded.revision }) });
      const answer = await response.json();
      if (!response.ok) throw new Error(answer.detail ?? answer.error ?? 'Could not save policies.');
      setState({ ...loaded, policy: answer.policy, revision: answer.revision }); setDraft(answer.policy); setNotice('Access policies saved.');
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save policies.'); }
    finally { setSaving(false); }
  };
  return <section aria-label="Access policies" class="space-y-5 py-4 text-sm text-fg">
    <header class="flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-semibold">Control how data can change</h2><p class="mt-1 text-muted">Choose allowed actions, then narrow them with column and row rules.</p></div>
      <Show when={state() && state()?.canManage !== false && source() === null}><Button variant="ghost" onClick={() => setSource(pretty(draft()))}>Edit JSON / YAML</Button></Show></header>
    <Show when={error()}><p role="alert" class="rounded border border-danger/30 bg-danger-soft p-3 text-danger">{error()}</p></Show>
    <Show when={!state() && !error()}><p role="status">Loading data actions…</p></Show>
    <Show when={state()?.canManage === false}><p>Dataset edit access is required to change these rules.</p></Show>
    <Show when={state() && state()?.canManage !== false}>
      <Show when={source() !== null} fallback={<>
        <Show when={draft()?.tables?.length}><label class="grid gap-1">Rules for table<select aria-label="Policy table" class={control} value={tableIndex()} onInput={event => setTableIndex(Number(event.currentTarget.value))}>
          <For each={draft()?.tables ?? []}>{(entry, index) => <option value={index()}>{entry.table.schema}.{entry.table.name}</option>}</For>
        </select></label></Show>
        <Show when={selected()}><For each={operations}>{op => {
          const current = () => permission(op);
          return <section class="rounded border border-edge bg-surface p-4"><label class="flex items-center gap-2 font-semibold"><input type="checkbox" aria-label={`Allow ${op}`} checked={Boolean(current())} onChange={event => setPermission(op, event.currentTarget.checked ? op === 'insert' ? { columns: '*', check: {} } : op === 'update' ? { columns: '*', filter: {}, check: {} } : { filter: {} } : null)} />{op}</label>
            <Show when={current() && 'columns' in current()!}><div class="mt-3 space-y-2"><label class="flex gap-2"><input type="checkbox" aria-label={`${op} all columns`} checked={(current() as InsertPermission | UpdatePermission).columns === '*'} onChange={event => setPermission(op, { ...current(), columns: event.currentTarget.checked ? '*' : [] } as Permission)} />Allow all columns</label>
              <Show when={(current() as InsertPermission | UpdatePermission).columns !== '*'}><For each={columns()}>{column => <label class="flex gap-2"><input type="checkbox" aria-label={`${op} column ${column.name}`} checked={((current() as InsertPermission | UpdatePermission).columns as string[] ?? []).includes(column.name)} onChange={event => { const prior = ((current() as InsertPermission | UpdatePermission).columns as string[] ?? []); setPermission(op, { ...current(), columns: event.currentTarget.checked ? [...prior, column.name] : prior.filter(name => name !== column.name) } as Permission); }} />{column.name}</label>}</For></Show>
            </div></Show>
            <Show when={current() && 'filter' in current()!}><PolicyConditions label={`${op} filter`} title="Which existing rows can change?" value={(current() as UpdatePermission | DeletePermission).filter ?? {}} columns={columns()} onChange={filter => setPermission(op, { ...current(), filter } as Permission)} /></Show>
            <Show when={current() && op !== 'delete'}><PolicyConditions label={`${op} check`} title="What must the new values satisfy?" value={(current() as InsertPermission | UpdatePermission).check ?? {}} columns={columns()} onChange={check => setPermission(op, { ...current(), check } as Permission)} /></Show>
          </section>;
        }}</For></Show>
        <label class="grid gap-1">Blocked functions<input aria-label="Denied functions" class={control} value={deniedText()} onInput={event => { const text = event.currentTarget.value; setDeniedText(text); const policy = draft(); if (policy) change({ ...policy, execution: { ...policy.execution, functions: { ...policy.execution?.functions, deny: text.split(',').map(item => item.trim()).filter(Boolean) } } }); }} /></label>
        <section><h3 class="font-semibold">Connected apps</h3><Show when={state()?.writtenBy?.length} fallback={<p>No apps use these actions yet.</p>}><For each={state()?.writtenBy}>{item => <p><a href={`/a/${item.id}`}>{item.title ?? item.id}</a> · {item.mutations.join(', ')}</p>}</For></Show></section>
      </>}>
        <label class="grid gap-1">Policy JSON or YAML<textarea aria-label="Policy JSON or YAML" spellcheck={false} class={`${control} min-h-96 font-mono`} value={source() ?? ''} onInput={event => setSource(event.currentTarget.value)} /></label>
        <div class="flex gap-2"><Button onClick={() => { try { change(parseDatasetAccessPolicy(parseYaml(source()!))); setSource(null); setTableIndex(0); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Invalid policy'); } }}>Apply policy source</Button><Button variant="ghost" onClick={() => setSource(null)}>Cancel source changes</Button></div>
      </Show>
      <details><summary>Review permission changes</summary><pre>{pretty(draft())}</pre></details>
      <footer class="flex items-center justify-between gap-3 rounded border border-edge bg-surface p-3"><p role="status">{notice() || (pretty(draft()) !== pretty(state()?.policy) ? 'You have unsaved rule changes.' : 'Rules are up to date.')}</p><Button disabled={saving() || source() !== null} onClick={() => void save()}>{saving() ? 'Saving policies…' : 'Save access policies'}</Button></footer>
    </Show>
  </section>;
}

// services/app/components/DatasetPolicies.tsx
import { useEffect, useState } from "react";
import { parse as parseYaml } from "yaml";
import { parseDatasetPolicy } from "@artifactbin/utils/dataset-policy";
import type {
  DatasetPolicy,
  DatasetTablePolicy,
  DatasetOperation,
  InsertPermission,
  UpdatePermission,
  DeletePermission,
} from "@artifactbin/contracts";
import { Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Tooltip } from "@/components/Tooltip";
import {
  PolicyConditions,
  PolicyValueInput,
} from "@/components/PolicyConditions";
import { Button } from "@/components/ui";

type Table = { schema: string; name: string; columns: Array<{ name: string }> };
type State = {
  canManage?: boolean;
  policy: DatasetPolicy | null;
  revision: number;
  tables: Table[];
  writtenBy: Array<{ id: string; title: string | null; mutations: string[] }>;
};
const inputClass =
  "w-full min-w-0 rounded-lg border border-edge bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none";
const parseList = (text: string) =>
  text
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
/** Keep the user's in-progress separators while the policy stores parsed names. */
function CommaListInput({
  label,
  value,
  onChange,
  placeholder,
}: {
  label: string;
  value: string[];
  onChange: (value: string[]) => void;
  placeholder?: string;
}) {
  const [text, setText] = useState(value.join(", "));
  const serialized = JSON.stringify(value);
  useEffect(() => {
    if (JSON.stringify(parseList(text)) !== serialized)
      setText(value.join(", "));
  }, [serialized]);
  return (
    <input
      aria-label={label}
      className={inputClass}
      placeholder={placeholder}
      value={text}
      onChange={(event) => {
        setText(event.target.value);
        onChange(parseList(event.target.value));
      }}
    />
  );
}
const operations: DatasetOperation[] = ["insert", "update", "delete"];
const pretty = (v: unknown) => JSON.stringify(v, null, 2);
const initial = (tables: Table[]): DatasetPolicy => ({
  version: 1,
  enforcement: "enabled",
  tables: tables.map((t) => ({ table: { schema: t.schema, name: t.name } })),
});
/** Both editors round-trip one schema; authorization remains on the server. */
function DatasetPolicyEditor({ artifactId }: { artifactId: string }) {
  const [state, setState] = useState<State | null>(null);
  const [draft, setDraft] = useState<DatasetPolicy | null>(null);
  const [source, setSource] = useState<string | null>(null);
  const role = "viewer";
  const [tableIndex, setTableIndex] = useState(0);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    let active = true;
    void fetch(`/api/my/artifacts/${encodeURIComponent(artifactId)}/policy`)
      .then(async (r) => {
        if (!r.ok)
          throw Error(
            "Dataset edit access is required to inspect its data rules.",
          );
        return r.json() as Promise<State>;
      })
      .then((s) => {
        if (active) {
          setState(s);
          setDraft(s.policy ?? initial(s.tables));
        }
      })
      .catch((e) => {
        if (active) setError(e.message);
      });
    return () => {
      active = false;
    };
  }, [artifactId]);
  const change = (next: DatasetPolicy | null) => {
    setDraft(next);
    setNotice("");
    setError("");
  };
  const selected = draft?.tables[tableIndex];
  const columns =
    state?.tables.find(
      (t) =>
        t.schema === selected?.table.schema && t.name === selected.table.name,
    )?.columns ?? [];
  const updateTable = (next: DatasetTablePolicy) =>
    change({
      ...draft!,
      tables: draft!.tables.map((t, i) => (i === tableIndex ? next : t)),
    });
  const permission = (op: DatasetOperation) => {
    const stored = selected?.[`${op}_permissions`]?.find(
      (e) => e.role === role,
    )?.permission;
    return stored && op === "insert"
      ? {
          ...stored,
          columns:
            ("columns" in stored ? stored.columns : undefined) ??
            ("*" as const),
        }
      : stored;
  };
  const setPermission = (
    op: DatasetOperation,
    value: InsertPermission | UpdatePermission | DeletePermission | null,
  ) => {
    if (!selected) return;
    const field = `${op}_permissions` as const;
    const existing = selected[field]?.find((e) => e.role === role);
    const entries = (selected[field] ?? []).filter((e) => e.role !== role);
    updateTable({
      ...selected,
      [field]: value
        ? [...entries, { ...existing, role, permission: value }]
        : entries,
    });
  };
  const save = async () => {
    if (!state) return;
    setSaving(true);
    setError("");
    try {
      const policy = draft ? parseDatasetPolicy(draft) : null;
      const response = await fetch(
        `/api/my/artifacts/${encodeURIComponent(artifactId)}/policy`,
        {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            policy,
            expectedPolicyRevision: state.revision,
          }),
        },
      );
      const result = await response.json();
      if (!response.ok) throw Error(result.detail ?? result.error);
      setState({ ...state, policy: result.policy, revision: result.revision });
      setDraft(result.policy);
      setNotice("Access policies saved.");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not save policies");
    } finally {
      setSaving(false);
    }
  };
  const dirty = state && pretty(draft) !== pretty(state.policy);
  return (
    <section aria-label="Access policies" className="space-y-6 text-sm">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div className="max-w-xl">
          <h2 className="text-xl font-semibold tracking-tight">
            Control how data can change
          </h2>
          <p className="mt-2 text-sm leading-6 text-muted">
            Choose allowed actions, then narrow them with column and row rules.
            Everyone with access uses these same rules.
          </p>
        </div>
        {state?.canManage !== false && state && source === null && (
          <Button
            variant="ghost"
            onClick={() => setSource(pretty(draft ?? initial(state.tables)))}
          >
            Edit JSON / YAML
          </Button>
        )}
      </header>
      {error && (
        <p
          role="alert"
          className="rounded-lg border border-danger/30 bg-danger-soft p-3 text-danger"
        >
          {error}
        </p>
      )}
      {!state && !error && (
        <p role="status" className="text-muted">
          Loading data actions…
        </p>
      )}
      {state?.canManage === false && (
        <p className="text-muted">
          Dataset edit access is required to change these rules.
        </p>
      )}
      {state && state.canManage !== false && (
        <>
          {source !== null ? (
            <section className="space-y-4 rounded-xl border border-edge bg-surface p-5">
              <label className="grid gap-2 font-medium">
                Policy JSON or YAML
                <textarea
                  aria-label="Policy JSON or YAML"
                  spellCheck={false}
                  className={`${inputClass} min-h-96 font-mono text-xs leading-6`}
                  value={source}
                  onChange={(e) => setSource(e.target.value)}
                />
              </label>
              <div className="flex flex-wrap gap-2">
                <Button
                  onClick={() => {
                    try {
                      change(parseDatasetPolicy(parseYaml(source)));
                      setSource(null);
                      setTableIndex(0);
                    } catch (e) {
                      setError(
                        e instanceof Error ? e.message : "Invalid policy",
                      );
                    }
                  }}
                >
                  Apply policy source
                </Button>
                <Button variant="ghost" onClick={() => setSource(null)}>
                  Cancel source changes
                </Button>
              </div>
            </section>
          ) : (
            draft && (
              <div className="grid min-w-0 items-start gap-6 lg:grid-cols-[minmax(0,1fr)_260px]">
                <div className="min-w-0 space-y-4">
                  <label className="flex flex-wrap items-center gap-3">
                    <span className="text-xs font-medium text-muted">
                      Rules for table
                    </span>
                    <select
                      aria-label="Policy table"
                      className={`${inputClass} max-w-xs font-mono text-xs`}
                      value={tableIndex}
                      onChange={(e) => setTableIndex(Number(e.target.value))}
                    >
                      {draft.tables.map((t, i) => (
                        <option
                          key={`${t.table.schema}.${t.table.name}`}
                          value={i}
                        >
                          {t.table.schema}.{t.table.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  {selected &&
                    operations.map((op) => (
                      <OperationCard
                        key={`${tableIndex}:${op}`}
                        op={op}
                        permission={permission(op)}
                        columns={columns}
                        onChange={(value) => setPermission(op, value)}
                      />
                    ))}
                </div>
                <aside className="min-w-0 space-y-5">
                  <section className="rounded-xl border border-accent/20 bg-accent-soft/30 p-4">
                    <ShieldCheck size={18} className="mb-3 text-accent" />
                    <h3 className="font-medium">One shared set of rules</h3>
                    <p className="mt-2 text-xs leading-5 text-muted">
                      Sharing decides who has access. These rules apply to
                      viewers, commenters, editors and owners. Existing data
                      stays visible.
                    </p>
                  </section>
                  <section className="space-y-4 rounded-xl border border-edge bg-surface p-4">
                    <h3 className="font-medium">Functions</h3>
                    <label className="grid gap-2 text-xs text-muted">
                      Blocked functions
                      <CommaListInput
                        label="Denied functions"
                        placeholder="e.g. lower, upper"
                        value={draft.execution?.functions?.deny ?? []}
                        onChange={(deny) =>
                          change({
                            ...draft,
                            execution: {
                              ...draft.execution,
                              functions: {
                                ...draft.execution?.functions,
                                deny,
                              },
                            },
                          })
                        }
                      />
                    </label>
                  </section>
                  <section className="px-1">
                    <h3 className="font-medium">Connected apps</h3>
                    {state.writtenBy.length ? (
                      <ul className="mt-3 space-y-3">
                        {state.writtenBy.map((w) => (
                          <li key={w.id}>
                            <a
                              href={`/a/${w.id}`}
                              className="text-sm hover:text-accent"
                            >
                              <span>{w.title ?? w.id}</span>{" "}
                              <span aria-hidden="true">↗</span>
                            </a>
                            <p className="mt-1 text-xs text-muted">
                              {w.mutations.join(", ")}
                            </p>
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <p className="mt-2 text-xs text-muted">
                        No apps use these actions yet.
                      </p>
                    )}
                  </section>
                </aside>
              </div>
            )
          )}
          <details className="rounded-lg border border-edge bg-surface px-4 py-3">
            <summary className="cursor-pointer text-xs text-muted">
              Review permission changes
            </summary>
            <div className="mt-4 grid gap-4 sm:grid-cols-2">
              {[
                ["Current", state.policy],
                ["Proposed", draft],
              ].map(([label, value]) => (
                <div key={String(label)} className="min-w-0">
                  <p className="mb-2 text-xs font-medium">{String(label)}</p>
                  <pre className="max-h-60 overflow-auto rounded-lg bg-raised/30 p-3 text-xs">
                    {pretty(value)}
                  </pre>
                </div>
              ))}
            </div>
          </details>
          <footer className="sticky bottom-3 z-10 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-edge bg-surface/95 px-4 py-3 shadow-lg backdrop-blur-md">
            <p
              role="status"
              className={`text-xs ${notice ? "text-accent" : "text-muted"}`}
            >
              {notice ||
                (dirty
                  ? "You have unsaved rule changes."
                  : "Rules are up to date.")}
            </p>
            <Button
              disabled={saving || source !== null}
              onClick={() => void save()}
              className="rounded-lg px-4 py-2"
            >
              {saving ? "Saving policies…" : "Save access policies"}
            </Button>
          </footer>
        </>
      )}
    </section>
  );
}

const operationCopy = {
  insert: ["Add rows", "Let people submit new records."],
  update: ["Update rows", "Let people change existing records."],
  delete: ["Delete rows", "Let people remove matching records."],
} as const;
type Permission = InsertPermission | UpdatePermission | DeletePermission;
function OperationCard({
  op,
  permission: p,
  columns,
  onChange,
}: {
  op: DatasetOperation;
  permission: Permission | undefined;
  columns: Table["columns"];
  onChange: (value: Permission | null) => void;
}) {
  const [title, description] = operationCopy[op];
  return (
    <section
      className={`min-w-0 overflow-hidden rounded-xl border bg-surface ${p ? "border-edge-bright" : "border-edge"}`}
    >
      <header className="flex items-center justify-between gap-4 px-5 py-4">
        <div>
          <h3 className="font-semibold">{title}</h3>
          <p className="mt-1 text-xs text-muted">{description}</p>
        </div>
        <label className="flex shrink-0 cursor-pointer items-center gap-2 text-xs text-muted">
          <span>{p ? "Allowed" : "Not allowed"}</span>
          <input
            aria-label={`Allow ${op}`}
            type="checkbox"
            className="h-4 w-4 accent-accent"
            checked={!!p}
            onChange={(e) =>
              onChange(
                e.target.checked
                  ? op === "insert"
                    ? { columns: "*", check: {} }
                    : op === "update"
                      ? { columns: "*", filter: {}, check: {} }
                      : { filter: {} }
                  : null,
              )
            }
          />
        </label>
      </header>
      {p && (
        <div className="space-y-5 border-t border-edge px-4 py-5 sm:px-5">
          {"columns" in p && (
            <fieldset className="space-y-3">
              <legend className="mb-2 text-sm font-medium">
                Writable columns
              </legend>
              <label className="flex items-center gap-2 text-xs text-muted">
                <input
                  aria-label={`${op} all columns`}
                  className="accent-accent"
                  type="checkbox"
                  checked={(p.columns ?? "*") === "*"}
                  onChange={(e) =>
                    onChange({ ...p, columns: e.target.checked ? "*" : [] })
                  }
                />
                Allow all columns
              </label>
              {p.columns !== undefined && p.columns !== "*" && (
                <div className="flex flex-wrap gap-2">
                  {columns.map((c) => (
                    <label
                      key={c.name}
                      className={`inline-flex cursor-pointer items-center gap-2 rounded-md border px-2.5 py-1.5 font-mono text-xs ${p.columns?.includes(c.name) ? "border-accent/30 bg-accent-soft text-fg" : "border-edge text-muted"}`}
                    >
                      <input
                        aria-label={`${op} column ${c.name}`}
                        className="accent-accent"
                        type="checkbox"
                        checked={p.columns?.includes(c.name) ?? false}
                        onChange={(e) =>
                          onChange({
                            ...p,
                            columns: e.target.checked
                              ? [...(p.columns as string[]), c.name]
                              : (p.columns as string[]).filter(
                                  (x) => x !== c.name,
                                ),
                          })
                        }
                      />
                      {c.name}
                    </label>
                  ))}
                </div>
              )}
            </fieldset>
          )}
          {"filter" in p && (
            <PolicyConditions
              label={`${op} filter`}
              title="Which existing rows can change?"
              value={p.filter}
              columns={columns}
              onChange={(filter) => onChange({ ...p, filter })}
            />
          )}
          {op !== "delete" && (
            <>
              <PolicyConditions
                label={`${op} check`}
                title="What must the new values satisfy?"
                value={"check" in p ? (p.check ?? {}) : {}}
                columns={columns}
                onChange={(check) =>
                  onChange({ ...p, check } as InsertPermission)
                }
              />
              <Presets
                op={op}
                columns={columns}
                value={"set" in p ? (p.set ?? {}) : {}}
                onChange={(set) => onChange({ ...p, set } as InsertPermission)}
              />
            </>
          )}
        </div>
      )}
    </section>
  );
}
function Presets({
  op,
  value,
  columns,
  onChange,
}: {
  op: string;
  value: NonNullable<InsertPermission["set"]>;
  columns: Table["columns"];
  onChange: (value: NonNullable<InsertPermission["set"]>) => void;
}) {
  const available = columns.filter((c) => !(c.name in value));
  return (
    <details
      className="border-t border-edge pt-4"
      open={Object.keys(value).length > 0 || undefined}
    >
      <summary className="cursor-pointer text-xs font-medium text-muted">
        Set values automatically{" "}
        {Object.keys(value).length > 0 && `(${Object.keys(value).length})`}
      </summary>
      <p className="my-3 text-xs leading-5 text-muted">
        These values override submitted values for the selected columns.
      </p>
      <div className="space-y-2">
        {Object.entries(value).map(([name, constant]) => (
          <div
            key={name}
            className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] items-center gap-2"
          >
            <span className="truncate font-mono text-xs">{name}</span>
            <PolicyValueInput
              label={`${op} preset ${name}`}
              value={constant}
              onChange={(next) =>
                onChange({ ...value, [name]: next as typeof constant })
              }
            />
            <Tooltip content="Remove preset">
              <button
                type="button"
                aria-label={`Remove ${op} preset ${name}`}
                className="rounded-md p-2 text-muted hover:text-danger"
                onClick={() =>
                  onChange(
                    Object.fromEntries(
                      Object.entries(value).filter(([key]) => key !== name),
                    ),
                  )
                }
              >
                <Trash2 size={15} />
              </button>
            </Tooltip>
          </div>
        ))}
      </div>
      {available.length > 0 && (
        <div className="mt-3 flex items-center gap-2">
          <Plus size={14} className="text-muted" />
          <select
            aria-label={`Add ${op} preset`}
            className={`${inputClass} max-w-xs`}
            value=""
            onChange={(e) => {
              if (e.target.value) onChange({ ...value, [e.target.value]: "" });
            }}
          >
            <option value="">Choose a column to set…</option>
            {available.map((c) => (
              <option key={c.name}>{c.name}</option>
            ))}
          </select>
        </div>
      )}
    </details>
  );
}

export function DatasetPolicies({
  artifactId,
  expanded = false,
}: {
  artifactId: string;
  expanded?: boolean;
}) {
  const [open, setOpen] = useState(expanded);
  return (
    <div>
      {!expanded && (
        <Button
          variant="ghost"
          aria-expanded={open}
          onClick={() => setOpen(!open)}
        >
          Manage access policies
        </Button>
      )}
      {open && <DatasetPolicyEditor artifactId={artifactId} />}
    </div>
  );
}
