// services/app/solid/document/ForkArtifact.tsx
/* @jsxImportSource solid-js */
import { createSignal, For, onCleanup, onMount, Show, type JSX } from 'solid-js';
import GitFork from 'lucide-solid/icons/git-fork';
import { loginHref } from '@/lib/login-href';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { Tooltip } from '../components/Tooltip';

type Dataset = { id: string; title: string | null };
export function copiedDatasetsNote(datasets: Dataset[]): string | null {
  const first = datasets[0];
  if (!first) return null;
  return datasets.length === 1 ? `Its dataset “${first.title ?? first.id}” will be copied too` : `Its ${datasets.length} datasets will be copied too`;
}

export interface ForkProps { id: string; title?: string | null; variant?: 'menu' | 'bar'; navigate?: (href: string) => void }
const go = (href: string) => { window.location.assign(href); };

export function ForkConfirm(props: ForkProps & { onClose: () => void }): JSX.Element {
  const [busy, setBusy] = createSignal(false);
  const [datasets, setDatasets] = createSignal<Dataset[] | null>(null);
  const [refusal, setRefusal] = createSignal<string[] | null>(null);
  let active = true;
  let inFlight = false;
  onCleanup(() => { active = false; });
  onMount(() => {
    void fetch(`/api/my/artifacts/${encodeURIComponent(props.id)}/fork`, {
      method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dry_run: true }),
    }).then(async response => {
      if (!response.ok) return;
      const body = await response.json() as { datasets?: Dataset[] };
      if (active && Array.isArray(body.datasets)) setDatasets(body.datasets);
    }).catch(() => {});
  });
  const navigate = (href: string) => (props.navigate ?? go)(href);
  const fork = () => {
    if (inFlight) return;
    inFlight = true; setBusy(true); setRefusal(null);
    let leaving = false;
    void (async () => {
      try {
        const response = await fetch(`/api/my/artifacts/${encodeURIComponent(props.id)}/fork`, { method: 'POST', credentials: 'same-origin' });
        const body = await response.json().catch(() => ({})) as { url?: string; error?: string; details?: string[] };
        if (!active) return;
        if (response.status === 201 && body.url) {
          leaving = true;
          const url = new URL(body.url, location.href);
          navigate(url.pathname + url.search);
          return;
        }
        if (response.status === 401 || (response.status === 409 && body.error === 'sign_in_required')) {
          leaving = true; navigate(loginHref(location, 'fork')); return;
        }
        setRefusal([...new Set(body.details?.length ? body.details : [body.error ?? `could not fork (${response.status})`])]);
      } catch { if (active) setRefusal(['could not fork — try again']); }
      finally { if (!leaving && active) { inFlight = false; setBusy(false); } }
    })();
  };
  return <ConfirmDialog title="Fork this artifact?" description={<>
    <p>{`A copy of “${props.title ?? 'this artifact'}” will be added to your artifacts. You’ll open the new copy after forking. Comments, history and sharing stay with the original.`}</p>
    <Show when={datasets() && copiedDatasetsNote(datasets()!)}><p aria-label="Datasets this fork copies" role="status" class="mt-3 rounded border border-edge bg-raised px-2 py-2 text-xs text-muted">{copiedDatasetsNote(datasets()!)}</p></Show>
    <Show when={refusal()}>{lines => <div aria-label="Fork refused" role="status" class="mt-3 rounded border border-edge bg-raised px-2 py-2 text-xs text-muted"><For each={lines()}>{line => <p class="whitespace-pre-wrap">{line}</p>}</For><button type="button" aria-label="Dismiss fork refusal" onClick={() => setRefusal(null)}>dismiss</button></div>}</Show>
  </>}
    action="Fork and open copy" confirmLabel="Confirm fork" cancelLabel="Cancel fork" busy={busy()} onConfirm={fork} onCancel={props.onClose} />;
}

export function ForkArtifact(props: ForkProps): JSX.Element {
  const [asked, setAsked] = createSignal(false);
  return <div class="relative"><Tooltip content="Fork artifact"><button type="button" aria-label="Fork artifact" onClick={() => setAsked(true)}
    class={props.variant === 'bar' ? 'flex h-9 w-9 items-center justify-center rounded-lg text-muted hover:bg-raised' : 'flex w-full items-center gap-2 rounded px-2 py-2 text-left font-mono text-xs text-muted hover:bg-raised'}>
    <GitFork size={14} /><span class={props.variant === 'bar' ? 'sr-only' : ''}>fork</span></button></Tooltip>
    <Show when={asked()}><ForkConfirm {...props} onClose={() => setAsked(false)} /></Show>
  </div>;
}

// services/app/components/ForkArtifact.tsx
'use client';

/**
 * "make this mine" — the ONE owner of the fork request and its three answers.
 *
 * There are two surfaces onto the same act (the artifact-controls row, and the
 * confirm dialog a `?intent=fork` address opens on mount), so the POST and its
 * outcomes live here once: a second hand-written copy of a fetch with three
 * branches is how two doors drift apart.
 *
 *  - 201 → the copy exists; navigate through the app router, which owns the
 *    old artifact's guarded teardown and the new document lifetime.
 *  - 400 → the door refused BY NAME (an unownable <Mutation> target, a private
 *    ref). The refusal is the useful part — it names what the forker would have
 *    to change — so it is shown rather than swallowed into "try again".
 *  - 409 `sign_in_required` → a fork needs an owner and this browser has no
 *    account; go to /login and come back to THIS address still asking to fork
 *    (lib/intent), so the person does the work once.
 */
import ConfirmDialog from './ConfirmDialog';
import { Tooltip } from './Tooltip';
import { GitFork } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { loginHref } from '@/lib/login-href';
import { useRouter } from '@/lib/navigation';

/** What the last attempt produced: the refusal lines, or nothing. */
interface ForkState {
  /** In flight — the surfaces disable themselves rather than firing twice. */
  busy: boolean;
  /** The door's own words, when it refused. Null while nothing is wrong. */
  refusal: string[] | null;
  /**
   * What the fork would COPY, asked before it is offered. A page that WRITES
   * datasets is copied together with them, under this account — a bigger act
   * than the word "fork" promises on its own, so the dialog says it first. Null
   * until the dry run answers, and if it never does the button still works: the
   * note describes the fork, it does not authorize it.
   */
  datasets: Array<{ id: string; title: string | null }> | null;
  fork: () => void;
  dismiss: () => void;
}

/** The sentence a dialog says when forking would take datasets along. */
export function copiedDatasetsNote(datasets: Array<{ id: string; title: string | null }>): string | null {
  const first = datasets[0];
  if (!first) return null;
  // The singular NAMES it — one dataset is a thing a person recognizes. The
  // plural counts, because five titles in a confirm dialog is a wall.
  return datasets.length === 1
    ? `Its dataset “${first.title ?? first.id}” will be copied too`
    : `Its ${datasets.length} datasets will be copied too`;
}

/** The row and the dialog share this — see the note above the module. */
const CONTROL_ROW = 'flex w-full cursor-pointer items-center gap-2 rounded-[5px] border-0 bg-transparent px-2 py-2 text-left font-mono text-xs text-muted transition-colors hover:bg-raised hover:text-fg disabled:cursor-default disabled:opacity-60';

/**
 * Where /login sends them back to: the address they are looking at, still
 * asking. Read from `window.location` and not from a prop, because the whole
 * point is the address bar the person would otherwise have to find again —
 * including the `$` values of whatever they had narrowed the document to.
 */
const loginBack = (): string => loginHref(window.location, 'fork');

/**
 * The request, its outcomes and the two navigations, as a hook so both
 * surfaces share one implementation.
 */
function useForkArtifact(id: string): ForkState {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [refusal, setRefusal] = useState<string[] | null>(null);
  const [datasets, setDatasets] = useState<ForkState['datasets']>(null);
  /** A navigation is in flight after a 201; nothing may set state into it. */
  const alive = useRef(true);
  const generation = useRef(0);
  useEffect(() => {
    alive.current = true;
    return () => { alive.current = false; generation.current += 1; };
  }, [id]);
  /*
   * THE DRY RUN, once the dialog is open. It creates nothing, so it costs a
   * request and no consequence, and its failure is deliberately silent: a fork
   * that would copy datasets is still a fork this person may ask for, and a
   * scary red line about a preview call is not the refusal they need to read.
   */
  useEffect(() => {
    let current = true;
    void (async () => {
      try {
        const res = await fetch(`/api/my/artifacts/${id}/fork`, {
          method: 'POST', credentials: 'same-origin',
          headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dry_run: true }),
        });
        if (!res.ok) return;
        const body = (await res.json().catch(() => ({}))) as { datasets?: Array<{ id: string; title: string | null }> };
        if (current && Array.isArray(body.datasets)) setDatasets(body.datasets);
      } catch { /* the note is an extra; its absence changes nothing */ }
    })();
    return () => { current = false; };
  }, [id]);
  /**
   * The re-entrancy guard is a REF, not the `busy` state, and that is the
   * whole of it: `setBusy(true)` takes effect at the next render, so two
   * clicks inside one tick both read `busy === false` and `disabled` has not
   * applied to the button yet — and this door creates a real artifact per
   * call. `busy` stays, but only to say so on the surface.
   */
  const inFlight = useRef(false);

  const fork = useCallback(() => {
    if (inFlight.current) return;
    inFlight.current = true;
    setBusy(true);
    setRefusal(null);
    const started = generation.current;
    const current = () => alive.current && started === generation.current;
    /** This attempt ends in a navigation, so the guard never reopens. */
    let leaving = false;
    void (async () => {
      try {
        const res = await fetch(`/api/my/artifacts/${id}/fork`, { method: 'POST', credentials: 'same-origin' });
        const body = (await res.json().catch(() => ({}))) as { url?: string; error?: string; details?: string[] };
        if (!current()) return;
        if (res.status === 201 && body.url) {
          leaving = true;
          // By PATH, on the origin this page is already on: the reply's host is
          // derived from the request's headers, which a browser reaching the
          // app through an internal hostname (a live session) does not share.
          const copy = new URL(body.url, window.location.href);
          router.push(copy.pathname + copy.search);
          return;
        }
        if (res.status === 401 || (res.status === 409 && body.error === 'sign_in_required')) {
          leaving = true;
          router.push(loginBack());
          return;
        }
        // ONCE EACH: a page naming the same unreachable ref from three
        // positions is refused three times in identical words, and three
        // copies of one sentence reads as three problems.
        setRefusal([...new Set(body.details?.length ? body.details : [body.error ?? `could not fork (${res.status})`])]);
      } catch {
        if (current()) setRefusal(['could not fork — try again']);
      } finally {
        // A 201 or `sign_in_required` LEAVES: the guard stays closed and the
        // label stays busy through the navigation, because a button that
        // re-enables itself while the browser is already on its way to the
        // copy is a second copy.
        if (!leaving && current()) {
          inFlight.current = false;
          setBusy(false);
        }
      }
    })();
  }, [id, router]);

  return { busy, refusal, datasets, fork, dismiss: useCallback(() => setRefusal(null), []) };
}

/** The refusal, said where the act was asked for. */
function ForkRefusal({ lines, onDismiss }: { lines: string[]; onDismiss: () => void }) {
  return (
    <div aria-label="Fork refused" role="status" className="mt-1 rounded-[5px] border border-edge bg-raised px-2 py-2 font-mono text-[11px] text-muted">
      {lines.map((line) => <p key={line} className="whitespace-pre-wrap">{line}</p>)}
      <button
        type="button"
        aria-label="Dismiss fork refusal"
        onClick={onDismiss}
        className="mt-1 cursor-pointer border-0 bg-transparent p-0 font-mono text-[11px] text-accent"
      >
        dismiss
      </button>
    </div>
  );
}

/** Fork is offered to every reader; the server decides the read ACL.
 * The bar variant keeps refusals visible beside the initiating control. */
export default function ForkArtifact({ id, title = null, variant = 'menu' }: {
  id: string;
  title?: string | null;
  /** Settings row or compact app-bar button. */
  variant?: 'menu' | 'bar';
}) {
  const [asked, setAsked] = useState(false);
  return (
    <div className="relative">
      <Tooltip content="Fork artifact"><button
        type="button" aria-label="Fork artifact" onClick={() => setAsked(true)}
        className={variant === 'bar' ? 'flex h-9 w-9 cursor-pointer items-center justify-center rounded-[8px] border-0 bg-transparent text-muted hover:bg-raised hover:text-fg' : CONTROL_ROW}
      >
        <GitFork size={14} strokeWidth={1.75} />
        <span className={variant === 'bar' ? 'sr-only' : 'flex-1'}>fork</span>
      </button></Tooltip>
      {asked && <ForkConfirm id={id} title={title} onClose={() => setAsked(false)} />}
    </div>
  );
}

/**
 * The confirm dialog a `?intent=fork` address opens.
 *
 * It asks because the instruction arrived in a URL: a fork writes a copy into
 * somebody's account, and an address anyone may hand over must not be able to
 * do that silently. Focus goes to Cancel and stays inside the dialog,
 * Escape is cancel — the house dialog contract (components/ConfirmDialog).
 */
export function ForkConfirm({ id, title, onClose }: { id: string; title: string | null; onClose: () => void }) {
  const { busy, refusal, datasets, fork, dismiss } = useForkArtifact(id);
  const note = datasets && copiedDatasetsNote(datasets);
  return <ConfirmDialog title="Fork this artifact?"
    description={`A copy of “${title ?? 'this artifact'}” will be added to your artifacts. You’ll open the new copy after forking. Comments, history and sharing stay with the original.`}
    action="Fork and open copy" confirmLabel="Confirm fork" cancelLabel="Cancel fork"
    busy={busy} onConfirm={fork} onCancel={onClose}>
    {/* Before the one Fork button, never as a second choice: there is no fork
        of an app that leaves its datasets behind, so this is what will happen
        rather than something to opt into. */}
    {note && <p aria-label="Datasets this fork copies" role="status" className="mt-3 rounded-[5px] border border-edge bg-raised px-2 py-2 font-mono text-[11px] text-muted">{note}</p>}
    {refusal && <ForkRefusal lines={refusal} onDismiss={dismiss} />}
  </ConfirmDialog>;
}
