// services/app/solid/components/ShareLink.tsx
/* @jsxImportSource solid-js */
import { createSignal, For, onMount, Show, type JSX } from 'solid-js';
import type { DatasetCatalog } from '@/lib/datasets/types';
import type { DatasetAccess, SharingPatch, Visibility } from '@/lib/artifacts';
import type { ShareEntry, ShareRole } from '@/lib/share-roles';
import { DialogShell } from '@/solid/components/DialogShell';
interface SharingState {
  visibility: Visibility; linkRole: ShareRole; shares: ShareEntry[]; access?: DatasetAccess;
  datasetKind?: DatasetCatalog['kind']; policyVersion?: number; canPrivate?: boolean;
  writtenBy?: Array<{ id: string; title: string | null; mutations: string[] }>;
}

function RolePicker(props: { label: string; value: ShareRole; onChange: (role: ShareRole) => void }): JSX.Element {
  const [open, setOpen] = createSignal(false);
  return <span class="relative inline-block"><button type="button" aria-label={props.label} aria-expanded={open()} onClick={() => setOpen(value => !value)} class="rounded border border-edge bg-surface p-1">{props.value === 'editor' ? 'can edit' : 'can view'}</button><Show when={open()}><span role="listbox" aria-label={props.label} class="absolute right-0 top-full z-50 min-w-24 rounded border border-edge bg-surface p-1 shadow-xl"><For each={(['viewer', 'editor'] as const)}>{role => <button type="button" role="option" aria-selected={props.value === role} onClick={() => { setOpen(false); props.onChange(role); }} class="block w-full p-1 text-left hover:bg-raised">{role === 'editor' ? 'can edit' : 'can view'}</button>}</For></span></Show></span>;
}
/** Sharing edits stay on the scoped artifact endpoint; copied links contain no secret or query. */
export default function ShareLink(props: { artifactId?: string; title?: string; format?: string; datasetKind?: DatasetCatalog['kind']; editable?: boolean; class?: string; url?: string; startOpen?: boolean; onClose?: () => void }): JSX.Element {
  const [open, setOpen] = createSignal(Boolean(props.startOpen));
  const [state, setState] = createSignal<SharingState | null>(null);
  const [email, setEmail] = createSignal('');
  const [error, setError] = createSignal('');
  const [copied, setCopied] = createSignal(false);
  const [confirmReadOnly, setConfirmReadOnly] = createSignal(false);
  const canManage = () => Boolean(props.artifactId && props.editable);
  const endpoint = () => `/api/my/artifacts/${encodeURIComponent(props.artifactId!)}/sharing`;
  onMount(() => { if (canManage()) void fetch(endpoint()).then(async response => { if (!response.ok) throw new Error('Could not load sharing.'); return response.json() as Promise<SharingState>; }).then(setState).catch(cause => setError(cause.message)); });
  const update = async (patch: SharingPatch) => {
    if (!canManage()) return false;
    setError('');
    try {
      const response = await fetch(endpoint(), { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) });
      if (!response.ok) throw new Error('Could not update sharing.');
      setState(await response.json() as SharingState); return true;
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not update sharing.'); return false; }
  };
  const copyLink = () => { void navigator.clipboard?.writeText(new URL(props.url ?? location.pathname, location.origin).href); setCopied(true); };
  const postgres = () => props.format === 'dataset' && (props.datasetKind === 'postgres' || state()?.datasetKind === 'postgres');
  const showWrites = () => props.format === 'dataset' && state() && !postgres() && state()?.policyVersion !== 2;
  return <>
    <Show when={!props.startOpen}><button type="button" aria-label="Share" class={props.class} onClick={() => canManage() ? setOpen(true) : copyLink()}>{copied() ? 'copied' : state() ? `share: ${state()!.visibility}` : 'Share'}</button></Show>
    <Show when={open()}><DialogShell onClose={() => { setOpen(false); props.onClose?.(); }}><div role="dialog" aria-modal="true" aria-label="Sharing" class="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4">
      <div class="max-h-[90vh] w-full max-w-lg space-y-4 overflow-auto rounded-xl border border-edge bg-surface p-6 text-sm text-fg">
        <div class="flex justify-between"><h2 class="text-lg font-semibold">Sharing {props.title}</h2><button type="button" aria-label="Close sharing" onClick={() => { setOpen(false); props.onClose?.(); }}>Close</button></div>
        <button type="button" aria-label="Copy link" onClick={copyLink} class="w-full rounded border border-edge p-2">{copied() ? 'copied' : 'copy link'}</button>
        <div class="flex gap-1"><For each={(['public', 'unlisted', 'private'] as const).filter(value => value !== 'private' || state()?.canPrivate !== false)}>{visibility =>
          <button type="button" aria-label={`Make ${visibility}`} aria-pressed={state()?.visibility === visibility} disabled={!state()} onClick={() => void update({ visibility })} class="flex-1 rounded border border-edge p-2 aria-pressed:border-accent">{visibility}</button>
        }</For></div>
        <input aria-label="Invite email" type="email" value={email()} onInput={event => setEmail(event.currentTarget.value)} placeholder="email@example.com" class="w-full rounded border border-edge bg-surface p-2" />
        <Show when={state()} fallback={<p role="status">Loading sharing…</p>}>{current => <>
          <Show when={current().visibility !== 'private'}><div class="flex items-center justify-between">Anyone with the link<RolePicker label="Link role" value={current().linkRole ?? 'viewer'} onChange={role => void update({ linkRole: role })} /></div></Show>
          <Show when={postgres()}><p aria-label="PostgreSQL read-only access">Editors can manage the connection, notebook and whitelist. Viewers can query exposed data. Database rows cannot be changed here.</p></Show>
          <Show when={showWrites()}><section aria-label="Dataset writes" class="space-y-2 border-t border-edge pt-4"><h3 class="font-semibold">Writes</h3><div class="flex gap-2"><button type="button" aria-label="Make read-only" aria-pressed={current().access !== 'readwrite'} onClick={() => current().writtenBy?.length ? setConfirmReadOnly(true) : void update({ access: 'read' })}>read-only</button><button type="button" aria-label="Make read & write" aria-pressed={current().access === 'readwrite'} onClick={() => void update({ access: 'readwrite' })}>read &amp; write</button></div>
            <For each={current().writtenBy ?? []}>{writer => <p>{writer.title ?? writer.id} · {writer.mutations.join(', ')}</p>}</For>
            <Show when={confirmReadOnly()}><div role="alertdialog" aria-label="Make this dataset read-only?"><p>Documents that write here will stop working until writes are enabled again. The rows stay.</p><button type="button" aria-label="Confirm read-only" onClick={() => { void update({ access: 'read' }); setConfirmReadOnly(false); }}>Make read-only</button><button type="button" onClick={() => setConfirmReadOnly(false)}>Keep writable</button></div></Show>
          </section></Show>
          <section class="space-y-2 border-t border-edge pt-4"><h3 class="font-semibold">People</h3><For each={current().shares}>{entry => <div class="flex items-center gap-2"><span class="min-w-0 flex-1 truncate">{entry.email}</span><RolePicker label={`Role for ${entry.email}`} value={entry.role} onChange={role => void update({ shares: current().shares.map(person => person.email === entry.email ? { ...person, role } : person) })} /><button type="button" aria-label={`Remove ${entry.email}`} onClick={() => void update({ shares: current().shares.filter(person => person.email !== entry.email) })}>Remove</button></div>}</For>
            <form class="flex gap-2" onSubmit={event => { event.preventDefault(); const address = email().trim(); if (!address) return; void update({ shares: [...current().shares, { email: address, role: 'viewer' }] }); setEmail(''); }}><button type="submit" aria-label="Add email">add</button></form>
          </section>
          <Show when={props.format === 'dataset' && !postgres()}><a aria-label="Manage access policies" href={`/a/${props.artifactId}/edit`} onClick={() => setOpen(false)}>Manage data actions ↗</a></Show>
        </>}</Show>
        <Show when={error()}><p role="alert" class="text-danger">{error()}</p></Show>
      </div>
    </div></DialogShell></Show>
  </>;
}

// services/app/components/ShareLink.tsx
'use client';

/**
 * "share" — ONE button. For an owner it opens the centered sharing dialog: copy link,
 * the READ acl (visibility), the PEOPLE (invited emails, each with a role —
 * `can view` or `can edit`, under EVERY visibility, because a public
 * document can have editors too) and, for a dataset, the WRITE acl (the
 * access toggle and who writes to it) together, so there is a single place
 * to answer "who can see this, who can change it, and how do I hand it to
 * them". An anonymous owner manages all of that except `private`, which
 * needs an account to anchor its ACL and is hidden from them; someone who
 * owns nothing here gets a plain one-click copy.
 *
 * The URL is location minus the fragment on purpose: #edit is a MODE, never
 * part of the link you hand someone. Shelf menus pass the selected artifact's
 * address explicitly. The ACL
 * surface is session-only (/api/my/artifacts/<id>/sharing).
 */
import {DatasetPolicies} from '@/components/DatasetPolicies';
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { useTrustedPortalContainer } from '@/components/TrustedUi';
import { Crop, Check, EyeOff, Globe, Link as LinkIcon, Lock, PenLine, X } from 'lucide-react';
import { SelectMenu } from '@/components/SelectMenu';
import { Tooltip } from '@/components/Tooltip';
import type { DatasetCatalog } from '@/lib/datasets/types';
import type { DatasetAccess, SharingPatch, Visibility } from '@/lib/artifacts';
import { SHARE_ROLES, SHARE_ROLE_LABEL, type ShareEntry, type ShareRole } from '@/lib/share-roles';

interface SharingState {
  datasetKind?: DatasetCatalog['kind'];
  visibility: Visibility;
  /** GENERAL ACCESS: what the link grants whoever holds it. Meaningless while `private`. */
  linkRole: ShareRole;
  shares: ShareEntry[];
  /** Datasets: the WRITE ACL and the documents that would stop working without it. */
  access?: DatasetAccess;
  writtenBy?: Array<{ id: string; title: string | null; mutations: string[] }>;
  /** False for an anonymous owner — `private` has no ACL to anchor without an account. */
  canPrivate?: boolean;
}

const VISIBILITY_ICONS = { public: Globe, unlisted: EyeOff, private: Lock } as const;

/**
 * The role list, as the house dropdown wants it. A native <select> draws its
 * options with OS widgets, which lands system chrome in the middle of a
 * terminal-graphite panel — so both role controls here are SelectMenu
 * listboxes over the SAME options, because they are the same question asked
 * of a link and of a person.
 */
const ROLE_OPTIONS = SHARE_ROLES.map((r) => ({ value: r, label: SHARE_ROLE_LABEL[r] }));

export default function ShareLink({
  className,
  artifactId,
  title,
  owner = false,
  editable = false,
  format,
  datasetKind,
  variant = 'chip',
  url,
  onClose,
  onSocialPreview,
}: {
  className: string;
  /** Enables the ACL dialog; without it this is just the copy button. */
  artifactId?: string;
  /** The displayed name of the artifact being shared. */
  title?: string | null;
  /** This viewer OWNS the artifact — owners and editors manage its ACL. */
  owner?: boolean;
  /** Editors and owners may manage sharing. */
  editable?: boolean;
  /** The artifact's format — the writes row exists for a dataset and nothing else. */
  format?: string;
  /** Known before sharing loads; the API also supplies this for shelf callers. */
  datasetKind?: DatasetCatalog['kind'];
  /** `menu` is a document-control row; `dialog` opens directly from an external menu. */
  variant?: 'chip' | 'menu' | 'dialog';
  /** Explicit artifact address when opened from a shelf or table. */
  url?: string;
  /** Dialog-only callers unmount the sharing surface when dismissed. */
  onClose?: () => void;
  /** Editors may configure the card without managing access. */
  onSocialPreview?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const [open, setOpen] = useState(variant === 'dialog');
  const [state, setState] = useState<SharingState | null>(null);
  const [email, setEmail] = useState('');
  const [error, setError] = useState<string | null>(null);
  /** Closing writes with documents that write here asks once — see below. */
  const [confirmReadOnly, setConfirmReadOnly] = useState(false);

  // Revert through an effect so unmounting mid-flash cancels the timer.
  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 1500);
    return () => clearTimeout(t);
  }, [copied]);

  const canManage = (owner || editable) && !!artifactId;

  // Loaded on MOUNT, not on open: the button itself carries the verdict
  // ("share: public"), so it must know the answer before any click.
  useEffect(() => {
    if (!canManage || state) return;
    void (async () => {
      const res = await fetch(`/api/my/artifacts/${artifactId}/sharing`).catch(() => null);
      if (res?.ok) setState((await res.json()) as SharingState);
      else setError('could not load sharing');
    })();
  }, [canManage, artifactId, state]);

  const put = async (patch: SharingPatch) => {
    setError(null);
    const res = await fetch(`/api/my/artifacts/${artifactId}/sharing`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(patch),
    }).catch(() => null);
    if (res?.ok) setState((await res.json()) as SharingState);
    else setError('could not update sharing');
  };

  const copyLink = () => {
    void navigator.clipboard?.writeText(url ? new URL(url, location.origin).href : `${location.origin}${location.pathname}`);
    setCopied(true);
  };

  if (!canManage && !onSocialPreview) {
    if (variant === 'menu') {
      return (
        <button
          type="button"
          aria-label="Share"
          onClick={copyLink}
          className="flex w-full cursor-pointer items-center gap-2 rounded-[5px] border-0 bg-transparent px-2 py-2 text-left font-mono text-xs text-muted transition-colors hover:bg-raised hover:text-fg"
        >
          {copied ? <Check size={14} /> : <LinkIcon size={14} />}
          {copied ? 'copied link' : 'share'}
        </button>
      );
    }
    return (
      <Tooltip content={copied ? 'copied!' : 'copy link'}>
        <button type="button" aria-label="Share" onClick={copyLink} className={className}>
          {copied ? <Check size={12} /> : <LinkIcon size={12} />} <span className="hidden sm:inline">{copied ? 'copied' : 'share'}</span>
        </button>
      </Tooltip>
    );
  }

  const VerdictIcon = VISIBILITY_ICONS[state?.visibility ?? 'private'];
  /*
   * The WRITES row (datasets only).
   *
   * It lives here rather than in its own control because it answers the same
   * question the rest of this dialog does: who can do what with this thing.
   * `visibility` is who may READ it; `access` is who may CHANGE it through a
   * document. Neither implies the other, so they are two rows, not one picker.
   */
  const postgres = format === 'dataset' && (datasetKind === 'postgres' || state?.datasetKind === 'postgres');
  const writable = !postgres && state?.access === 'readwrite';
  const writers = state?.writtenBy ?? [];
  const showWrites = format === 'dataset' && !!state && !postgres;
  const setAccess = (next: DatasetAccess) => {
    // Closing writes never touches the ROWS — every mutate call re-checks — but
    // it does stop the documents that write, so it says which ones first. With
    // nothing writing here there is nothing to warn about, and it just flips.
    if (next === 'read' && writers.length > 0 && !confirmReadOnly) { setConfirmReadOnly(true); return; }
    setConfirmReadOnly(false);
    void put({ access: next });
  };
  const toggle = () => setOpen((o) => !o);
  return (
    <span className={variant === 'menu' ? 'relative block' : 'relative inline-flex items-center gap-1'}>
      {variant === 'dialog' ? null : variant === 'menu' ? (
        <button
          type="button"
          aria-label="Share"
          onClick={toggle}
          className={`flex w-full cursor-pointer items-center gap-2 rounded-[5px] border-0 bg-transparent px-2 py-2 text-left font-mono text-xs transition-colors hover:bg-raised hover:text-fg ${open ? 'text-accent' : 'text-muted'}`}
        >
          <VerdictIcon size={14} />
          <span>{state ? `sharing · ${state.visibility}` : 'sharing'}</span>
        </button>
      ) : (
      <Tooltip content="share / who can view" positioning={{ placement: 'bottom-end' }}>
        <button
          type="button"
          aria-label="Share"
          onClick={toggle}
          className={className}
        >
          <VerdictIcon size={12} />{' '}
          {/* The compact chip keeps its text from crowding a narrow toolbar. */}
          <span className="hidden whitespace-nowrap sm:inline">
            {state ? <>share: {state.visibility}</> : 'share'}
            {showWrites && writable && <span className="text-amber-500"> · writable</span>}
          </span>
        </button>
      </Tooltip>
      )}
      {open && (
        <SharePanel title={`Share “${title ?? (format === 'folder' ? 'Untitled folder' : 'Untitled')}”`} onClose={() => { setOpen(false); onClose?.(); }}>
          <button
            type="button"
            aria-label="Copy link"
            onClick={copyLink}
            className="mb-4 flex w-full cursor-pointer items-center justify-center gap-2 rounded-[5px] border border-edge bg-raised px-3 py-2.5 text-muted hover:border-edge-bright hover:text-fg"
          >
            {copied ? <Check size={11} /> : <LinkIcon size={11} />} {copied ? 'copied' : 'copy link'}
          </button>
          {onSocialPreview && (
            <button type="button" aria-label="Edit social preview" onClick={() => { setOpen(false); onSocialPreview(); }} className="mb-4 flex w-full cursor-pointer items-center gap-2 rounded-[5px] border border-edge px-3 py-2.5 text-muted hover:border-edge-bright hover:text-fg">
              <Crop size={14} /> social preview <span className="ml-auto text-[11px] text-faint">upload image or frame document</span>
            </button>
          )}
          {canManage && !state && !error && <p className="text-muted">loading…</p>}
          {error && <p className="text-red-400">{error}</p>}
          {state && (
            <>
              <div className="flex gap-1">
                {(
                  [
                    ['public', 'anyone with the link · listed on your profile'],
                    ['unlisted', 'anyone with the link · not listed anywhere'],
                    ['private', 'only you and invited emails'],
                  ] as const
                ).map(([v, tip]) => {
                  // `private` needs an account to anchor its ACL; an anonymous
                  // owner is not offered a tier the door would refuse.
                  if (v === 'private' && state.canPrivate === false) return null;
                  const Icon = VISIBILITY_ICONS[v];
                  return (
                    <Tooltip key={v} content={tip}>
                      <button
                        type="button"
                        aria-label={`Make ${v}`}
                        onClick={() => void put({ visibility: v })}
                      className={`flex-1 cursor-pointer rounded-[4px] border px-2 py-2.5 whitespace-nowrap ${state.visibility === v ? 'border-accent/40 bg-accent-soft text-accent' : 'border-edge text-muted hover:border-edge-bright hover:text-fg'}`}
                      >
                        <Icon size={11} className="mr-1 inline" /> {v}
                      </button>
                    </Tooltip>
                  );
                })}
              </div>
              {/*
                * GENERAL ACCESS, second half. The row above says who the LINK
                * REACHES; this says what it grants them once it has. Hidden
                * while `private`, where the link reaches nobody and a role
                * would be a control with no effect — the server still
                * REMEMBERS the choice, so coming back out of private restores
                * it rather than silently resetting to `can view`.
                */}
              {state.visibility !== 'private' && (
                <label className="mt-2 flex items-center justify-between gap-2 text-muted">
                  <span>anyone with the link</span>
                  <span className="w-32 shrink-0">
                    <SelectMenu
                      ariaLabel="Link role"
                      value={state.linkRole ?? 'viewer'}
                      options={ROLE_OPTIONS}
                      onChange={(v) => void put({ linkRole: v as ShareRole })}
                    />
                  </span>
                </label>
              )}
              {postgres && <p aria-label="PostgreSQL read-only access" className="mt-5 border-t border-edge pt-4 leading-relaxed text-muted">Editors can manage the connection, notebook and whitelist. Viewers can query exposed data. Database rows cannot be changed here.</p>}
              {showWrites && (
                <div className="mt-5 border-t border-edge pt-4">
                  <p className="mb-1 flex items-center justify-between text-faint">
                    <span className="uppercase tracking-wider">writes</span>
                    <PenLine size={11} />
                  </p>
                  <div className="flex gap-1">
                    {([
                      ['read', 'read-only', 'documents may only read this data'],
                      ['readwrite', 'read & write', 'you and dataset editors may add, change and remove rows'],
                    ] as const).map(([value, label, tip]) => (
                      <Tooltip key={value} content={tip}>
                        <button
                          type="button"
                          aria-label={value === 'read' ? 'Make read-only' : 'Make read & write'}
                          aria-pressed={(state.access ?? 'read') === value}
                          onClick={() => setAccess(value)}
                          className={`flex-1 cursor-pointer rounded-[4px] border px-2 py-1.5 whitespace-nowrap ${(state.access ?? 'read') === value
                            ? value === 'readwrite'
                              ? 'border-amber-500/40 bg-amber-500/10 text-amber-500'
                              : 'border-accent/40 bg-accent-soft text-accent'
                            : 'border-edge text-muted hover:border-edge-bright hover:text-fg'}`}
                        >
                          {label}
                        </button>
                      </Tooltip>
                    ))}
                  </div>
                  <p className="mt-2 leading-relaxed text-muted">
                    {writable
                      ? 'Sharing controls who can view and manage this dataset. Data rules below control which actions everyone with view access may run. Without a data policy, only dataset editors may write rows.'
                      : 'Documents can only read this dataset. A <Mutation> naming it is refused when you publish.'}
                  </p>
                  {writers.length > 0 && (
                    <div className="mt-2">
                      <p className="mb-1 uppercase tracking-wider text-faint">written by</p>
                      {writers.map((w) => (
                        <div key={w.id} className="flex items-center justify-between py-0.5">
                          <span className="truncate">{w.title ?? w.id}</span>
                          <span className="ml-2 shrink-0 text-faint">{w.mutations.join(', ')}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {confirmReadOnly && (
                    <div role="alert" className="mt-2 rounded-[4px] border border-danger/40 bg-danger-soft p-2 leading-relaxed">
                      <span className="text-danger">{writers.length} document{writers.length === 1 ? '' : 's'} write{writers.length === 1 ? 's' : ''} here.</span>{' '}
                      Their buttons will stop working until you turn writes back on. The rows stay.
                      <div className="mt-1.5 flex gap-1">
                        <button
                          type="button"
                          aria-label="Confirm read-only"
                          onClick={() => { setConfirmReadOnly(false); void put({ access: 'read' }); }}
                          className="cursor-pointer rounded-[4px] border border-danger/40 px-2 py-1 text-danger hover:bg-danger/10"
                        >
                          make read-only
                        </button>
                        <button
                          type="button"
                          aria-label="Keep writable"
                          onClick={() => setConfirmReadOnly(false)}
                          className="cursor-pointer rounded-[4px] border border-edge px-2 py-1 text-muted hover:text-fg"
                        >
                          keep writable
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
              {/* PEOPLE — under every visibility. `can view` on a public
                  document grants nothing the link does not, and says so;
                  `can edit` is the whole reason the list is here at all. */}
              <div className="mt-5 border-t border-edge pt-4">
                <p className="mb-1 uppercase tracking-wider text-faint">people</p>
                {state.shares.map((e) => (
                  <div key={e.email} className="flex items-center justify-between gap-2 py-0.5">
                    <span className="min-w-0 truncate">{e.email}</span>
                    <span className="flex shrink-0 items-center gap-1">
                      <Tooltip
                        content="already viewable by link"
                        disabled={state.visibility === 'private' || e.role === 'editor'}
                      >
                        <span className="w-32 shrink-0">
                          <SelectMenu
                            ariaLabel={`Role for ${e.email}`}
                            value={e.role}
                            options={ROLE_OPTIONS}
                            onChange={(v) => void put({ shares: state.shares.map((x) => (x.email === e.email ? { ...x, role: v as ShareRole } : x)) })}
                          />
                        </span>
                      </Tooltip>
                      <button
                        type="button"
                        aria-label={`Remove ${e.email}`}
                        onClick={() => void put({ shares: state.shares.filter((x) => x.email !== e.email) })}
                        className="cursor-pointer text-muted hover:text-fg"
                      >
                        <X size={11} />
                      </button>
                    </span>
                  </div>
                ))}
                <form
                    className="mt-1 flex gap-1"
                    onSubmit={(ev) => {
                      ev.preventDefault();
                      const addr = email.trim();
                      if (!addr) return;
                      // A new person starts as a viewer; the row's control promotes them.
                      void put({ shares: [...state.shares, { email: addr, role: 'viewer' }] });
                      setEmail('');
                    }}
                  >
                    <input
                      aria-label="Invite email"
                      placeholder="email@example.com"
                      value={email}
                      onChange={(ev) => setEmail(ev.target.value)}
                      className="min-w-0 flex-1 rounded-[4px] border border-edge bg-transparent px-2 py-1 text-fg outline-none focus:border-edge-bright"
                    />
                    <button
                      type="submit"
                      aria-label="Add email"
                      className="cursor-pointer rounded-[4px] border border-edge px-2 py-1 text-muted hover:border-edge-bright hover:text-fg"
                    >
                      add
                    </button>
                  </form>
              </div>
              {format === 'dataset' && !postgres && artifactId && <DatasetPolicies artifactId={artifactId} />}
            </>
          )}
        </SharePanel>
      )}
    </span>
  );
}

/** One viewport-level sharing surface. Portaling keeps it centered even when
 * its trigger lives inside an animated controls popover. */
function SharePanel({ onClose, children, title }: {
  title: string;
  onClose: () => void;
  children: React.ReactNode;
}) {
  const portal = useTrustedPortalContainer();
  useEffect(() => {
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); };
    window.addEventListener('keydown', escape);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener('keydown', escape);
    };
  }, [onClose]);

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-3 sm:p-8">
      <button
        type="button"
        aria-label="Close sharing by clicking outside"
        onClick={onClose}
        className="absolute inset-0 cursor-default border-0 bg-black/45 p-0 backdrop-blur-[2px]"
      />
      <section
        role="dialog"
        aria-modal="true"
        aria-label="Sharing"
        className="relative z-10 flex w-full max-w-2xl animate-[rise_.16s_ease-out] flex-col overflow-hidden rounded-[9px] border border-edge-bright bg-surface font-mono text-xs shadow-2xl"
        style={{ maxHeight: 'calc(100svh - 24px)' }}
      >
        <header className="flex items-start gap-4 border-b border-edge px-4 py-4 sm:px-6">
          <div className="min-w-0 flex-1">
            <h2 className="break-words text-base font-semibold text-fg">{title}</h2>
            <p className="mt-1 text-[11px] text-faint">Manage access, invite people, or copy the link.</p>
          </div>
          <button
            type="button"
            aria-label="Close sharing"
            autoFocus
            onClick={onClose}
            className="ml-auto inline-flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-[4px] text-muted hover:bg-raised hover:text-fg"
          >
            <X size={16} />
          </button>
        </header>
        <div className="overflow-y-auto px-4 py-4 sm:px-6 sm:py-5">
          {children}
        </div>
      </section>
    </div>,
    portal ?? document.body,
  );
}
