// services/app/solid/components/SharedWithYou.tsx
/* @jsxImportSource solid-js */
import { createMemo, createSignal, For, Show, type JSX } from 'solid-js';
import type { WorkspaceSharedItem } from '@/lib/workspace';
import { SHARE_ROLE_LABEL, SHARE_ROLES } from '@/lib/share-roles';
import { FormatBadge, formatLabel, LINK, MicroLabel, PANEL, TABLE_ROW, timeAgo } from './ui';

const FORMAT_ORDER = ['markup', 'dataset', 'viz', 'image', 'pdf'];
export default function SharedWithYou(props: { items: WorkspaceSharedItem[] }): JSX.Element {
  const [query, setQuery] = createSignal('');
  const [formatPicks, setFormatPicks] = createSignal<string[]>([]);
  const [rolePicks, setRolePicks] = createSignal<string[]>([]);
  const toggle = (kind: 'format' | 'role', value: string) => { const set = kind === 'format' ? setFormatPicks : setRolePicks; set(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value]); };
  const formats = createMemo(() => { const present = new Set<string>(props.items.map(item => item.format ?? 'markup')); return [...FORMAT_ORDER.filter(format => present.has(format)), ...[...present].filter(format => !FORMAT_ORDER.includes(format))]; });
  const roles = createMemo(() => SHARE_ROLES.filter(role => props.items.some(item => item.role === role)));
  const q = () => query().trim().toLowerCase();
  const filtering = () => Boolean(q() || formatPicks().length || rolePicks().length);
  const visible = createMemo(() => props.items.filter(item => {
    const format = item.format ?? 'markup';
    const searchable = [item.title, item.description, item.id, item.owner_username ? `@${item.owner_username}` : null, formatLabel(format), SHARE_ROLE_LABEL[item.role]].filter(Boolean).join(' ').toLowerCase();
    return (!q() || searchable.includes(q())) && (!formatPicks().length || formatPicks().includes(format)) && (!rolePicks().length || rolePicks().includes(item.role));
  }));
  return <Show when={props.items.length}><section aria-label="Shared with you" class="mt-8"><div class="mb-2"><MicroLabel>shared with you</MicroLabel></div><div class={PANEL}><div class="flex flex-wrap items-center gap-2 border-b border-edge px-4 py-2"><input aria-label="Search shared artifacts" placeholder="search shared artifacts" value={query()} onInput={event => setQuery(event.currentTarget.value)} class="min-w-32 flex-1 border-0 bg-transparent font-mono text-xs text-fg placeholder:text-faint focus:outline-none" /><Show when={formats().length >= 2 || roles().length >= 2}><span class="flex shrink-0 flex-wrap items-center gap-1.5 border-edge sm:ml-auto sm:border-l sm:pl-2"><Show when={formats().length >= 2}><For each={formats()}>{format => <button type="button" aria-label={`Filter ${format}`} aria-pressed={formatPicks().includes(format)} onClick={() => toggle('format', format)} class="rounded-full border border-edge px-2 py-0.5 font-mono text-[10px]">{formatLabel(format)}</button>}</For></Show><Show when={roles().length >= 2}><For each={roles()}>{role => <button type="button" aria-label={`Filter ${role}`} aria-pressed={rolePicks().includes(role)} onClick={() => toggle('role', role)} class="rounded-full border border-edge px-2 py-0.5 font-mono text-[10px]">{SHARE_ROLE_LABEL[role]}</button>}</For></Show></span></Show><Show when={filtering()}><span class="shrink-0 border-l border-edge pl-2 font-mono text-[10px] text-faint">{visible().length}/{props.items.length}</span></Show></div><div class="overflow-x-auto"><table class="w-full text-left font-mono text-xs"><tbody><Show when={visible().length === 0}><tr class={TABLE_ROW}><td colspan={5} class="px-4 py-6 text-center text-faint">{q() ? <>nothing matches &ldquo;{query().trim()}&rdquo;</> : 'nothing matches the active filters'}</td></tr></Show><For each={visible()}>{item => <tr class={TABLE_ROW}><td class="px-3 py-2"><a href={`/a/${item.id}`} aria-label={`Open shared artifact ${item.id}`} class={LINK}>{item.title || item.id}</a></td><td class="px-3 py-2 text-muted">{item.owner_username ? `@${item.owner_username}` : ''}</td><td class="px-3 py-2 text-muted" aria-label={`Your role on ${item.id}`}>{SHARE_ROLE_LABEL[item.role]}</td><td class="px-3 py-2"><FormatBadge format={item.format} /></td><td class="px-3 py-2 text-right whitespace-nowrap text-muted">{timeAgo(item.updated_at)}</td></tr>}</For></tbody></table></div></div></section></Show>;
}

// services/app/components/SharedWithYou.tsx
'use client';

import { Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { FormatBadge, formatLabel, LINK, MicroLabel, PANEL, TABLE_ROW, timeAgo } from '@/components/ui';
import { SHARE_ROLE_LABEL, SHARE_ROLES } from '@/lib/share-roles';
import type { WorkspaceSharedItem } from '@/lib/workspace';

/**
 * The dashboard's recipient-side view of `artifact_shares` — the rediscovery
 * surface a share otherwise lacks (lose the link, lose the document), and
 * where the recipient learns what they may DO with it (their role). Rows
 * link to the universal `/a/<id>` form: the viewer is NOT the owner, so
 * pretty owner-URLs are decoration they may not be able to resolve, and the
 * short form is the one address every reader can always use.
 *
 * Renders NOTHING when nothing is shared: an empty "shared with you" panel
 * would read as a bug on every fresh dashboard.
 */
const FORMAT_ORDER: string[] = ['markup', 'dataset', 'viz', 'image', 'pdf'];

function FilterChip({ value, label, active, onToggle }: {
  value: string;
  label: string;
  active: boolean;
  onToggle: (value: string) => void;
}) {
  return (
    <button
      type="button"
      aria-label={`Filter ${value}`}
      aria-pressed={active}
      onClick={() => onToggle(value)}
      className={`inline-flex cursor-pointer items-center rounded-full border px-2 py-0.5 font-mono text-[10px] leading-none whitespace-nowrap transition-colors ${
        active
          ? 'border-accent bg-accent-soft text-accent'
          : 'border-edge bg-transparent text-faint hover:border-edge-bright hover:text-muted'
      }`}
    >
      {label}
    </button>
  );
}

type SharedListItem = WorkspaceSharedItem;

export default function SharedWithYou({ items }: { items: SharedListItem[] }) {
  const [query, setQuery] = useState('');
  const [formatPicks, setFormatPicks] = useState<string[]>([]);
  const [rolePicks, setRolePicks] = useState<string[]>([]);

  const togglePick = (set: React.Dispatch<React.SetStateAction<string[]>>) => (value: string) =>
    set((picks) => (picks.includes(value) ? picks.filter((pick) => pick !== value) : [...picks, value]));

  const formatsPresent = new Set<string>(items.map((item) => item.format ?? 'markup'));
  const formats = [
    ...FORMAT_ORDER.filter((format) => formatsPresent.has(format)),
    ...[...formatsPresent].filter((format) => !FORMAT_ORDER.includes(format)),
  ];
  const roles = SHARE_ROLES.filter((role) => items.some((item) => item.role === role));
  const showFormats = formats.length >= 2;
  const showRoles = roles.length >= 2;
  const q = query.trim().toLowerCase();
  const filtering = Boolean(q) || formatPicks.length > 0 || rolePicks.length > 0;

  const visible = useMemo(() => items.filter((item) => {
    const format = item.format ?? 'markup';
    const searchable = [
      item.title,
      item.description,
      item.id,
      item.owner_username ? `@${item.owner_username}` : null,
      formatLabel(format),
      SHARE_ROLE_LABEL[item.role],
    ].filter(Boolean).join(' ').toLowerCase();
    return (!q || searchable.includes(q)) &&
      (formatPicks.length === 0 || formatPicks.includes(format)) &&
      (rolePicks.length === 0 || rolePicks.includes(item.role));
  }), [items, q, formatPicks, rolePicks]);

  if (items.length === 0) return null;
  return (
    <section aria-label="Shared with you" className="mt-8">
      <MicroLabel>shared with you</MicroLabel>
      <div className={`${PANEL} mt-2`}>
        <div className="flex flex-wrap items-center gap-2 border-b border-edge px-4 py-2">
          <Search size={13} className="shrink-0 text-faint" />
          <input
            aria-label="Search shared artifacts"
            placeholder="search shared artifacts"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            className="min-w-32 flex-1 border-0 bg-transparent font-mono text-xs text-fg placeholder:text-faint focus:outline-none"
          />
          {(showFormats || showRoles) && (
            <span className="flex shrink-0 flex-wrap items-center gap-1.5 border-edge sm:ml-auto sm:border-l sm:pl-2">
              {showFormats && formats.map((format) => (
                <FilterChip
                  key={format}
                  value={format}
                  label={formatLabel(format)}
                  active={formatPicks.includes(format)}
                  onToggle={togglePick(setFormatPicks)}
                />
              ))}
              {showFormats && showRoles && <span aria-hidden="true" className="mx-1 h-3 w-px bg-edge" />}
              {showRoles && roles.map((role) => (
                <FilterChip
                  key={role}
                  value={role}
                  label={SHARE_ROLE_LABEL[role]}
                  active={rolePicks.includes(role)}
                  onToggle={togglePick(setRolePicks)}
                />
              ))}
            </span>
          )}
          {filtering && (
            <span className="shrink-0 border-l border-edge pl-2 font-mono text-[10px] tabular-nums text-faint">
              {visible.length}/{items.length}
            </span>
          )}
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left font-mono text-xs">
            <tbody>
              {visible.length === 0 && (
                <tr className={TABLE_ROW}>
                  <td colSpan={5} className="px-4 py-6 text-center text-faint">
                    {q ? <>nothing matches &ldquo;{query.trim()}&rdquo;</> : 'nothing matches the active filters'}
                  </td>
                </tr>
              )}
              {visible.map((a) => (
                <tr key={a.id} className={TABLE_ROW}>
                  <td className="px-3 py-2">
                    <a href={`/a/${a.id}`} aria-label={`Open shared artifact ${a.id}`} className={LINK}>
                      {a.title || a.id}
                    </a>
                  </td>
                  <td className="px-3 py-2 text-muted">{a.owner_username ? `@${a.owner_username}` : ''}</td>
                  <td className="px-3 py-2 text-muted" aria-label={`Your role on ${a.id}`}>{SHARE_ROLE_LABEL[a.role]}</td>
                  <td className="px-3 py-2">
                    <FormatBadge format={a.format} />
                  </td>
                  <td className="px-3 py-2 text-right whitespace-nowrap text-muted">{timeAgo(a.updated_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}
