// services/app/solid/components/Shelf.tsx
/* @jsxImportSource solid-js */
import { createMemo, createSignal, For, Show, type JSX } from 'solid-js';
import FolderIcon from 'lucide-solid/icons/folder';
import FolderPlus from 'lucide-solid/icons/folder-plus';
import Inbox from 'lucide-solid/icons/inbox';
import GridIcon from 'lucide-solid/icons/layout-grid';
import ListIcon from 'lucide-solid/icons/list';
import Search from 'lucide-solid/icons/search';
import Globe from 'lucide-solid/icons/globe';
import Lock from 'lucide-solid/icons/lock';
import EyeOff from 'lucide-solid/icons/eye-off';
import Pencil from 'lucide-solid/icons/pencil';
import FolderInput from 'lucide-solid/icons/folder-input';
import Trash2 from 'lucide-solid/icons/trash-2';
import { writeBrowserArtifact } from '@/lib/browser-artifact-write';
import { buildShelf, parentOfRow, type ShelfRow } from '@/lib/shelf';
import { CARD_RENDER_GENERATION } from '@/lib/export-card';
import { pageDataChanged } from '@/web/page-data-events';
import { MicroLabel, PANEL, timeAgo } from './ui';
import { Tooltip } from './Tooltip';
import { ConfirmDialog } from './ConfirmDialog';
import RowMenu from './RowMenu';
import ShareLink from './ShareLink';
import { DialogShell } from '@/solid/components/DialogShell';
import { apiFetch } from '../lib/api';

type Actions = 'none' | 'share' | 'full';
interface Props {
  rows: ShelfRow[];
  actions?: Actions;
  scopeParentId?: string | null;
  parentId?: string | null;
  canCreateFolders?: boolean;
  assets?: boolean;
  showVisibility?: boolean;
  dates?: 'relative' | 'absolute';
  /** Home also filters "Shared with you" by this search box, so the caller hears every keystroke. */
  onQuery?: (query: string) => void;
}
const nameOf = (row: ShelfRow) => row.title ?? row.id;
const VISIBILITIES = ['public', 'unlisted', 'private'];

function Visibility(props: { row: ShelfRow }): JSX.Element {
  return <Show when={props.row.visibility}><Tooltip content={props.row.visibility}><span role="img" tabIndex={0} aria-label={`${nameOf(props.row)} is ${props.row.visibility}`} class="relative z-10 inline-flex shrink-0 rounded bg-slate-700/75 p-1 text-white"><Show when={props.row.visibility === 'public'} fallback={<Show when={props.row.visibility === 'private'} fallback={<EyeOff size={12} />}><Lock size={12} /></Show>}><Globe size={12} /></Show></span></Tooltip></Show>;
}

/** One document jacket: preview, caption and independent actions share the same surface. */
function ArtifactCover(props: { row: ShelfRow; showVisibility: boolean; children: JSX.Element }): JSX.Element {
  return <div class="artifact-cover">
    <a href={props.row.url} rel="external" aria-label={`Open ${nameOf(props.row)}`} class="artifact-cover-link" />
    <div class="artifact-cover-preview"><img src={`/a/${props.row.id}/export?format=jpg&mode=card&v=${props.row.version}&r=${CARD_RENDER_GENERATION}`} alt="" loading="lazy" /></div>
    <span class="artifact-cover-fold" aria-hidden="true" />
    <Show when={props.showVisibility}><div class="artifact-cover-visibility"><Visibility row={props.row} /></div></Show>
    <div class="artifact-cover-front">
      <span class="min-w-0 flex-1 line-clamp-2 font-mono text-[12px] font-semibold leading-4">{nameOf(props.row)}</span>
      <span class="relative z-[3] inline-flex shrink-0">{props.children}</span>
    </div>
  </div>;
}

export function RowActions(props: { row: ShelfRow; level: Actions; folders: ShelfRow[]; childCount: number; onRemoved: (id: string) => void; onChanged: () => void; showEdit?: boolean }): JSX.Element {
  const [confirm, setConfirm] = createSignal(false);
  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [moving, setMoving] = createSignal(false);
  const [moveFilter, setMoveFilter] = createSignal('');
  const [sharing, setSharing] = createSignal(false);
  const [renaming, setRenaming] = createSignal(false);
  const [draft, setDraft] = createSignal('');
  const [parentId, setParentId] = createSignal(parentOfRow(props.row));
  const saveName = async () => {
    const title = draft().trim();
    setRenaming(false);
    if (!title || title === props.row.title) return;
    const result = await writeBrowserArtifact(props.row.id, { title }).catch(() => null);
    if (result?.ok) { props.row.title = title; props.onChanged(); pageDataChanged(); }
  };
  const move = async (id: string | null) => {
    const result = await writeBrowserArtifact(props.row.id, { parent_id: id }).catch(() => null);
    if (result?.ok) { setParentId(id); setMoving(false); setMoveFilter(''); props.onChanged(); pageDataChanged(); }
  };
  const closeMove = () => { setMoving(false); setMoveFilter(''); };
  const shownFolders = createMemo(() => {
    const q = moveFilter().trim().toLowerCase();
    return q ? props.folders.filter(f => nameOf(f).toLowerCase().includes(q)) : props.folders;
  });
  const remove = async () => {
    setBusy(true); setError(null);
    const result = await fetch(`/api/my/artifacts/${props.row.id}`, { method: 'DELETE' }).catch(() => null);
    setBusy(false);
    if (!result?.ok) { setError('Could not delete this artifact.'); return; }
    setConfirm(false); props.onRemoved(props.row.id); pageDataChanged();
  };
  return <>
    <Show when={renaming()}><input aria-label="Folder name" autofocus value={draft()} onInput={event => setDraft(event.currentTarget.value)} onBlur={() => void saveName()} onKeyDown={event => { if (event.key === 'Enter') void saveName(); if (event.key === 'Escape') setRenaming(false); }} class="relative z-20 w-32 border-b border-accent bg-transparent font-mono text-xs focus:outline-none" /></Show>
    <Show when={props.level === 'full'}>
      <span class="relative z-10 inline-flex shrink-0 items-center gap-1">
        <Show when={props.row.format !== 'folder' && props.showEdit !== false}><Tooltip content="edit"><a aria-label={`Edit ${nameOf(props.row)}`} href={`/a/${props.row.id}#edit`} class="shelf-secondary-action text-muted hover:text-accent"><Pencil size={13} /></a></Tooltip></Show>
        <RowMenu name={nameOf(props.row)} items={[
          { label: `Manage sharing for ${nameOf(props.row)}`, text: 'share', icon: () => <span>↗</span>, onSelect: () => setSharing(true) },
          ...(props.row.format === 'folder' ? [{ label: `Rename ${nameOf(props.row)}`, text: 'rename', icon: () => <Pencil size={12} />, onSelect: () => { setDraft(props.row.title ?? ''); setRenaming(true); } }] : []),
          { label: `Move ${nameOf(props.row)}`, text: 'move to folder', icon: () => <FolderInput size={12} />, onSelect: () => setMoving(true) },
          { label: `Delete ${nameOf(props.row)}`, text: props.childCount ? `delete (${props.childCount} inside)` : 'delete', icon: () => <Trash2 size={12} />, danger: true, onSelect: () => setConfirm(true) },
        ]} />
        <Show when={sharing()}><ShareLink artifactId={props.row.id} title={nameOf(props.row)} format={props.row.format} editable url={props.row.url} startOpen onClose={() => setSharing(false)} /></Show>
      </span>
    </Show>
    <Show when={moving()}><DialogShell onClose={closeMove} initialFocus="[autofocus]"><div role="dialog" aria-label={`Move ${nameOf(props.row)}`} class="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div class="w-full max-w-sm rounded border border-edge bg-surface p-4"><h2 class="mb-3 font-mono text-sm">Move {nameOf(props.row)}</h2><input aria-label="Filter folders" placeholder="filter folders" autofocus value={moveFilter()} onInput={event => setMoveFilter(event.currentTarget.value)} class="mb-2 w-full rounded-[4px] border border-edge bg-transparent px-2 py-1.5 font-mono text-xs text-fg focus:border-accent focus:outline-none" /><div class="max-h-64 overflow-y-auto"><button type="button" aria-label="Move to root" aria-current={parentId() === null ? 'location' : undefined} onClick={() => void move(null)} class="block w-full px-2 py-1 text-left">root</button><For each={shownFolders()}>{folder => <button type="button" aria-label={`Move to ${nameOf(folder)}`} aria-current={parentId() === folder.id ? 'location' : undefined} disabled={folder.id === props.row.id || (folder.ancestor_ids ?? []).includes(props.row.id)} onClick={() => void move(folder.id)} class="block w-full px-2 py-1 text-left disabled:opacity-40">{nameOf(folder)}</button>}</For><Show when={moveFilter() && shownFolders().length === 0}><p class="px-2 py-1 font-mono text-xs text-faint">no folder matches</p></Show></div><button type="button" aria-label="Close folder picker" onClick={closeMove} class="mt-3 text-xs text-muted">Cancel</button></div></div></DialogShell></Show>
    <Show when={confirm()}><ConfirmDialog title={`Delete ${nameOf(props.row)}?`} description={props.childCount ? `Delete ${nameOf(props.row)} and the ${props.childCount} item${props.childCount === 1 ? '' : 's'} inside it? They go to the trash, and you can restore them any time.` : `Delete ${nameOf(props.row)}? It goes to the trash, and you can restore it any time.`} action="Delete" confirmLabel="Confirm delete" danger busy={busy()} error={error()} onCancel={() => setConfirm(false)} onConfirm={() => void remove()} /></Show>
  </>;
}

export default function Shelf(props: Props): JSX.Element {
  const [added, setAdded] = createSignal<ShelfRow[]>([]);
  const [removed, setRemoved] = createSignal<string[]>([]);
  const [revision, setRevision] = createSignal(0);
  const [query, setQuery] = createSignal('');
  const [filters, setFilters] = createSignal<string[]>([]);
  const [view, setView] = createSignal<'grid' | 'list'>('grid');
  const [page, setPage] = createSignal(0);
  const [naming, setNaming] = createSignal(false);
  const [name, setName] = createSignal('');
  const [creating, setCreating] = createSignal(false);
  const all = createMemo(() => { revision(); return [...props.rows.filter(row => !removed().includes(row.id)), ...added()]; });
  const scoped = createMemo(() => props.scopeParentId === undefined ? all() : all().filter(row => parentOfRow(row) === props.scopeParentId));
  const filtered = createMemo(() => scoped().filter(row => (!query().trim() || `${row.title ?? ''} ${row.id}`.toLowerCase().includes(query().trim().toLowerCase())) && (!filters().length || filters().includes(row.visibility ?? ''))));
  const shelf = createMemo(() => buildShelf(filtered()));
  const folders = createMemo(() => all().filter(row => row.format === 'folder'));
  const availableFilters = createMemo(() => VISIBILITIES.filter(value => scoped().some(row => row.visibility === value)));
  const toggle = (value: string) => { setFilters(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value]); setPage(0); };
  const childCount = (id: string) => all().filter(row => parentOfRow(row) === id).length;
  const remove = (id: string) => setRemoved(current => [...current, id, ...all().filter(row => (row.ancestor_ids ?? []).includes(id)).map(row => row.id)]);
  const createFolder = async () => {
    const title = name().trim();
    if (!title || creating()) return;
    setCreating(true);
    const response = await apiFetch('/api/my/artifacts', 'POST', { format: 'folder', title, parent_id: props.parentId ?? null }).catch(() => null);
    setCreating(false);
    if (!response?.ok) return;
    const body = await response.json() as Partial<ShelfRow> & { id: string };
    setAdded(current => [...current, { id: body.id, url: body.url ?? `/a/${body.id}`, title: body.title ?? title, format: 'folder', version: body.version ?? 1, visibility: body.visibility ?? 'private', updated_at: body.updated_at ?? new Date().toISOString(), parent_id: body.parent_id ?? props.parentId ?? null }]);
    setName(''); setNaming(false); pageDataChanged();
  };
  const docs = () => shelf().documents.slice(view() === 'list' ? page() * 10 : 0, view() === 'list' ? page() * 10 + 10 : undefined);
  return <div aria-label="Shelf" class="min-w-0">
    <div class="mb-5 flex min-w-0 flex-col gap-2 rounded-[6px] border border-edge bg-surface px-3 py-1.5 sm:flex-row sm:flex-wrap sm:items-center"><div class="flex min-w-0 items-center gap-2 sm:flex-1"><Search size={13} class="shrink-0 text-faint" /><input aria-label="Search artifacts" placeholder="search artifacts" value={query()} onInput={event => { setQuery(event.currentTarget.value); setPage(0); props.onQuery?.(event.currentTarget.value); }} class="h-7 min-w-0 flex-1 border-0 bg-transparent font-mono text-xs text-fg placeholder:text-faint focus:outline-none" /></div><div class="flex flex-wrap items-center gap-2 sm:contents"><Show when={availableFilters().length >= 2}><For each={availableFilters()}>{value => <button type="button" aria-label={`Filter ${value}`} aria-pressed={filters().includes(value)} onClick={() => toggle(value)} class="rounded-full border border-edge px-2 py-0.5 font-mono text-[10px] text-muted">{value}</button>}</For></Show><span role="group" aria-label="Shelf view" class="ml-auto inline-flex shrink-0 gap-1 border-l border-edge pl-1.5"><button type="button" aria-label="Grid view" aria-pressed={view() === 'grid'} onClick={() => setView('grid')} class={view() === 'grid' ? 'rounded bg-accent-soft p-1.5 text-accent' : 'p-1.5 text-faint'}><GridIcon size={14} /></button><button type="button" aria-label="List view" aria-pressed={view() === 'list'} onClick={() => setView('list')} class={view() === 'list' ? 'rounded bg-accent-soft p-1.5 text-accent' : 'p-1.5 text-faint'}><ListIcon size={14} /></button></span><Show when={props.canCreateFolders}><Show when={naming()} fallback={<Tooltip content="create a folder here"><button type="button" aria-label="New folder" onClick={() => setNaming(true)} class="inline-flex h-7 items-center gap-1 px-2 font-mono text-[10px] text-muted"><FolderPlus size={12} />new folder</button></Tooltip>}><input aria-label="Folder name" autofocus value={name()} onInput={event => setName(event.currentTarget.value)} onKeyDown={event => { if (event.key === 'Enter') void createFolder(); if (event.key === 'Escape') setNaming(false); }} class="h-7 w-36 rounded border border-edge bg-transparent px-1.5 font-mono text-xs" /><span class="font-mono text-[10px] text-faint">{creating() ? 'creating…' : 'enter'}</span></Show></Show></div></div>
    <Show when={shelf().folders.length}><section aria-label="Folders" class="relative z-20 mb-6"><div class="mb-2"><MicroLabel>folders</MicroLabel></div><ul class={view() === 'grid' ? 'grid grid-cols-2 gap-3 lg:grid-cols-4' : 'grid grid-cols-1 gap-3 sm:grid-cols-2'}><For each={shelf().folders}>{row => {
      const papers = () => all().filter(item => parentOfRow(item) === row.id && item.format === 'markup').slice(0, 5);
      return <li class={view() === 'grid' ? 'group relative rounded-md p-3 hover:bg-raised/60' : `group relative flex min-w-0 items-center gap-2 rounded-[6px] p-3 ${PANEL}`}>
        <Show when={view() === 'grid'} fallback={<><FolderIcon size={15} class="shrink-0 text-accent" /><a href={row.url} rel="external" aria-label={`Open folder ${nameOf(row)}`} class="min-w-0 flex-1 truncate font-mono text-sm font-semibold text-fg after:absolute after:inset-0">{nameOf(row)}</a><Show when={childCount(row.id)}><span class="font-mono text-[10px] text-faint">{childCount(row.id)}</span></Show><Show when={props.showVisibility !== false}><Visibility row={row} /></Show><RowActions row={row} level={props.actions ?? 'none'} folders={folders()} childCount={childCount(row.id)} onRemoved={remove} onChanged={() => setRevision(value => value + 1)} /></>}>
          <div aria-label={`Preview of folder ${nameOf(row)}`} class="folder-cover">
            <a href={row.url} rel="external" aria-label={`Open folder ${nameOf(row)}`} class="absolute inset-0 z-[2] rounded-md focus-visible:outline-2 focus-visible:outline-accent" />
            <div class="folder-cover-tab"><span class="truncate font-mono text-[10px] tabular-nums">{childCount(row.id) ? `${childCount(row.id)} artifact${childCount(row.id) === 1 ? '' : 's'}` : 'empty folder'}</span></div>
            <div class="folder-cover-back" />
            <Show when={!papers().length}><div class="folder-cover-empty" aria-hidden="true"><Inbox size={28} /></div></Show>
            <Show when={props.showVisibility !== false && row.visibility}><span aria-label={`${nameOf(row)} is ${row.visibility}`} class="folder-cover-visibility absolute left-2 top-[27px] z-[3] rounded bg-slate-700/75 p-1 text-white"><Show when={row.visibility === 'public'} fallback={<Show when={row.visibility === 'private'} fallback={<EyeOff size={12} />}><Lock size={12} /></Show>}><Globe size={12} /></Show></span></Show>
            <div class="folder-cover-papers" style={{ '--paper-width': papers().length > 2 ? '48%' : '61%' }}><For each={papers()}>{(item, index) => <div class="folder-cover-paper" style={{ '--paper-position': index() / Math.max(1, papers().length - 1) }}><img src={`/a/${item.id}/export?format=jpg&mode=card&v=${item.version}&r=${CARD_RENDER_GENERATION}`} alt="" loading="lazy" /></div>}</For></div>
            <div class="folder-cover-front"><span class="min-w-0 flex-1 truncate pr-2 font-mono text-[13px] font-semibold">{nameOf(row)}</span><span class="relative z-[3] ml-auto"><RowActions row={row} level={props.actions ?? 'none'} folders={folders()} childCount={childCount(row.id)} onRemoved={remove} onChanged={() => setRevision(value => value + 1)} /></span></div>
          </div>
        </Show>
      </li>;
    }}</For></ul></section></Show>
    <Show when={docs().length}><section aria-label="Artifacts">
      <div class="mb-2"><MicroLabel>artifacts</MicroLabel></div>
      <ul aria-label={view() === 'grid' ? 'Artifact grid' : 'Artifact list'} class={view() === 'grid' ? 'grid grid-cols-2 gap-3 lg:grid-cols-4' : 'flex flex-col gap-2'}>
        <For each={docs()}>{row => <li class={view() === 'grid' ? 'group relative min-w-0 rounded-md p-3 hover:bg-raised/60' : `group relative ${PANEL} flex items-center gap-3 px-3 py-2`}>
          <Show when={view() === 'grid'} fallback={<>
            <a href={row.url} rel="external" aria-label={`Open ${nameOf(row)}`} class="flex min-w-0 flex-1 items-center gap-2 font-mono text-sm font-medium text-fg hover:text-accent"><img src={`/a/${row.id}/export?format=jpg&mode=card&v=${row.version}&r=${CARD_RENDER_GENERATION}`} alt="" width={24} height={24} loading="lazy" class="size-6 shrink-0 rounded-sm border border-edge bg-raised object-cover object-top" /><span class="truncate">{nameOf(row)}</span></a>
            <Show when={props.showVisibility !== false}><Visibility row={row} /></Show>
            <span class="font-mono text-[10px] text-faint">{timeAgo(row.updated_at)}</span>
            <RowActions row={row} level={props.actions ?? 'none'} folders={folders()} childCount={0} onRemoved={remove} onChanged={() => setRevision(value => value + 1)} />
          </>}>
            <ArtifactCover row={row} showVisibility={props.showVisibility !== false}>
              <RowActions row={row} level={props.actions ?? 'none'} folders={folders()} childCount={0} onRemoved={remove} onChanged={() => setRevision(value => value + 1)} />
            </ArtifactCover>
          </Show>
        </li>}</For>
      </ul>
    </section></Show>
    <Show when={view() === 'list' && shelf().documents.length > 10}><div class="mt-3 flex justify-between font-mono text-xs"><span aria-label="Page range">{page() * 10 + 1}-{Math.min((page() + 1) * 10, shelf().documents.length)} of {shelf().documents.length}</span><span class="flex gap-2"><button type="button" aria-label="Previous page" disabled={page() === 0} onClick={() => setPage(value => value - 1)}>Previous</button><button type="button" aria-label="Next page" disabled={(page() + 1) * 10 >= shelf().documents.length} onClick={() => setPage(value => value + 1)}>Next</button></span></div></Show>
    <Show when={!shelf().folders.length && !shelf().documents.length && (query() || filters().length)}><p aria-label="No matches" class="font-mono text-xs text-faint">nothing matches the active {query() ? 'search' : 'filters'}</p></Show>
  </div>;
}

// services/app/components/Shelf.tsx
'use client';

/**
 * THE SHELF — one presentation for the homepage and public profiles.
 *
 * `/` (the dashboard) and `/@handle` (the public profile) answer different
 * questions with the same drive-like presentation. This component fetches
 * nothing: each page runs its own query and hands over rows plus what the
 * viewer may do with them.
 *
 * The capability props are the seam. A profile passes no `views`, so no
 * spline is drawn and no column is reserved — OPTIONAL FIELDS DEGRADE, which
 * is the whole test of whether the seam is in the right place. If adding view
 * counts to the dashboard required touching the profile, this would be the
 * wrong shape.
 *
 * Partitioning and recency order live in `lib/shelf` (pure). This file owns
 * the grid/list presentation and hands list mode to `ArtifactTable`.
 */
import { useMemo, useState } from 'react';
import { Check, Folder, FolderInput, FolderPlus, LayoutGrid, Link2, List as ListIcon, Pencil, Search, Trash2 } from 'lucide-react';
import RowMenu, { confirmDeleteArtifact } from '@/components/RowMenu';
import { MoveMenu, type PickerFolder } from '@/components/FolderPicker';
import { ArtifactTable } from '@/components/TokenBrowser';
import { Tooltip } from '@/components/Tooltip';
import { dateStamp, MicroLabel, PANEL, timeAgo, VISIBILITY_TIPS, VisibilityPill } from '@/components/ui';
import { ViewsMark } from '@/components/ViewsMark';
import { buildShelf, groupShelfByRecency, parentOfRow, type ShelfRow } from '@/lib/shelf';
import { CARD_RENDER_GENERATION } from '@/lib/export-card';

/**
 * The row shape lives with the POLICY (lib/shelf), because it is what a page
 * ANSWERS rather than how the answer looks — three server modules build these
 * rows and none of them may import React. Re-exported here so every existing
 * `import type { ShelfRow } from '@/components/Shelf'` still reads.
 */
export type { ShelfRow } from '@/lib/shelf';

/**
 * WHAT A VIEWER MAY DO WITH A ROW — a LEVEL, not a boolean, because the three
 * surfaces need three different subsets:
 *
 * - `none`  a stranger reading
 * - `share` a PROFILE: handing someone the link is the whole point of the
 *           page, and nothing there should change the document
 * - `full`  the owner's dashboard: share, edit, and the overflow menu
 *
 * Withholding is the DEFAULT. A capability that has to be asked for cannot be
 * granted by forgetting a prop.
 */
export type ShelfActions = 'none' | 'share' | 'full';

export interface ShelfProps {
  rows: ShelfRow[];
  actions?: ShelfActions;
  /**
   * Show the band of datasets and images. The dashboard is where material is
   * managed; a profile is about the documents, and listing the material there
   * is the junk-drawer `listPublicArtifactsByUser` already refuses to be.
   */
  assets?: boolean;
  /**
   * How a timestamp reads. RELATIVE ("3 hrs ago") narrates activity and
   * belongs on the owner's own surfaces, where recency is the thing being
   * judged. ABSOLUTE ("Aug 29, 2026") is the public face of a timestamp — a
   * profile is a record, not a feed, and "just now" tells a visitor nothing
   * they can cite. Same split `dateStamp`/`timeAgo` have always drawn.
   */
  dates?: 'relative' | 'absolute';
  /** The folder that a folder created from this shelf should belong to. */
  parentId?: string | null;
  /** Folder pages opt into creation without inheriting the homepage's row actions. */
  canCreateFolders?: boolean;
}

/** Create a child folder in place, preserving the shelf's current view state. */
function NewFolder({ parentId, onMade }: { parentId: string | null; onMade: (row: ShelfRow) => void }) {
  const [naming, setNaming] = useState(false);
  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);

  const create = async () => {
    const title = name.trim();
    if (!title || busy) return;
    setBusy(true);
    const response = await fetch('/api/my/artifacts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ format: 'folder', title, parent_id: parentId }),
    }).catch(() => null);
    setBusy(false);
    if (!response?.ok) return;
    const body = (await response.json().catch(() => null)) as (Partial<ShelfRow> & { id?: string }) | null;
    if (!body?.id) return;
    onMade({
      ...body,
      id: body.id,
      url: body.url ?? `/a/${body.id}`,
      title: body.title ?? title,
      format: 'folder',
      version: body.version ?? 1,
      visibility: body.visibility ?? 'private',
      updated_at: body.updated_at ?? new Date().toISOString(),
      parent_id: body.parent_id ?? parentId,
    });
    setName('');
    setNaming(false);
  };

  if (!naming) {
    return (
      <Tooltip content="create a folder here">
        <button
          type="button"
          aria-label="New folder"
          onClick={() => setNaming(true)}
          className="inline-flex h-7 shrink-0 cursor-pointer items-center gap-1 rounded-[4px] px-2 font-mono text-[10px] text-muted transition-colors hover:bg-raised hover:text-accent"
        >
          <FolderPlus size={12} /> new folder
        </button>
      </Tooltip>
    );
  }

  return (
    <span className="inline-flex h-7 shrink-0 items-center gap-1">
      <input
        aria-label="Folder name"
        placeholder="folder name"
        autoFocus
        value={name}
        onChange={(event) => setName(event.target.value)}
        onKeyDown={(event) => {
          if (event.key === 'Enter') { event.preventDefault(); void create(); }
          if (event.key === 'Escape') { event.preventDefault(); setName(''); setNaming(false); }
        }}
        className="h-7 w-36 rounded-[4px] border border-edge bg-transparent px-1.5 font-mono text-[11px] text-fg focus:border-edge-bright focus:outline-none"
      />
      <span className="font-mono text-[10px] text-faint">{busy ? 'creating…' : 'enter'}</span>
    </span>
  );
}

/**
 * THE FOLDERS STRIP — a third partition of the shelf (lib/shelf `folders`),
 * above the documents and absent for an account that has none, so nothing moves
 * for someone who never makes one.
 *
 * A folder is an artifact, so a tile is an ordinary link to `/a/<id>`; what it
 * adds over a document card is that a folder has no thumbnail worth taking (its
 * own card would be a picture of this listing) and a count instead.
 */
function FolderTile({ row, count, level, folders, onDeleted }: { row: ShelfRow; count: number; level: ShelfActions; folders: PickerFolder[]; onDeleted: (id: string) => void }) {
  /**
   * RENAMING IS THE ONE VERB A FOLDER HAS THAT A DOCUMENT DOES NOT NEED HERE.
   * A document is renamed in its editor's Title field; a folder has no content
   * and therefore no editor, so the pencil beside it opened on nothing. The
   * verb moves into the menu with the other folder verbs and edits the tile in
   * place, through the metadata door (PATCH {title}) rather than the replace
   * one — a name should not archive a version.
   */
  const [renaming, setRenaming] = useState(false);
  const [draft, setDraft] = useState('');
  const [title, setTitle] = useState<string | null>(row.title);
  const shown = { ...row, title };
  const save = () => {
    const next = draft.trim();
    setRenaming(false);
    if (!next || next === title) return;
    setTitle(next);
    void fetch(`/api/my/artifacts/${row.id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: next }),
    }).catch(() => { /* the next load reads the server's answer */ });
  };
  if (renaming) {
    return (
      <li className={`reveal relative flex items-center gap-2 px-3 py-2.5 ${PANEL} border-accent`}>
        <Folder size={14} className="shrink-0 text-accent" />
        <input
          aria-label="Folder name"
          autoFocus
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={save}
          onKeyDown={(e) => {
            if (e.key === 'Enter') { e.preventDefault(); save(); }
            if (e.key === 'Escape') setRenaming(false);
          }}
          className="min-w-0 flex-1 border-0 bg-transparent font-mono text-sm font-semibold text-fg focus:outline-none"
        />
      </li>
    );
  }
  return (
    <li className={`reveal group relative flex items-center gap-2 px-3 py-2.5 ${PANEL} transition-colors hover:border-edge-bright`}>
      <Folder size={14} className="shrink-0 text-faint transition-colors group-hover:text-accent" />
      {/* A STRETCHED LINK: the whole tile opens the folder, while the actions
          beside it sit above the pseudo-element rather than inside the anchor
          (a <button> in an <a> is invalid markup and swallows its own click). */}
      <a
        href={row.url}
        aria-label={`Open folder ${nameOf(shown)}`}
        className="min-w-0 flex-1 truncate font-mono text-sm font-semibold text-fg no-underline transition-colors after:absolute after:inset-0 group-hover:text-accent"
      >
        {title ?? row.id}
      </a>
      {/* Only when there IS one. This count is what THIS shelf holds under the
          folder, and a profile's listing is root-scoped (its children are on
          the folder's own page) — so a zero here would be a wrong number
          rather than an empty folder. */}
      {count > 0 && <span className="shrink-0 font-mono text-[10px] tabular-nums text-faint">{count}</span>}
      {row.visibility && <VisibilityPill compact visibility={row.visibility} name={nameOf(shown)} />}
      <Actions
        row={shown}
        level={level}
        folders={folders}
        childCount={count}
        onDeleted={onDeleted}
        onRename={() => { setDraft(title ?? ''); setRenaming(true); }}
      />
    </li>
  );
}

/** Icon-only row action — the label lives in the tooltip, not beside the glyph. */
const ICON_ACTION =
  'inline-flex h-6 w-6 cursor-pointer items-center justify-center rounded-[4px] border-0 bg-transparent p-0 text-muted transition-colors hover:text-accent';

const CARD_ACTION_SURFACE =
  'flex h-[26px] items-center rounded-[4px] border border-edge bg-surface/90 px-0.5';

const VISIBILITY_ORDER = ['public', 'unlisted', 'private'] as const;

const nameOf = (row: ShelfRow) => row.title ?? row.id;

/**
 * Copy-link and edit in grid mode. List mode exposes the same capability set
 * through `ArtifactTable`.
 *
 * `relative z-10` is load-bearing: the card body is a STRETCHED LINK (an
 * anchor whose ::after covers the whole card), because a <button> nested
 * inside an <a> is invalid markup and swallows its own click. These sit above
 * that pseudo-element instead of inside the anchor.
 */
function Actions({ row, level, folders, childCount = 0, onDeleted, onRename }: { row: ShelfRow; level: ShelfActions; folders: PickerFolder[]; childCount?: number; onDeleted?: (id: string) => void; onRename?: () => void }) {
  const [copied, setCopied] = useState(false);
  const [moving, setMoving] = useState(false);
  const [parentId, setParentId] = useState(parentOfRow(row));
  const share = async () => {
    const url = row.url.startsWith('http') ? row.url : `${location.origin}${row.url}`;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      window.open(url, '_blank');
    }
  };
  if (level === 'none') return null;
  return (
    <span className="relative z-10 inline-flex shrink-0 items-center gap-0.5">
      <Tooltip content={copied ? 'copied!' : 'copy share link'}>
        <button
          type="button"
          aria-label={`Share ${nameOf(row)}`}
          onClick={share}
          className={`${ICON_ACTION} ${copied ? 'text-accent' : ''}`}
        >
          {copied ? <Check size={13} /> : <Link2 size={13} />}
        </button>
      </Tooltip>
      {level === 'full' && (
        <>
          {/* A FOLDER HAS NO DOCUMENT TO EDIT, so it is offered no editor —
              `#edit` on one would open a mode with nothing in it. Its rename
              lives in the menu below instead. */}
          {!onRename && (
            <Tooltip content="edit">
              <a aria-label={`Edit ${nameOf(row)}`} href={`/a/${row.id}#edit`} className={`${ICON_ACTION} no-underline`}>
                <Pencil size={13} />
              </a>
            </Tooltip>
          )}
          <RowMenu
            name={nameOf(row)}
            items={[
              ...(onRename ? [{
                label: `Rename ${nameOf(row)}`,
                text: 'rename',
                icon: <Pencil size={12} />,
                onSelect: onRename,
              }] : []),
              {
                label: `Move ${nameOf(row)}`,
                text: 'move to folder',
                icon: <FolderInput size={12} />,
                onSelect: () => setMoving(true),
              },
              {
                label: `Delete ${nameOf(row)}`,
                // The row SAYS how much goes with it, and the confirm says it
                // again in a sentence: deleting a folder is deleting everything
                // under it, in one statement, into a trash it can be taken back
                // out of at any time (lib/trash).
                text: childCount > 0 ? `delete (${childCount} inside)` : 'delete',
                icon: <Trash2 size={12} />,
                danger: true,
                onSelect: () => {
                  void confirmDeleteArtifact(row.id, nameOf(row), childCount).then((ok) => {
                    if (!ok) return;
                    // A caller that can drop the row does; anything else falls
                    // back to the reload the dense tier has always used.
                    if (onDeleted) onDeleted(row.id);
                    else window.location.reload();
                  });
                },
              },
            ]}
          />
        </>
      )}
      {moving && (
        <MoveMenu
          row={{ id: row.id, format: row.format, parent_id: parentId, ancestor_ids: row.ancestor_ids }}
          folders={folders}
          onMoved={setParentId}
          onClose={() => setMoving(false)}
        />
      )}
    </span>
  );
}

/**
 * THE PICTURE CARRIES THE CHROME — on every tier, at the same corner.
 *
 * The hero used to keep its classification and controls at the top of its
 * RIGHT column, which reads correctly only while that column is beside the
 * thumbnail. On a phone the grid stacks, the column falls underneath, and the
 * two controls that overlay the picture on every card below sat in a band
 * under the picture on the one above them — the tiers stopped looking like
 * one shelf. Hanging them on the picture is ONE rule with no breakpoint fork,
 * and the hero's right column is then free to be nothing but the document.
 */
function CardControls({ row, level, folders }: { row: ShelfRow; level: ShelfActions; folders: PickerFolder[] }) {
  if (!row.visibility && level === 'none') return null;
  return (
    <div
      aria-label={`${nameOf(row)} card controls`}
      className="absolute inset-x-2.5 top-2.5 z-10 flex items-start justify-between gap-2"
    >
      <VisibilityTag row={row} overlay />
      {level !== 'none' && (
        <div className={`${CARD_ACTION_SURFACE} ml-auto`}>
          <Actions row={row} level={level} folders={folders} />
        </div>
      )}
    </div>
  );
}

function Stamp({ row, mode, trailing = false }: { row: ShelfRow; mode: 'relative' | 'absolute'; trailing?: boolean }) {
  return (
    <Tooltip content={new Date(row.updated_at).toLocaleString()}>
      <time
        aria-label={`${nameOf(row)} updated`}
        dateTime={row.updated_at}
        suppressHydrationWarning
        className={`${trailing ? 'ml-auto' : ''} shrink-0 font-mono text-[11px] whitespace-nowrap text-muted`}
      >
        {mode === 'absolute' ? dateStamp(row.updated_at) : timeAgo(row.updated_at)}
      </time>
    </Tooltip>
  );
}

/** The document collection already guarantees `markup`; visibility is the only
 * classification that adds information here. */
function VisibilityTag({ row, overlay = false }: { row: ShelfRow; overlay?: boolean }) {
  return row.visibility ? (
    <VisibilityPill visibility={row.visibility} name={nameOf(row)} compact={overlay} overlay={overlay} />
  ) : null;
}

/** The artifact's own og card — one lazily-rendered image serves unfurls and the drive grid alike. */
function Thumb({ row, className }: { row: ShelfRow; className: string }) {
  return (
    <span className={`relative block w-full overflow-hidden bg-raised ${className}`}>
      <span className="absolute inset-0 flex items-center justify-center">
        <span className="h-4 w-4 animate-spin rounded-full border-2 border-edge-bright border-t-accent" />
      </span>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/a/${row.id}/export?format=jpg&mode=card&v=${row.version}&r=${CARD_RENDER_GENERATION}`}
        alt=""
        loading="lazy"
        className="relative h-full w-full object-cover"
      />
    </span>
  );
}

/**
 * Rows per page in list mode and in the separate assets table.
 */
export const SHELF_LIST_PER_PAGE = 10;

/** Multi-select quick filter. The pressed state is the whole contract. */
function FilterChip({ value, active, onToggle }: { value: string; active: boolean; onToggle: (v: string) => void }) {
  return (
    <Tooltip content={VISIBILITY_TIPS[value] ?? ''}>
      <button
        type="button"
        aria-label={`Filter ${value}`}
        aria-pressed={active}
        onClick={() => onToggle(value)}
        className={`inline-flex cursor-pointer items-center gap-1 rounded-full border px-2 py-0.5 font-mono text-[10px] leading-none whitespace-nowrap transition-colors ${
          active ? 'border-accent/50 bg-accent-soft text-accent' : 'border-edge text-faint'
        }`}
      >
        {value}
      </button>
    </Tooltip>
  );
}

export default function Shelf({ rows, actions = 'none', assets = true, dates = 'relative', parentId = null, canCreateFolders = false }: ShelfProps) {
  const [query, setQuery] = useState('');
  const [picks, setPicks] = useState<string[]>([]);
  const [made, setMade] = useState<ShelfRow[]>([]);
  /*
   * Folders TRASHED here, and everything that went with them. A folder is
   * deleted with its whole subtree in one statement (lib/trash), so dropping
   * only the tile would leave its documents on the shelf pointing at rows that
   * are 404 — and reloading to find that out would throw away the search, the
   * filters and the scroll, exactly as creating one would.
   */
  const [trashed, setTrashed] = useState<string[]>([]);
  const trash = (id: string) => setTrashed((t) => [...t, id]);
  const [view, setView] = useState<'grid' | 'list'>('grid');
  const q = query.trim().toLowerCase();
  const present = trashed.length
    ? rows.filter((r) => !trashed.includes(r.id) && !(r.ancestor_ids ?? []).some((a) => trashed.includes(a)))
    : rows;
  // `assets={false}` removes supporting files from the whole shelf contract,
  // including search counts and visibility chips. Their management surface is
  // `/assets`; leaving them in these derivations would make Home report hidden
  // matches that it can never render.
  const available = made.length > 0 ? [...made, ...present] : present;
  const all = assets ? available : available.filter((row) => row.format === 'markup' || row.format === 'folder');

  const togglePick = (v: string) => setPicks((p) => (p.includes(v) ? p.filter((x) => x !== v) : [...p, v]));

  // Chips are derived from the rows, so a shelf with nothing to split on shows
  // no dead controls.
  const chips = VISIBILITY_ORDER.filter((v) => all.some((r) => r.visibility === v));
  const showChips = chips.length >= 2;

  const shelf = useMemo(() => {
    const matched = all.filter(
      (r) =>
        (!q || `${r.title ?? ''} ${r.description ?? ''} ${r.format}`.toLowerCase().includes(q)) &&
        (picks.length === 0 || (r.visibility != null && picks.includes(r.visibility))),
    );
    return buildShelf(matched);
  }, [all, q, picks]);

  /** The account's folders, for every picker on this shelf — the tree, unfiltered. */
  const pickable: PickerFolder[] = useMemo(
    () => all.filter((r) => r.format === 'folder').map((r) => ({ id: r.id, title: r.title, ancestor_ids: r.ancestor_ids ?? [] })),
    [all],
  );
  /**
   * How many rows THIS shelf holds inside a folder — what the page was given
   * and no more. The dashboard lists the whole account, so its number is the
   * folder's; a profile lists the ROOT, so it has none to count and shows none.
   */
  const inside = (id: string): number => all.filter((r) => parentOfRow(r) === id).length;
  const dateGroups = useMemo(() => groupShelfByRecency(shelf.documents), [shelf.documents]);

  const filtering = Boolean(q) || picks.length > 0;
  const nothing = shelf.documents.length === 0 && shelf.assets.length === 0 && shelf.folders.length === 0;

  return (
    <section aria-label="Shelf" className="flex flex-col gap-4">
      {(all.length > 0 || canCreateFolders) && (
        <div className={`flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1.5 px-3 py-1.5 ${PANEL}`}>
            <Search size={13} className="shrink-0 text-faint" />
            <input
              aria-label="Search artifacts"
              placeholder="search artifacts"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="h-7 min-w-32 flex-1 border-0 bg-transparent font-mono text-xs text-fg placeholder:text-faint focus:outline-none"
            />
            {showChips && (
              <span className="flex shrink-0 items-center gap-1.5 border-l border-edge pl-2">
                {chips.map((v) => (
                  <FilterChip key={v} value={v} active={picks.includes(v)} onToggle={togglePick} />
                ))}
              </span>
            )}
            {filtering && (
              <span className="shrink-0 border-l border-edge pl-2 font-mono text-[10px] tabular-nums text-faint">
                {shelf.total + shelf.assets.length}/{all.length}
              </span>
            )}
          {canCreateFolders && (
            <span className="shrink-0 border-l border-edge pl-1.5">
              <NewFolder parentId={parentId} onMade={(row) => setMade((current) => [row, ...current])} />
            </span>
          )}
          <div role="group" aria-label="Shelf view" className="ml-auto flex shrink-0 items-center border-l border-edge pl-1.5">
            {([
              ['grid', 'Grid view', LayoutGrid],
              ['list', 'List view', ListIcon],
            ] as const).map(([value, label, Icon]) => (
              <button
                key={value}
                type="button"
                aria-label={label}
                aria-pressed={view === value}
                onClick={() => setView(value)}
                className={`inline-flex h-7 w-8 cursor-pointer items-center justify-center rounded-[4px] transition-all ${
                  view === value ? 'bg-accent-soft text-accent' : 'text-faint hover:bg-raised hover:text-fg'
                }`}
              >
                <Icon size={14} strokeWidth={1.7} />
              </button>
            ))}
          </div>
        </div>
      )}

      {/* FOLDERS — above the documents, and only for an account that has one.
        * A folder is where the deliverables are rather than a deliverable, so
        * it is neither a document tier nor an asset (lib/shelf's third
        * partition), and `total` still counts documents: making a folder never
        * changes what the shelf says you have. */}
      {shelf.folders.length > 0 && (
        /*
         * `relative z-20` is load-bearing, and was found by a real click. Every
         * row here carries `.reveal`, which is a CSS ANIMATION — so each row is
         * its own stacking context and a menu's `z-30` cannot escape it. The
         * strip sits ABOVE the document tiers in the DOM, so painting order put
         * a folder's open menu UNDERNEATH the hero card below it: visible,
         * and unclickable. Raising the section raises everything inside it.
         */
        <section aria-label="Folders" className="relative z-20">
          <div className="mb-2 flex items-baseline gap-2">
            <MicroLabel>folders</MicroLabel>
          </div>
          <ul className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {shelf.folders.map((row) => (
              <FolderTile key={row.id} row={row} count={inside(row.id)} level={actions} folders={pickable} onDeleted={trash} />
            ))}
          </ul>
        </section>
      )}

      {nothing && filtering && (
        <p aria-label="No matches" className="px-1 font-mono text-xs text-faint">
          nothing matches the active {q ? 'search' : 'filters'}
        </p>
      )}

      {view === 'grid' && shelf.documents.length > 0 && (
        <div aria-label="Artifact grid" className="flex flex-col gap-7">
          {dateGroups.map((group) => (
            <section key={group.key} aria-label={`${group.label} artifacts`}>
              <div className="mb-2.5 flex items-center gap-3 px-0.5">
                <h2 className="shrink-0 font-mono text-[10px] font-medium uppercase tracking-[0.13em] text-muted">
                  {group.label}
                </h2>
                <span aria-hidden="true" className="h-px flex-1 bg-edge" />
              </div>
              <ul className="grid grid-cols-1 gap-3.5 sm:grid-cols-2 lg:grid-cols-4">
                {group.rows.map((row) => {
                  const i = shelf.documents.indexOf(row);
                  return (
                    <li
                      key={row.id}
                      className={`reveal group relative flex flex-col overflow-hidden ${PANEL} transition-[border-color,transform] duration-150 hover:-translate-y-0.5 hover:border-edge-bright`}
                      style={{ animationDelay: `${Math.min(i * 35, 280)}ms` }}
                    >
                      <div className="relative">
                        <Thumb row={row} className="aspect-[40/21] border-b border-edge" />
                        <CardControls row={row} level={actions} folders={pickable} />
                      </div>
                      <div className="flex flex-1 flex-col gap-2 px-3 py-2.5">
                        <a
                          href={row.url}
                          aria-label={`Open ${nameOf(row)}`}
                          className="block truncate font-mono text-[13px] leading-snug font-semibold text-fg no-underline transition-colors after:absolute after:inset-0 group-hover:text-accent"
                        >
                          {row.title ?? 'Untitled'}
                        </a>
                        <div className="mt-auto flex min-w-0 items-center gap-2">
                          {row.views !== undefined && (
                            <ViewsMark name={nameOf(row)} views={row.views} sparkline={row.sparkline} className="flex-1" />
                          )}
                          <Stamp row={row} mode={dates} trailing={row.views !== undefined} />
                        </div>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </section>
          ))}
        </div>
      )}

      {view === 'list' && shelf.documents.length > 0 && (
        <ArtifactTable
          artifacts={shelf.documents}
          folders={pickable}
          manage={actions === 'full'}
          canEdit={actions === 'full'}
          canShare={actions !== 'none'}
          embedded
          dates={dates}
          perPage={SHELF_LIST_PER_PAGE}
        />
      )}

      {/* Not a tier: the material documents are built from. */}
      {assets && shelf.assets.length > 0 && (
        <section aria-label="Assets">
          <div className="mb-2 flex items-baseline gap-2">
            <MicroLabel>assets</MicroLabel>
            <span className="font-mono text-[10px] text-faint">the material documents are built from</span>
          </div>
          <ArtifactTable
            artifacts={shelf.assets}
            folders={pickable}
            manage={actions === 'full'}
            canEdit={false}
            canShare={false}
            showViews={false}
            filtersInline
            dates={dates}
            perPage={SHELF_LIST_PER_PAGE}
          />
        </section>
      )}
    </section>
  );
}
