// services/app/solid/pages/Welcome.tsx
/* @jsxImportSource solid-js */
import { createEffect, createSignal, onCleanup, Show, type JSX } from 'solid-js';
import { Navigate } from '@solidjs/router';
import { internalRedirectTarget } from '@/lib/safe-redirect';
import { pageDataChanged, profileChanged } from '@/web/page-data-events';
import { AvatarCircle } from '../components/AvatarCircle';
import { replaceDocument } from '../shared/document-navigation';
import { useSession } from '../web/session';

const HANDLE_REFUSALS: Record<string, string> = {
  username_taken: 'that handle is taken — pick another',
  invalid_username: '3–32 characters: lowercase letters, numbers, underscore (no hyphens)',
};

export function WelcomePage(): JSX.Element {
  const { session, reload } = useSession();
  const search = new URLSearchParams(window.location.search);
  const callbackUrl = search.get('callbackUrl');
  const [username, setUsername] = createSignal('');
  const [image, setImage] = createSignal<string | null>(null);
  const [status, setStatus] = createSignal<string | null>(null);
  const [busy, setBusy] = createSignal(false);
  const [leaving, setLeaving] = createSignal(false);
  createEffect(() => {
    let alive = true;
    void fetch('/api/my/profile', { credentials: 'same-origin' }).then(response => response.ok ? response.json() : null).then((profile: { username: string | null; image: string | null } | null) => {
      if (alive && profile) { setUsername(profile.username ?? ''); setImage(profile.image); }
    }).catch(() => {});
    onCleanup(() => { alive = false; });
  });
  const confirm = async () => {
    setBusy(true); setStatus(null);
    const response = await fetch('/api/my/profile', { method: 'PATCH', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: username(), welcome_pending: false }) }).catch(() => null);
    setBusy(false);
    if (!response) { setStatus('could not reach the server'); return; }
    const body = await response.json().catch(() => ({})) as { error?: string };
    if (!response.ok) { setStatus(HANDLE_REFUSALS[body.error ?? ''] ?? 'could not save that handle'); return; }
    setLeaving(true); pageDataChanged(); profileChanged(); reload();
    replaceDocument(internalRedirectTarget(callbackUrl, window.location.origin));
  };
  return <Show when={leaving() || !session() || !!session()?.user} fallback={<Navigate href={`/login?callbackUrl=${encodeURIComponent(`/welcome${search.toString() ? `?${search}` : ''}`)}`} />}>
    <Show when={leaving() || !session()?.onboarded} fallback={<Navigate href="/account" />}>
      <main class="mx-auto mt-16 max-w-xl px-6"><div class="mx-auto max-w-sm">
        <h1 class="text-base font-semibold"><span class="text-accent">&gt;</span> welcome</h1>
        <div class="mt-6"><AvatarCircle image={image()} initial={username() || 'a'} userId={session()?.user?.id ?? ''} onChange={setImage} /></div>
        <form class="mt-6" onSubmit={event => { event.preventDefault(); void confirm(); }}>
          <label for="welcome-username" class="font-mono text-[10px] uppercase tracking-[0.14em] text-faint">handle</label>
          <div class="mt-2 flex items-center gap-2"><span class="w-4 text-center font-mono text-sm text-muted">@</span><input id="welcome-username" aria-label="Username" autocomplete="off" spellcheck={false} value={username()} onInput={event => setUsername(event.currentTarget.value)} class="min-w-0 flex-1 rounded-[4px] border border-edge bg-surface px-3 py-2 text-sm" /></div>
          <Show when={status()}><p role="status" class="mt-2 ml-6 font-mono text-xs text-danger">{status()}</p></Show>
          <div class="mt-6"><button type="submit" disabled={busy() || !username().trim()} class="rounded-[4px] border border-fg bg-fg px-3 py-1.5 font-mono text-xs font-semibold text-bg">Confirm</button></div>
        </form>
      </div></main>
    </Show>
  </Show>;
}

// services/app/web/pages/Welcome.tsx
/**
 * THE WELCOME PAGE — seen once, by a brand-new account, from wherever the app
 * shell intercepted them (web/OnboardingGate).
 *
 * Deliberately three things: the picture, the handle, Confirm. Everything else
 * a person might want to set has a home on the account page and can wait; what
 * cannot wait is that they arrive somewhere with an auto-assigned handle and a
 * blank circle and never learn either is theirs to change.
 *
 * Confirm saves BOTH in one PATCH — the handle and `welcome_pending: false` —
 * so a refused handle leaves them here with the reason and the page intact,
 * rather than half-confirmed with a name they did not pick. The picture is
 * already saved by then: it goes to its own door the moment it is chosen, so
 * Confirm never has bytes to wait on.
 */
import { useEffect, useState } from 'react';
import { Navigate } from 'react-router';
import AvatarCircle from '@/components/AvatarCircle';
import { HANDLE_REFUSALS } from '@/components/UsernameCard';
import { Button, Input, MicroLabel } from '@/components/ui';
import { useRouter, useSearchParams } from '@/lib/navigation';
import { internalRedirectTarget } from '@/lib/safe-redirect';
import { pageDataChanged } from '@/web/page-data-events';
import { useSession } from '../session';

interface Profile { username: string | null; image: string | null }

export function WelcomePage() {
  const { session, reload } = useSession();
  const search = useSearchParams();
  const router = useRouter();
  const callbackUrl = search.get('callbackUrl');

  const [username, setUsername] = useState('');
  const [image, setImage] = useState<string | null>(null);
  const [status, setStatus] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  // Once Confirm has been answered, this page is leaving. The "already
  // onboarded" guard below must not fire in the gap and steal the callback.
  const [leaving, setLeaving] = useState(false);

  useEffect(() => {
    let alive = true;
    void fetch('/api/my/profile', { credentials: 'same-origin' })
      .then((r) => (r.ok ? r.json() : null))
      .then((profile: Profile | null) => {
        if (!alive || !profile) return;
        setUsername(profile.username ?? '');
        setImage(profile.image);
      })
      .catch(() => {});
    return () => { alive = false; };
  }, []);

  if (!leaving && session && !session.user) {
    // Back HERE afterwards, callback and all: the destination the shell was
    // holding for this person must survive the detour through the login page.
    const here = `/welcome${search.toString() ? `?${search.toString()}` : ''}`;
    return <Navigate to={`/login?callbackUrl=${encodeURIComponent(here)}`} replace />;
  }
  if (!leaving && session?.user && session.onboarded) return <Navigate to="/account" replace />;

  const confirm = async () => {
    setBusy(true);
    setStatus(null);
    const res = await fetch('/api/my/profile', {
      method: 'PATCH',
      credentials: 'same-origin',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, welcome_pending: false }),
    }).catch(() => null);
    setBusy(false);
    if (!res) return setStatus('could not reach the server');
    const body = (await res.json().catch(() => ({}))) as { username?: string; error?: string };
    if (!res.ok) return setStatus(HANDLE_REFUSALS[body.error ?? ''] ?? 'could not save that handle');

    setLeaving(true);
    pageDataChanged();
    // The session's `onboarded` bit is stale the moment this succeeds, and it
    // is what the gate reads — re-read it before anything navigates.
    reload();
    router.replace(internalRedirectTarget(callbackUrl, window.location.origin));
  };

  return (
    <main className="mx-auto mt-16 max-w-xl px-6">
      <div className="mx-auto max-w-sm">
        <h1 className="text-base font-semibold"><span className="text-accent">&gt;</span> welcome</h1>
        <p className="mt-2 font-mono text-xs leading-relaxed text-muted">
          Two things people will see. Both are yours to change later, on the account page.
        </p>

        <div className="mt-6">
          <AvatarCircle
            image={image}
            initial={username || 'a'}
            userId={session?.user?.id ?? ''}
            onChange={setImage}
          />
        </div>

        <form
          className="mt-6"
          onSubmit={(e) => { e.preventDefault(); void confirm(); }}
        >
          <MicroLabel>handle</MicroLabel>
          <div className="mt-2 flex items-center gap-2">
            <span className="w-4 text-center font-mono text-sm text-muted">@</span>
            <span className="min-w-0 flex-1">
              <Input
                aria-label="Username"
                autoComplete="off"
                spellCheck={false}
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </span>
          </div>
          {status && <p role="status" className="mt-2 ml-6 font-mono text-xs text-danger">{status}</p>}
          <div className="mt-6">
            <Button type="submit" disabled={busy || !username.trim()}>Confirm</Button>
          </div>
        </form>
      </div>
    </main>
  );
}
