// services/app/components/SelectMenu.tsx
'use client';

/**
 * The house dropdown — terminal-graphite chrome for what a native <select>
 * draws with OS widgets. A trigger button over a Radix popover, the same
 * anatomy AnchoredPanel gives the theme and mode chips.
 *
 * Lives beside ui.tsx rather than in it: the kit file is imported by server
 * components for its class constants, and this one needs state.
 *
 * A listbox, not a menu: it always models "one value out of a closed set", so
 * `aria-selected` and the check mark always mean something. Callers that need
 * "no value" pass it as an explicit option (`{ value: '', label: '— none —' }`)
 * — the empty string is a choice a user can make, not an absence.
 *
 * THE PANEL IS PORTALLED, for the same reason Tooltip's is: an absolutely
 * placed panel is clipped by any `overflow-hidden`/`overflow-y-auto` ancestor,
 * and z-index does not escape a clip. This dropdown's homes are precisely the
 * places that have one — the centered share dialog (which rounds its corners
 * and scrolls its own body) and the chart inspector rail — where a clipped
 * list would put its last options out of reach. Radix Popover also flips it
 * above the trigger when the space below runs out.
 */
import { Check, ChevronDown } from 'lucide-react';
import * as PopoverPrimitive from '@radix-ui/react-popover';
import { useState } from 'react';
import { useTrustedPortalContainer } from './TrustedUi';

interface SelectMenuOption {
  value: string;
  label: string;
  /** Dim annotation after the label — a column's type, a dataset's row count. */
  hint?: string;
}

export function SelectMenu({
  value,
  options,
  onChange,
  ariaLabel,
  disabled = false,
  placeholder = '— none —',
}: {
  value: string;
  options: SelectMenuOption[];
  onChange: (value: string) => void;
  ariaLabel: string;
  disabled?: boolean;
  /** Trigger text when `value` matches no option — the caller says what absence means here. */
  placeholder?: string;
}) {
  const [open, setOpen] = useState(false);
  const portalContainer = useTrustedPortalContainer();
  /** Keyboard cursor while open; seeded on the current value so arrows start from it. */
  const [active, setActive] = useState(0);

  const current = options.find((o) => o.value === value);
  const pick = (v: string) => {
    setOpen(false);
    onChange(v);
  };
  const openList = () => {
    setActive(Math.max(0, options.findIndex((o) => o.value === value)));
    setOpen(true);
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (!open) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();
        openList();
      }
      return;
    }
    if (e.key === 'Escape') { e.preventDefault(); setOpen(false); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); setActive((i) => Math.min(i + 1, options.length - 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setActive((i) => Math.max(i - 1, 0)); }
    else if (e.key === 'Enter') { e.preventDefault(); if (options[active]) pick(options[active].value); }
    else if (e.key === 'Tab') setOpen(false);
  };

  return (
    <PopoverPrimitive.Root open={open} onOpenChange={(next) => (next ? openList() : setOpen(false))}>
      <div className="relative" onKeyDown={onKeyDown}>
        <PopoverPrimitive.Trigger asChild>
          <button
            type="button"
            aria-label={ariaLabel}
            aria-haspopup="listbox"
            disabled={disabled}
            className="flex w-full cursor-pointer items-center justify-between gap-2 rounded-[4px] border border-edge bg-surface px-2 py-1 text-left font-mono text-xs text-fg hover:bg-raised disabled:cursor-default disabled:opacity-50"
          >
            <span className="truncate">
              {current ? current.label : placeholder}
              {current?.hint && <span className="text-faint"> · {current.hint}</span>}
            </span>
            <ChevronDown size={12} className="shrink-0 opacity-60" />
          </button>
        </PopoverPrimitive.Trigger>
      </div>

      <PopoverPrimitive.Portal container={portalContainer}>
        <PopoverPrimitive.Content
          role="listbox"
          aria-label={`${ariaLabel} options`}
          align="start"
          sideOffset={4}
          collisionPadding={8}
          onKeyDown={onKeyDown}
          // The trigger keeps the keyboard; a listbox whose options are buttons
          // would otherwise take focus on open and lose the arrow handler above.
          onOpenAutoFocus={(e) => e.preventDefault()}
          // Above EVERY app layer, not merely above its neighbours: portalled to
          // <body>, it inherits no stacking context from the thing that opened
          // it, so it has to outrank the highest surface that can hold a trigger
          // — the centered dialogs at z-[100], which is where it lives.
          className="z-[200] max-h-64 overflow-y-auto rounded-[4px] border border-edge bg-surface py-1 shadow-lg"
          style={{ width: 'var(--radix-popover-trigger-width)' }}
        >
          {options.map((o, i) => (
            <button
              key={o.value}
              type="button"
              role="option"
              aria-selected={o.value === value}
              onClick={() => pick(o.value)}
              onMouseEnter={() => setActive(i)}
              className={`flex w-full cursor-pointer items-center justify-between gap-2 px-2 py-1 text-left font-mono text-xs text-fg ${
                i === active ? 'bg-raised' : ''
              }`}
            >
              <span className="truncate">
                {o.label}
                {o.hint && <span className="text-faint"> · {o.hint}</span>}
              </span>
              {o.value === value && <Check size={11} className="shrink-0 text-accent" />}
            </button>
          ))}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
}

// services/app/solid/ui/SelectMenu.tsx
/* @jsxImportSource solid-js */
/**
 * The house dropdown, terminal-graphite chrome for what a native
 * <select> draws with OS widgets. Same contract — a trigger button over an anchored, portalled panel
 * (solid/ui/Popover) — and the same anatomy: a listbox, not a menu, so `aria-selected` and the
 * check mark always mean something, and a caller that needs "no value" passes it as an explicit option.
 */
import { createSignal, For, Show, type JSX } from 'solid-js';
import Check from 'lucide-solid/icons/check';
import ChevronDown from 'lucide-solid/icons/chevron-down';
import { Popover } from './Popover';

interface SelectMenuOption {
  value: string;
  label: string;
  /** Dim annotation after the label — a column's type, a dataset's row count. */
  hint?: string;
}

export function SelectMenu(props: {
  value: string;
  options: SelectMenuOption[];
  onChange: (value: string) => void;
  ariaLabel: string;
  disabled?: boolean;
  /** Trigger text when `value` matches no option — the caller says what absence means here. */
  placeholder?: string;
}): JSX.Element {
  const [open, setOpen] = createSignal(false);
  /** Keyboard cursor while open; seeded on the current value so arrows start from it. */
  const [active, setActive] = createSignal(0);
  const current = () => props.options.find((o) => o.value === props.value);
  const placeholder = () => props.placeholder ?? '— none —';

  const pick = (v: string) => { setOpen(false); props.onChange(v); };
  const openList = () => {
    setActive(Math.max(0, props.options.findIndex((o) => o.value === props.value)));
    setOpen(true);
  };

  const onKeyDown = (event: KeyboardEvent) => {
    if (!open()) {
      if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); openList(); }
      return;
    }
    if (event.key === 'Escape') { event.preventDefault(); setOpen(false); }
    else if (event.key === 'ArrowDown') { event.preventDefault(); setActive((i) => Math.min(i + 1, props.options.length - 1)); }
    else if (event.key === 'ArrowUp') { event.preventDefault(); setActive((i) => Math.max(i - 1, 0)); }
    else if (event.key === 'Enter') { event.preventDefault(); const o = props.options[active()]; if (o) pick(o.value); }
    else if (event.key === 'Tab') setOpen(false);
  };

  return (
    <div class="relative" onKeyDown={onKeyDown}>
      <Popover
        open={open()}
        onOpenChange={(next) => (next ? openList() : setOpen(false))}
        label={`${props.ariaLabel} options`}
        role="listbox"
        class="z-[200] max-h-64 overflow-y-auto rounded-[4px] py-1"
        onPanelKeyDown={onKeyDown}
        trigger={(attrs) => (
          <button
            ref={attrs.ref}
            type="button"
            aria-label={props.ariaLabel}
            aria-haspopup={attrs['aria-haspopup']}
            disabled={props.disabled}
            onClick={() => (open() ? setOpen(false) : openList())}
            class="flex w-full cursor-pointer items-center justify-between gap-2 rounded-[4px] border border-edge bg-surface px-2 py-1 text-left font-mono text-xs text-fg hover:bg-raised disabled:cursor-default disabled:opacity-50"
          >
            <span class="truncate">
              {current() ? current()!.label : placeholder()}
              <Show when={current()?.hint}>{(hint) => <span class="text-faint"> · {hint()}</span>}</Show>
            </span>
            <ChevronDown size={12} class="shrink-0 opacity-60" />
          </button>
        )}
      >
        <div style={{ width: 'var(--radix-popper-anchor-width)' }}>
          <For each={props.options}>
            {(o, i) => (
              <button
                type="button"
                role="option"
                aria-selected={o.value === props.value}
                onClick={() => pick(o.value)}
                onMouseEnter={() => setActive(i())}
                class={`flex w-full cursor-pointer items-center justify-between gap-2 px-2 py-1 text-left font-mono text-xs text-fg ${i() === active() ? 'bg-raised' : ''}`}
              >
                <span class="truncate">
                  {o.label}
                  <Show when={o.hint}>{(hint) => <span class="text-faint"> · {hint()}</span>}</Show>
                </span>
                <Show when={o.value === props.value}><Check size={11} class="shrink-0 text-accent" /></Show>
              </button>
            )}
          </For>
        </div>
      </Popover>
    </div>
  );
}
