// services/app/solid/App.tsx
/* @jsxImportSource solid-js */
/** Solid owns the entire Trash route. Other destinations load their React document. */
import { ErrorBoundary, lazy, Suspense, type JSX } from 'solid-js';
import { Route, Router, type RouteSectionProps } from '@solidjs/router';
import { SessionProvider } from './web/session';
import { PageChrome } from './components/PageChrome';
import { OnboardingGate } from './components/OnboardingGate';
import { InboxProvider } from './web/notifications';

const TrashPage = lazy(() => import('./pages/Trash').then((m) => ({ default: m.TrashPage })));
const NotFoundPage = lazy(() => import('./pages/NotFound').then((m) => ({ default: m.NotFoundPage })));
const LoginPage = lazy(() => import('./pages/Login').then((m) => ({ default: m.LoginPage })));
const StartPage = lazy(() => import('./pages/Start').then((m) => ({ default: m.StartPage })));
const WelcomePage = lazy(() => import('./pages/Welcome').then((m) => ({ default: m.WelcomePage })));
const NotificationsPage = lazy(() => import('./pages/Notifications').then((m) => ({ default: m.NotificationsPage })));
const AccountPage = lazy(() => import('./pages/Account').then((m) => ({ default: m.AccountPage })));
const DocsPage = lazy(() => import('./pages/Docs').then((m) => ({ default: m.DocsPage })));
const ProfilePage = lazy(() => import('./pages/Profile').then((m) => ({ default: m.ProfilePage })));
const HomePage = lazy(() => import('./pages/Home').then((m) => ({ default: m.HomePage })));
const FolderRoute = lazy(() => import('./pages/Folder').then((m) => ({ default: m.FolderRoute })));
const AssetsPage = lazy(() => import('./pages/Assets').then((m) => ({ default: m.AssetsPage })));
const DatasetEditorPage = lazy(() => import('./pages/DatasetEditor').then((m) => ({ default: m.DatasetEditorPage })));
const FileUploadPage = lazy(() => import('./pages/FileUpload').then((m) => ({ default: m.FileUploadPage })));

function PendingPage(): JSX.Element {
  return <main aria-label="Loading page" role="status" aria-busy="true" class="mx-auto max-w-5xl px-4 py-10"><span class="sr-only">Loading page…</span><div aria-hidden="true" class="h-7 w-48 rounded bg-raised" /></main>;
}

function Root(props: RouteSectionProps): JSX.Element {
  return (
    <SessionProvider>
    <InboxProvider>
    <OnboardingGate>
      <PageChrome />
      <ErrorBoundary fallback={(_, reset) => <main class="mx-auto max-w-5xl px-4 py-10" role="alert">Could not load this page. <button aria-label="Retry loading page" onClick={reset}>Retry</button></main>}>
        <Suspense fallback={<PendingPage />}>{props.children}</Suspense>
      </ErrorBoundary>
    </OnboardingGate>
    </InboxProvider>
    </SessionProvider>
  );
}

export function App(): JSX.Element {
  return (
    <Router root={Root}>
      <Route path="/" component={HomePage} />
      <Route path="/a/:id" component={FolderRoute} />
      <Route path="/trash" component={TrashPage} />
      <Route path="/assets" component={AssetsPage} />
      <Route path="/datasets/new" component={DatasetEditorPage} />
      <Route path="/files/new" component={FileUploadPage} />
      <Route path="/a/:id/edit" component={DatasetEditorPage} />
      <Route path="/login" component={LoginPage} />
      <Route path="/start" component={StartPage} />
      <Route path="/welcome" component={WelcomePage} />
      <Route path="/notifications" component={NotificationsPage} />
      <Route path="/account" component={AccountPage} />
      <Route path="/docs-human" component={DocsPage} />
      <Route path="/:user" component={ProfilePage} />
      <Route path="*404" component={NotFoundPage} />
    </Router>
  );
}

// services/app/web/App.tsx
import {NotificationProvider} from '@/components/NotificationCenter';
import { Navigate, Route, Routes } from 'react-router';
import { SessionProvider } from './session';
import { Shell } from './Shell';
import { routePages } from './route-pages';
import { NavigationPreloads } from './navigation-preloads';
import { OnboardingGate } from './OnboardingGate';

const { NotificationsPage, ChatPage, AccountPage, AssetsPage, DatasetEditorPage, FileUploadPage, DocsPage, HomePage, LoginPage, NotFoundPage, ProfilePage, StartPage, TrashPage, WelcomePage } = routePages;

export function App() {
  return (
    <SessionProvider>
    <NotificationProvider>
      <NavigationPreloads>
      {/* Around the WHOLE table: a new account is intercepted wherever it
        * landed, not only on the routes somebody remembered to guard. */}
      <OnboardingGate>
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/start" element={<StartPage />} />
        <Route element={<Shell />}>
          <Route path="/login" element={<LoginPage />} />
          <Route path="/chat" element={<ChatPage />} />
          <Route path="/notifications" element={<NotificationsPage />} />
          <Route path="/account" element={<AccountPage />} />
          <Route path="/welcome" element={<WelcomePage />} />
          <Route path="/assets" element={<AssetsPage />} />
          <Route path="/datasets/new" element={<DatasetEditorPage />} />
          <Route path="/files/new" element={<FileUploadPage />} />
          <Route path="/tokens" element={<Navigate to="/account" replace />} />
          <Route path="/trash" element={<TrashPage />} />
          {/* `/docs` and below are the agent surface, served by the server's
            * docs route — the SPA must not claim them. */}
          <Route path="/docs-human" element={<DocsPage />} />
          <Route path="*" element={<NotFoundPage />} />
        </Route>
        <Route path="/a/:id/edit" element={<ProfilePage />} />
        <Route path="/a/:id" element={<ProfilePage />} />
        <Route path="/:user/*" element={<ProfilePage />} />
      </Routes>
      </OnboardingGate>
      </NavigationPreloads>
    </NotificationProvider>
    </SessionProvider>
  );
}
