// services/app/components/NotificationSettings.tsx
import {useEffect,useState} from 'react';
import {Button} from './ui';
import {useNotificationInbox} from './use-notification-inbox';
type EmailPreferences={invitations:boolean;comments:boolean;activity:boolean};

export function NotificationSettings(){
 const {state,error,load}=useNotificationInbox();
 const [email,setEmail]=useState<EmailPreferences|null>(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{void fetch('/api/my/people/email').then(r=>r.ok?r.json():null).then(data=>{if(data?.enabled)setEmail(data.preferences);}).catch(()=>{});},[]);
 const saveEmail=async(preferences:EmailPreferences)=>{
  setSaving(true);setNotice('');
  try{const r=await fetch('/api/my/people/email',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(preferences)});if(!r.ok)throw Error();setEmail((await r.json()).preferences);setNotice('Saved');}catch{setNotice('Could not save email preferences. Try again.');}finally{setSaving(false);}
 };
 return <section id="notifications" aria-label="Notification settings" className="rounded-lg border border-edge bg-surface p-5 font-sans">
  <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-base font-semibold">Notification settings</h2><a href="/notifications" className="text-sm text-muted hover:text-fg">All notifications</a></div>
  <p className="mt-1 text-sm text-muted">Choose how invitations and updates reach you.</p>
  {error&&<p role="alert" className="mt-3 text-sm text-danger">{error} <button onClick={()=>void load()}>Retry</button></p>}
  {state&&<div className="mt-5 border-t border-edge pt-4"><h3 className="mb-3 text-sm font-medium">Invitations</h3><label className="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" className="mt-1 accent-accent" checked={state.autoAccept} onChange={e=>void load({autoAccept:e.target.checked})}/><span>Automatically accept invitations from people I follow.<span className="mt-1 block text-xs leading-5 text-muted">You can review invitations from everyone else before joining.</span></span></label></div>}
  {email&&<fieldset disabled={saving} className="mt-5 space-y-3 border-t border-edge pt-4"><legend className="text-sm font-medium">Email notifications</legend>{(['invitations','comments','activity'] as const).map(key=><label key={key} className="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" className="mt-1 accent-accent" checked={email[key]} onChange={e=>void saveEmail({...email,[key]:e.target.checked})}/><span>{key==='invitations'?'Invitations':key==='comments'?'Unread comment updates':'Likes and follows'}<span className="mt-1 block text-xs text-muted">{key==='invitations'?'As soon as you’re invited.':key==='comments'?'Only if you haven’t read the update after a few minutes.':'One daily summary.'}</span></span></label>)}</fieldset>}
  {notice&&<p role="status" className="mt-3 text-xs text-muted">{notice}</p>}
  {!!state?.blocks.length&&<div className="mt-5 border-t border-edge pt-4"><h3 className="mb-2 text-sm font-medium">Blocked people</h3>{state.blocks.map(b=><div className="flex items-center justify-between py-2" key={b.user_id}><span className="text-sm">@{b.username??b.user_id}</span><Button variant="ghost" onClick={()=>void load({unblock:b.user_id})}>Unblock</Button></div>)}</div>}
 </section>;
}

// services/app/solid/components/NotificationSettings.tsx
/* @jsxImportSource solid-js */
import { createSignal, For, onMount, Show, type JSX } from 'solid-js';
import { useInbox } from '../web/notifications';

type EmailPreferences = { invitations: boolean; comments: boolean; activity: boolean };
const KEYS = ['invitations', 'comments', 'activity'] as const;
const LABELS = { invitations: 'Invitations', comments: 'Unread comment updates', activity: 'Likes and follows' };

export function NotificationSettings(): JSX.Element {
  const inbox = useInbox();
  const [email, setEmail] = createSignal<EmailPreferences | null>(null);
  const [saving, setSaving] = createSignal(false);
  const [notice, setNotice] = createSignal('');
  onMount(() => { void fetch('/api/my/people/email').then(response => response.ok ? response.json() : null).then((data: { enabled?: boolean; preferences?: EmailPreferences } | null) => { if (data?.enabled && data.preferences) setEmail(data.preferences); }).catch(() => {}); });
  const saveEmail = async (preferences: EmailPreferences) => {
    setSaving(true); setNotice('');
    try { const response = await fetch('/api/my/people/email', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(preferences) }); if (!response.ok) throw new Error(); const data = await response.json() as { preferences: EmailPreferences }; setEmail(data.preferences); setNotice('Saved'); }
    catch { setNotice('Could not save email preferences. Try again.'); }
    finally { setSaving(false); }
  };
  return <section id="notifications" aria-label="Notification settings" class="rounded-lg border border-edge bg-surface p-5 font-sans"><div class="flex flex-wrap items-center justify-between gap-2"><h2 class="text-base font-semibold">Notification settings</h2><a href="/notifications" class="text-sm text-muted hover:text-fg">All notifications</a></div><p class="mt-1 text-sm text-muted">Choose how invitations and updates reach you.</p>
    <Show when={inbox.error()}><p role="alert" class="mt-3 text-sm text-danger">{inbox.error()} <button onClick={() => void inbox.load()}>Retry</button></p></Show>
    <Show when={inbox.state()}><div class="mt-5 border-t border-edge pt-4"><h3 class="mb-3 text-sm font-medium">Invitations</h3><label class="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" class="mt-1 accent-accent" checked={inbox.state()?.autoAccept} onChange={event => void inbox.load({ autoAccept: event.currentTarget.checked })} /><span>Automatically accept invitations from people I follow.<span class="mt-1 block text-xs leading-5 text-muted">You can review invitations from everyone else before joining.</span></span></label></div></Show>
    <Show when={email()}><fieldset disabled={saving()} class="mt-5 space-y-3 border-t border-edge pt-4"><legend class="text-sm font-medium">Email notifications</legend><For each={KEYS}>{key => <label class="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" class="mt-1 accent-accent" checked={email()?.[key]} onChange={event => void saveEmail({ ...email()!, [key]: event.currentTarget.checked })} /><span>{LABELS[key]}</span></label>}</For></fieldset></Show>
    <Show when={notice()}><p role="status" class="mt-3 text-xs text-muted">{notice()}</p></Show>
    <Show when={inbox.state()?.blocks.length}><div class="mt-5 border-t border-edge pt-4"><h3 class="mb-2 text-sm font-medium">Blocked people</h3><For each={inbox.state()?.blocks}>{block => <div class="flex items-center justify-between py-2"><span class="text-sm">@{block.username ?? block.user_id}</span><button type="button" onClick={() => void inbox.load({ unblock: block.user_id })}>Unblock</button></div>}</For></div></Show>
  </section>;
}
