// services/app/components/PageChrome.tsx
'use client';

/**
 * Shared page chrome. The app topbar holds Home, repository stars and page
 * controls; document chrome uses the same panels through its existing bridge.
 */
import {
  BookOpen, CircleUser, ChevronRight, FileText, LogIn, LogOut, Menu, Moon,
  SlidersVertical, Sun, User, X,
} from 'lucide-react';
import { useEffect, useState } from 'react';
import { useIsPhoneViewport } from '@/components/MobileSheet';
import GitHubStar from '@/components/GitHubStar';
import { GitHubIcon } from '@/components/brand-icons';
import { REPO_URL } from '@/lib/repo';
import { Tooltip } from '@/components/Tooltip';
import { forgetTokens } from '@/lib/browser-session';
import { CHROME_IDENTITY } from '@/lib/chrome-identity';
import { crumbsFor } from '@/lib/breadcrumb';
import { loginHref } from '@/lib/login-href';
import { usePathname } from '@/lib/navigation';
import Avatar from '@/components/Avatar';
import {NotificationBell,NotificationMenu} from './NotificationCenter';
import {PagePanel} from './PagePanel';
import {announcePanel,requestPageChrome,subscribePageChrome,useExclusiveLayer,useOpenOnRequest,type PagePanelName} from './page-chrome-state';
export {requestPageChrome,subscribePageChrome} from './page-chrome-state';
import { useSession } from '@/web/session';

export type AppearanceMode = 'light' | 'dark';

const EDGE = 12;
const ITEM =
  'flex w-full items-center gap-3 rounded-[5px] border-0 bg-transparent px-3 py-3 text-left font-mono text-sm no-underline transition-colors sm:gap-2.5 sm:px-2.5 sm:py-2 sm:text-xs';
const FLOATING_BUTTON =
  'z-[60] flex h-9 w-9 cursor-pointer items-center justify-center rounded-full border border-edge bg-surface/90 text-muted shadow-sm backdrop-blur-md transition-[color,background-color,transform] hover:bg-raised hover:text-fg active:scale-95';


function triggerPosition(side: 'left' | 'right', fixed: boolean, open: boolean) {
  const position = fixed || open ? 'fixed' : 'absolute';
  return `${position} top-3 ${side === 'left' ? 'left-3' : 'right-3'}`;
}

export function PageMenu({
  authed,
  anon = false,
  fixed = false,
  triggerless = false,
  panelTop,
}: {
  authed: boolean;
  anon?: boolean;
  title?: string | null;
  fixed?: boolean;
  /** Where the dropdown starts, when more than the bar sits above it (edit mode). */
  panelTop?: number;
  /** No button of its own: the framed document's chrome opens it (requestPageChrome). */
  triggerless?: boolean;
}) {
  const pathname = usePathname() ?? '';
  const [open, setOpen] = useState(false);
  const phone = useIsPhoneViewport();
  const toggle = useExclusiveLayer(open, setOpen);
  useOpenOnRequest('menu', open, setOpen);
  useEffect(() => { announcePanel('menu', open); }, [open]);

  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  const link = (href: string, label: string, icon: React.ReactNode, active: boolean) => (
    <a
      href={href}
      aria-label={label}
      className={`${ITEM} cursor-pointer ${active ? 'bg-accent-soft text-accent' : 'text-muted hover:bg-raised hover:text-fg'}`}
      onClick={() => setOpen(false)}
    >
      {icon}
      {label}
    </a>
  );

  const layer = open && (
    <>
      <button
        type="button"
        aria-label="Close the menu"
        onClick={() => setOpen(false)}
        className={`fixed inset-0 z-40 cursor-default border-0 p-0 ${triggerless && !phone ? 'bg-transparent' : 'bg-black/25'}`}
      />
      <nav
        aria-label="Menu"
        /* Opened from the framed chrome it is a DROPDOWN under the bar (a bottom
           sheet on a phone), the twin of the controls panel; on its own it stays
           the app's left drawer. */
        className={triggerless
          ? (phone
            ? 'fixed inset-x-0 bottom-0 z-50 flex animate-[rise_.14s_ease-out] flex-col rounded-t-[10px] border-t border-edge bg-surface p-3 pb-[max(20px,env(safe-area-inset-bottom))] shadow-xl'
            : 'fixed right-3 top-14 z-50 flex w-72 animate-[rise_.14s_ease-out] flex-col rounded-[7px] border border-edge bg-surface p-2 shadow-xl')
          : 'fixed inset-y-0 left-0 z-50 flex w-full animate-[drawer-in_.15s_ease-out] flex-col border-r border-edge bg-surface p-2 pt-16 shadow-xl sm:w-72'}
        style={triggerless && !phone && panelTop !== undefined ? { top: panelTop } : undefined}
      >
        <button
          type="button"
          aria-label="Dismiss menu"
          onClick={() => setOpen(false)}
          className="absolute right-3 top-3 flex h-9 w-9 cursor-pointer items-center justify-center rounded-full border border-edge bg-surface text-muted hover:bg-raised hover:text-fg sm:hidden"
          style={{ top: `max(${EDGE}px, env(safe-area-inset-top))` }}
        >
          <X size={17} strokeWidth={1.5} />
        </button>
        <a
          href="/"
          aria-label="Hosted at artifactbin"
          className="mb-3 flex items-center gap-2.5 px-2 font-mono text-sm font-semibold text-fg no-underline transition-colors hover:text-accent"
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/logo-128.png" alt="" className="h-7 w-7" />
          artifactbin
        </a>

        {link('/', 'Artifacts', <FileText size={15} strokeWidth={1.5} />, pathname === '/')}
        {link('/chat', 'Remote sessions', <User size={15} strokeWidth={1.5} />, pathname === '/chat')}
        {link('/notifications', 'Notifications', <User size={15} strokeWidth={1.5} />, false)}
        {link('/account', 'Account', <User size={15} strokeWidth={1.5} />, pathname === '/account')}
        {link('/docs-human', 'Human Docs', <BookOpen size={15} strokeWidth={1.5} />, pathname === '/docs-human')}

        <a
          href={REPO_URL}
          target="_blank"
          rel="noopener noreferrer"
          className={`${ITEM} cursor-pointer text-muted hover:bg-raised hover:text-fg`}
          onClick={() => setOpen(false)}
        >
          <GitHubIcon size={15} />
          Support artifactbin
        </a>

        <div className="mt-auto" />
        <div className="my-1 h-px bg-edge" />
        {authed ? (
          <button
            type="button"
            aria-label="Sign out"
            onClick={() => void fetch('/api/auth/sign-out', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })
              .catch(() => null)
              .then(() => { window.location.href = '/'; })}
            className={`${ITEM} cursor-pointer text-muted hover:bg-raised hover:text-fg`}
          >
            <LogOut size={15} strokeWidth={1.5} />
            Sign out
          </button>
        ) : anon ? (
          <button
            type="button"
            aria-label="Disconnect this browser"
            onClick={() => void forgetTokens().then(() => { window.location.href = '/'; })}
            className={`${ITEM} cursor-pointer text-muted hover:bg-raised hover:text-fg`}
          >
            <LogOut size={15} strokeWidth={1.5} />
            Disconnect this browser
          </button>
        ) : (
          // Only rendered while the menu is open, so the address is the one on screen now.
          link(loginHref(window.location), 'Login', <LogIn size={15} strokeWidth={1.5} />, pathname === '/login')
        )}
      </nav>
    </>
  );

  return (
    <>
      {!triggerless && <Tooltip content={open ? 'close menu' : 'menu'} positioning={{ placement: 'bottom-start' }}>
        <button
          type="button"
          aria-label={open ? 'Close menu' : 'Open menu'}
          aria-expanded={open}
          onClick={toggle}
          data-chrome-placement="page"
          className={`${triggerPosition('left', fixed, open)} ${FLOATING_BUTTON}`}
          style={{ top: `max(${EDGE}px, env(safe-area-inset-top))`, left: `max(${EDGE}px, env(safe-area-inset-left))` }}
        >
          {open ? <X size={17} strokeWidth={1.5} /> : <Menu size={17} strokeWidth={1.5} />}
        </button>
      </Tooltip>}
      {layer}
    </>
  );
}

function AppearancePicker({ mode, onPick }: { mode: AppearanceMode; onPick: (mode: AppearanceMode) => void }) {
  return (
    <section aria-label="Appearance">
      <h2 className="mb-2 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-faint">appearance</h2>
      <div role="group" aria-label="Color mode" className="flex overflow-hidden rounded-[5px] border border-edge">
        {([
          ['light', 'Light mode', <Sun key="sun" size={14} strokeWidth={1.5} />],
          ['dark', 'Dark mode', <Moon key="moon" size={14} strokeWidth={1.5} />],
        ] as const).map(([value, label, icon]) => (
          <button
            key={value}
            type="button"
            aria-label={label}
            aria-pressed={mode === value}
            onClick={() => onPick(value)}
            className={`flex flex-1 cursor-pointer items-center justify-center gap-2 border-0 px-3 py-2 font-mono text-xs transition-colors ${
              mode === value ? 'bg-accent-soft text-accent' : 'bg-transparent text-muted hover:bg-raised hover:text-fg'
            }`}
          >
            {icon}
            {value}
          </button>
        ))}
      </div>
    </section>
  );
}

/**
 * WHAT THE PAGE IS RIGHT NOW. The pre-paint script in web/index.html has
 * already stamped the reader's stored choice by the time React mounts, so the
 * document is the only honest source for the control's opening state — a
 * constant here can only disagree with what the reader is looking at, and it
 * survives the default mode being changed.
 */
const currentAppAppearance = (): AppearanceMode =>
  typeof document !== 'undefined' && document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light';

/** One reader choice, two surfaces: the app shell and (when supplied) the
 * artifact runtime. Keeping the app write here means controlled document
 * controls cannot accidentally skip the shell preference. */
function applyAppAppearance(mode: AppearanceMode) {
  // Light is the default and carries NO attribute (app/globals.css puts it on
  // bare `:root`), so dark is the one that gets stamped.
  if (mode === 'dark') document.documentElement.dataset.theme = 'dark';
  else delete document.documentElement.dataset.theme;
  try { localStorage.setItem('mx_theme', mode); } catch { /* private mode */ }
}

export function PageControls({
  initialOpen = false,
  fixed = false,
  rightOffset = EDGE,
  label = 'Page controls',
  mode: controlledMode,
  onModeChange,
  active = false,
  badge = 0,
  children,
  triggerless = false,
  panelTop,
}: {
  initialOpen?: boolean;
  fixed?: boolean;
  /** Distance from the viewport's right edge. Artifact rails move the control
      to the document edge so it never covers the rail's own close button. */
  rightOffset?: number;
  label?: string;
  mode?: AppearanceMode;
  onModeChange?: (mode: AppearanceMode) => void;
  active?: boolean;
  badge?: number;
  children?: React.ReactNode | ((close: () => void) => React.ReactNode);
  /** No button of its own: the framed document's chrome opens it (requestPageChrome). */
  triggerless?: boolean;
  /** Where the dropdown starts, when more than the bar sits above it (edit mode). */
  panelTop?: number;
}) {
  const [open, setOpen] = useState(initialOpen);
  useEffect(()=>{if(initialOpen)setOpen(true);},[initialOpen]);
  const [appMode, setAppMode] = useState<AppearanceMode>(currentAppAppearance);
  const toggle = useExclusiveLayer(open, setOpen);
  useOpenOnRequest('controls', open, setOpen);
  useEffect(() => { announcePanel('controls', open); }, [open]);
  const mode = controlledMode ?? appMode;

  // Re-reads the page when a controlled document hands the control back. The
  // question "what mode is this" is asked HERE and in the initial state, both
  // through currentAppAppearance so the two can never answer differently.
  useEffect(() => {
    if (controlledMode) return;
    setAppMode(currentAppAppearance());
  }, [controlledMode]);

  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  const pickMode = (next: AppearanceMode) => {
    setAppMode(next);
    applyAppAppearance(next);
    onModeChange?.(next);
  };

  const close = () => setOpen(false);
  const body = (
    <div className="space-y-4">
      <AppearancePicker mode={mode} onPick={pickMode} />
      {children && (
        <div className="border-t border-edge pt-3">
          {typeof children === 'function' ? children(close) : children}
        </div>
      )}
    </div>
  );
  const header = (
    <div className="mb-3 flex items-center justify-between gap-3">
      <h1 className="font-mono text-xs font-semibold text-fg">{label.toLowerCase()}</h1>
      <button type="button" aria-label={`Dismiss ${label.toLowerCase()}`} onClick={close} className="cursor-pointer rounded-[4px] p-1 text-muted hover:bg-raised hover:text-fg">
        <X size={15} strokeWidth={1.5} />
      </button>
    </div>
  );

  return (
    <>
      {!triggerless && <Tooltip content={label.toLowerCase()} positioning={{ placement: 'bottom-end' }}>
        <button
          type="button"
          aria-label={open ? `Close ${label.toLowerCase()}` : `Open ${label.toLowerCase()}`}
          aria-expanded={open}
          onClick={toggle}
          data-chrome-placement="page"
          className={`${triggerPosition('right', fixed, open)} ${FLOATING_BUTTON} ${active || open ? 'text-accent' : ''}`}
          style={{
            top: `max(${EDGE}px, env(safe-area-inset-top))`,
            right: rightOffset === EDGE ? `max(${EDGE}px, env(safe-area-inset-right))` : rightOffset,
          }}
        >
          {open ? <X size={17} strokeWidth={1.5} /> : <SlidersVertical size={17} strokeWidth={1.5} />}
          {badge > 0 && (
            <span aria-label="Open annotation count" className="absolute -right-1 -top-1 inline-flex h-4 min-w-4 items-center justify-center rounded-full bg-accent px-1 font-mono text-[9px] leading-none text-surface">
              {badge}
            </span>
          )}
        </button>
      </Tooltip>}

      <PagePanel open={open} label={label} onClose={close} header={header} rightOffset={rightOffset} panelTop={panelTop}>{body}</PagePanel>
    </>
  );
}

const BAR_BUTTON =
  'flex h-9 w-9 cursor-pointer items-center justify-center rounded-[8px] border-0 bg-transparent text-muted transition-colors hover:bg-raised hover:text-fg';

/**
 * ONE BAR, ALWAYS THERE. Every app page carries one 44px bar in its own flow —
 * the logo home on the left, the page's crumb beside it, and the two panels'
 * buttons on the right — the same shape the reader's document bar has, so
 * moving between a document and the app does not change where anything is.
 * Sticky, not fixed, so it never covers content.
 */
export function AppBar({
  title,
  hideBreadcrumb = false,
  label = 'Page controls',
  fixed = false,
  center,
  actions,
}: {
  title?: string | null;
  hideBreadcrumb?: boolean;
  label?: string;
  /** Over a page that does not flow (the artifact page in edit mode) rather than in one. */
  fixed?: boolean;
  /** Something to say in the middle — "edit mode". */
  center?: React.ReactNode;
  actions?: React.ReactNode;
}) {
  const pathname = usePathname() ?? '';
  const trail = hideBreadcrumb ? [] : crumbsFor(pathname, title);
  const [openPanel, setOpenPanel] = useState<PagePanelName | null>(null);
  // Outside a SessionProvider this is `session: null`, and the glyph stays.
  const { session } = useSession();
  const person = session?.kind === 'account' ? session.user : null;
  useEffect(() => subscribePageChrome((which,open) => {
    setOpenPanel(current => open ? which : current === which ? null : current);
  }), []);
  const control = (which: 'menu' | 'controls', name: string, icon: React.ReactNode, face?: React.ReactNode) => {
    const open = openPanel === which;
    return (
      <Tooltip content={name} positioning={{ placement: 'bottom-end' }}>
        <button
          type="button"
          aria-label={open ? `Close ${name}` : `Open ${name}`}
          aria-expanded={open}
          onClick={() => requestPageChrome(which)}
          className={`${BAR_BUTTON} ${open ? 'text-accent' : ''}`}
        >
          {face
            // A face stays a face when its menu opens; the ring says open.
            ? <span className={`rounded-full ring-offset-1 ring-offset-surface ${open ? 'ring-2 ring-accent' : ''}`}>{face}</span>
            : open ? <X size={17} strokeWidth={1.5} /> : icon}
        </button>
      </Tooltip>
    );
  };
  return (
    <>
    <header aria-label="Page bar" className={`${fixed ? 'fixed inset-x-0 top-0' : 'sticky top-0'} z-40 flex h-11 items-center gap-2 sm:gap-3 border-b border-edge bg-surface/85 px-3 backdrop-blur-md`}>
      {center && <div className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">{center}</div>}
      <a href="/" aria-label="Home" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[8px] no-underline transition-colors hover:bg-raised">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/logo-128.png" alt="" style={{ width: CHROME_IDENTITY.logoSize, height: CHROME_IDENTITY.logoSize }} />
      </a>
      <a href="/" className="min-w-0 truncate font-mono text-[13px] font-medium text-fg no-underline hover:text-accent sm:hidden">artifactbin</a>
      {/* Desktop breadcrumbs; phones keep the brand beside the logo. */}
      <nav aria-label="Current page" className="hidden min-w-0 items-center gap-2 font-mono text-fg sm:flex" style={{ fontSize: CHROME_IDENTITY.fontSize, fontWeight: CHROME_IDENTITY.fontWeight }}>
        <a href="/" className={`shrink-0 no-underline hover:text-accent ${trail.length === 0 ? 'font-semibold text-fg' : 'text-muted'}`}>artifactbin</a>
        {trail.length === 0 && (
          <>
            <span aria-hidden="true" className="text-faint">·</span>
            <span className="truncate font-normal text-muted">Google Docs for agents</span>
          </>
        )}
        {trail.map((crumb) => (
          <span key={`${crumb.href ?? ''}:${crumb.label}`} className="flex min-w-0 items-center gap-2">
            <ChevronRight size={14} className="shrink-0 text-faint" aria-hidden="true" />
            {crumb.href ? (
              <a href={crumb.href} className="shrink-0 text-muted no-underline hover:text-accent">{crumb.label}</a>
            ) : (
              <span className="min-w-0 truncate font-semibold text-fg">{crumb.label}</span>
            )}
          </span>
        ))}
      </nav>
      <div className="ml-auto flex shrink-0 items-center gap-1">
        <GitHubStar placement="desktop-bar" />
        <GitHubStar placement="mobile-bar" />
        {actions}
        {/* The document bar's glyphs, at its size and stroke, so the two bars read as one. */}
        <NotificationBell/>
        {control('controls', label.toLowerCase(), <SlidersVertical size={20} strokeWidth={1.5} />)}
        {control('menu', 'menu', <CircleUser size={20} strokeWidth={1.5} />, person
          ? <Avatar image={person.image} initial={person.username || person.email || '?'} userId={person.id} size={24} />
          : undefined)}
      </div>
    </header>
    <NotificationMenu/>
    </>
  );
}

export default function PageChrome({
  authed,
  anon = false,
  title,
  hideBreadcrumb = false,
  label = 'Page controls',
  children,
  actions,
}: {
  authed: boolean;
  anon?: boolean;
  title?: string | null;
  hideBreadcrumb?: boolean;
  /** The controls panel's name — "Artifact controls" on an artifact page. */
  label?: string;
  actions?: React.ReactNode;
  /** Extra rows for the controls panel (an artifact's own actions). */
  children?: React.ReactNode | ((close: () => void) => React.ReactNode);
}) {
  return (
    <>
      <AppBar title={title} label={label} hideBreadcrumb={hideBreadcrumb} actions={actions} />
      <PageMenu authed={authed} anon={anon} title={title} fixed triggerless />
      <PageControls fixed triggerless label={label}>{children}</PageControls>
    </>
  );
}

// services/app/solid/components/PageChrome.tsx
/* @jsxImportSource solid-js */
import { createContext, createEffect, createSignal, For, onCleanup, Show, useContext, type JSX, type Setter } from 'solid-js';
/** Shared Solid app chrome. One owner closes one panel before another opens. */
import { Bell, BookOpen, ChevronRight, CircleUser, FileText, LogIn, LogOut, Moon, SlidersVertical, Sun, User, X } from 'lucide-solid';
import { GitHubIcon } from './brand-icons';
import { useLocation } from '@solidjs/router';
import { crumbsFor } from '@/lib/breadcrumb';
import { CHROME_IDENTITY } from '@/lib/chrome-identity';
import { githubStarMarkup, wireGithubStar } from '@/lib/github-star';
import { REPO_URL } from '@/lib/repo';
import { forgetTokens } from '@/lib/browser-session';
import { loginHref } from '../shared/login-href';
import { useSession } from '../web/session';
import { Tooltip } from './Tooltip';
import { PeopleInbox } from './PeopleInbox';
import { useInbox } from '../web/notifications';
import { Avatar } from './Avatar';

/** Artifact controls from the editor seam; the named export below owns app pages. */
export default function ArtifactPageChrome(props: { authed: boolean; anon: boolean; title: string; label: string; children: JSX.Element }): JSX.Element {
  const [open, setOpen] = createSignal(false);
  return <aside class="fixed right-4 top-4 z-40">
    <button type="button" aria-label="Open artifact controls" aria-expanded={open()} onClick={() => setOpen(value => !value)} class="rounded border border-edge bg-surface px-3 py-2 text-xs text-fg">{props.title || 'Artifact'} ···</button>
    <Show when={open()}><div role="dialog" aria-label={props.label} class="absolute right-0 mt-2 w-64 rounded border border-edge bg-surface p-3 shadow-xl"><div class="mb-3 flex items-center justify-between"><h1 class="font-mono text-xs font-semibold">{props.label.toLowerCase()}</h1><button type="button" aria-label={`Dismiss ${props.label.toLowerCase()}`} onClick={() => setOpen(false)}>×</button></div>{props.children}</div></Show>
  </aside>;
}

type Panel = 'menu' | 'controls' | 'notifications' | null;
/** A route may suppress the app bar while it owns the whole viewport (the 404 page). */
export const ChromeVisibilityContext = createContext<Setter<boolean>>();
export function useChromeVisibility(): Setter<boolean> | undefined { return useContext(ChromeVisibilityContext); }
const BAR_BUTTON = 'flex h-9 w-9 cursor-pointer items-center justify-center rounded-[8px] border-0 bg-transparent text-muted transition-colors hover:bg-raised hover:text-fg';

function Star(props: { mobile: boolean }): JSX.Element {
  let root!: HTMLSpanElement;
  createEffect(() => wireGithubStar(root));
  return <span ref={root} data-mx-github-star="" class={`${props.mobile ? 'inline-flex sm:hidden' : 'hidden sm:inline-flex'} h-7 shrink-0 items-center text-fg print:hidden`} innerHTML={githubStarMarkup(!props.mobile)} />;
}

export function PageChrome(): JSX.Element {
  const location = useLocation();
  const { session } = useSession();
  const inbox = useInbox();
  const [panel, setPanel] = createSignal<Panel>(null);
  const [mode, setMode] = createSignal<'light' | 'dark'>(typeof document !== 'undefined' && document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light');
  const person = () => session()?.kind === 'account' ? session()?.user : null;
  const crumbs = () => crumbsFor(location.pathname);
  const toggle = (next: Panel) => setPanel(current => current === next ? null : next);
  const close = () => setPanel(null);
  const pick = (next: 'light' | 'dark') => {
    setMode(next);
    if (next === 'dark') document.documentElement.dataset.theme = 'dark';
    else delete document.documentElement.dataset.theme;
    try { localStorage.setItem('mx_theme', next); } catch { /* private mode */ }
  };
  const unread = () => Boolean(inbox.state()?.unread);
  createEffect(() => {
    if (!panel()) return;
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); };
    window.addEventListener('keydown', escape);
    onCleanup(() => window.removeEventListener('keydown', escape));
  });
  return <>
    <header aria-label="Page bar" class="sticky top-0 z-40 flex h-11 items-center gap-2 border-b border-edge bg-surface/85 px-3 backdrop-blur-md sm:gap-3">
      <a href="/" aria-label="Home" class="flex h-9 w-9 shrink-0 items-center justify-center rounded-[8px] no-underline transition-colors hover:bg-raised"><img src="/logo-128.png" alt="" style={{ width: `${CHROME_IDENTITY.logoSize}px`, height: `${CHROME_IDENTITY.logoSize}px` }} /></a>
      <a href="/" class="min-w-0 truncate font-mono text-[13px] font-medium text-fg no-underline hover:text-accent sm:hidden">artifactbin</a>
      <nav aria-label="Current page" class="hidden min-w-0 items-center gap-2 font-mono text-fg sm:flex" style={{ 'font-size': `${CHROME_IDENTITY.fontSize}px`, 'font-weight': CHROME_IDENTITY.fontWeight }}>
        <a href="/" class={`shrink-0 no-underline hover:text-accent ${crumbs().length ? 'text-muted' : 'font-semibold text-fg'}`}>artifactbin</a>
        <Show when={!crumbs().length}><span aria-hidden="true" class="text-faint">·</span><span class="truncate font-normal text-muted">Google Docs for agents</span></Show>
        <For each={crumbs()}>{crumb => <span class="flex min-w-0 items-center gap-2"><ChevronRight size={14} class="shrink-0 text-faint" aria-hidden="true" /><Show when={crumb.href} fallback={<span class="min-w-0 truncate font-semibold text-fg">{crumb.label}</span>}><a href={crumb.href} class="shrink-0 text-muted no-underline hover:text-accent">{crumb.label}</a></Show></span>}</For>
      </nav>
      <div class="ml-auto flex shrink-0 items-center gap-1">
        <Star mobile={false} /><Star mobile={true} />
        <Show when={person()}><Tooltip content="Notifications"><button type="button" aria-label={unread() ? 'Notifications, unread updates' : 'Notifications'} aria-expanded={panel() === 'notifications'} onClick={() => toggle('notifications')} class={`${BAR_BUTTON} relative`}><Bell size={20} strokeWidth={1.5} /><Show when={unread()}><span aria-hidden="true" class="absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500" /></Show></button></Tooltip></Show>
        <Tooltip content="page controls"><button type="button" aria-label={panel() === 'controls' ? 'Close page controls' : 'Open page controls'} aria-expanded={panel() === 'controls'} onClick={() => toggle('controls')} class={BAR_BUTTON}>{panel() === 'controls' ? <X size={17} /> : <SlidersVertical size={20} strokeWidth={1.5} />}</button></Tooltip>
        <Tooltip content="menu"><button type="button" aria-label={panel() === 'menu' ? 'Close menu' : 'Open menu'} aria-expanded={panel() === 'menu'} onClick={() => toggle('menu')} class={BAR_BUTTON}><Show when={person()} fallback={panel() === 'menu' ? <X size={17} /> : <CircleUser size={20} strokeWidth={1.5} />}><span class={`rounded-full ring-offset-1 ring-offset-surface ${panel() === 'menu' ? 'ring-2 ring-accent' : ''}`}><Avatar image={person()?.image ?? null} initial={person()?.username || person()?.email || '?'} userId={person()?.id ?? ''} size={24} /></span></Show></button></Tooltip>
      </div>
    </header>
    <Show when={panel()}>
      <button type="button" aria-label="Close panel" class="fixed inset-0 z-40 cursor-default border-0 bg-black/25 p-0" onClick={close} />
      <Show when={panel() === 'menu'}>
        <PageMenuPanel close={close} />
      </Show>
      <Show when={panel() === 'controls'}><section aria-label="Page controls" class="fixed right-3 top-14 z-50 w-72 rounded-[7px] border border-edge bg-surface p-4 shadow-xl"><div class="mb-3 flex items-center justify-between"><h1 class="font-mono text-xs font-semibold">page controls</h1><button type="button" aria-label="Dismiss page controls" onClick={close}><X size={15} /></button></div><section aria-label="Appearance"><h2 class="mb-2 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-faint">appearance</h2><div role="group" aria-label="Color mode" class="flex overflow-hidden rounded-[5px] border border-edge"><button type="button" aria-label="Light mode" aria-pressed={mode() === 'light'} onClick={() => pick('light')} class="flex flex-1 items-center justify-center gap-2 px-3 py-2 font-mono text-xs"><Sun size={14} />light</button><button type="button" aria-label="Dark mode" aria-pressed={mode() === 'dark'} onClick={() => pick('dark')} class="flex flex-1 items-center justify-center gap-2 px-3 py-2 font-mono text-xs"><Moon size={14} />dark</button></div></section></section></Show>
      <Show when={panel() === 'notifications'}><NotificationsPanel close={close} /></Show>
    </Show>
  </>;
}

const MENU_ROW = 'flex w-full items-center gap-3 rounded-[5px] border-0 bg-transparent px-3 py-3 text-left font-mono text-sm no-underline transition-colors sm:gap-2.5 sm:px-2.5 sm:py-2 sm:text-xs';

/**
 * The app menu (links, then sign out / disconnect / login), shared by the app bar and the document
 * page. On its own it is the app's left DRAWER; opened from a document's chrome (`dropdown`) it drops
 * under the bar at the right, and is a bottom sheet on a phone — the twin of the controls panel.
 */
export function PageMenuPanel(props: { close: () => void; dropdown?: boolean; phone?: boolean; top?: number }): JSX.Element {
  const { session } = useSession();
  const location = useLocation();
  const person = () => session()?.kind === 'account' ? session()?.user : null;
  const close = () => props.close();
  const link = (href: string, label: string, icon: JSX.Element) => {
    const active = () => location.pathname === href;
    return <a href={href} rel={['/', '/assets', '/trash', '/login', '/start', '/welcome', '/notifications', '/account', '/docs-human', '/chat'].includes(href) ? undefined : 'external'} aria-label={label}
      class={`${MENU_ROW} cursor-pointer ${active() ? 'bg-accent-soft text-accent' : 'text-muted hover:bg-raised hover:text-fg'}`} onClick={close}>{icon}{label}</a>;
  };
  const placement = () => props.dropdown
    ? (props.phone
      ? 'fixed inset-x-0 bottom-0 z-50 flex animate-[rise_.14s_ease-out] flex-col rounded-t-[10px] border-t border-edge bg-surface p-3 pb-[max(20px,env(safe-area-inset-bottom))] shadow-xl'
      : 'fixed right-3 top-14 z-50 flex w-72 animate-[rise_.14s_ease-out] flex-col rounded-[7px] border border-edge bg-surface p-2 shadow-xl')
    : 'fixed inset-y-0 left-0 z-50 flex w-full animate-[drawer-in_.15s_ease-out] flex-col border-r border-edge bg-surface p-2 pt-16 shadow-xl sm:w-72';
  return (
    <nav aria-label="Menu" class={placement()} style={props.dropdown && !props.phone && props.top !== undefined ? { top: `${props.top}px` } : undefined}>
      <button type="button" aria-label="Dismiss menu" onClick={close} style={{ top: 'max(12px, env(safe-area-inset-top))' }}
        class="absolute right-3 top-3 flex h-9 w-9 cursor-pointer items-center justify-center rounded-full border border-edge bg-surface text-muted hover:bg-raised hover:text-fg sm:hidden"><X size={17} stroke-width={1.5} /></button>
      <a href="/" aria-label="Hosted at artifactbin" class="mb-3 flex items-center gap-2.5 px-2 font-mono text-sm font-semibold text-fg no-underline transition-colors hover:text-accent"><img src="/logo-128.png" alt="" class="h-7 w-7" />artifactbin</a>
      {link('/', 'Artifacts', <FileText size={15} stroke-width={1.5} />)}
      {link('/chat', 'Remote sessions', <User size={15} stroke-width={1.5} />)}
      {link('/notifications', 'Notifications', <User size={15} stroke-width={1.5} />)}
      {link('/account', 'Account', <User size={15} stroke-width={1.5} />)}
      {link('/docs-human', 'Human Docs', <BookOpen size={15} stroke-width={1.5} />)}
      <a href={REPO_URL} target="_blank" rel="noopener noreferrer" class={`${MENU_ROW} cursor-pointer text-muted hover:bg-raised hover:text-fg`} onClick={close}><GitHubIcon size={15} />Support artifactbin</a>
      <div class="mt-auto" /><div class="my-1 h-px bg-edge" />
      <Show when={person()} fallback={<Show when={session()?.kind === 'anon'} fallback={link(loginHref(window.location), 'Login', <LogIn size={15} stroke-width={1.5} />)}>
        <button type="button" aria-label="Disconnect this browser" class={`${MENU_ROW} cursor-pointer text-muted hover:bg-raised hover:text-fg`} onClick={() => void forgetTokens().then(() => { window.location.href = '/'; })}><LogOut size={15} stroke-width={1.5} />Disconnect this browser</button>
      </Show>}>
        <button type="button" aria-label="Sign out" class={`${MENU_ROW} cursor-pointer text-muted hover:bg-raised hover:text-fg`} onClick={() => void fetch('/api/auth/sign-out', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }).catch(() => null).then(() => { window.location.href = '/'; })}><LogOut size={15} stroke-width={1.5} />Sign out</button>
      </Show>
    </nav>
  );
}

/** The notifications panel, shared by the app bar and the document page. */
export function NotificationsPanel(props: { close: () => void }): JSX.Element {
  const close = () => props.close();
  return <section aria-label="Notifications" class="fixed right-3 top-14 z-50 w-80 rounded-[7px] border border-edge bg-surface p-4 shadow-xl"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold">Notifications</h2><button type="button" aria-label="Close notifications" onClick={close}><X size={18} /></button></div><div class="max-h-[55vh] overflow-y-auto"><PeopleInbox compact close={close} /></div><nav aria-label="Notification links" class="mt-2 flex flex-col gap-2 border-t border-edge pt-3"><a href="/notifications" onClick={close}>All notifications</a><a href="/account#notifications" onClick={close}>Notification settings</a></nav></section>;
}
