// services/app/components/TokensPanel.tsx
'use client';

import { useConfirmation } from './ConfirmDialog';
import { Ban } from 'lucide-react';
import { usePageData } from '@/web/use-page-data';
import { Button, MicroLabel, PANEL, TABLE_ROW } from '@/components/ui';

interface UserTokenView {
  id: string;
  name: string | null;
  status: 'active' | 'expired' | 'revoked';
  created_at: string;
  deleted_at: string | null;
  expires_at: string | null;
  last_used_at: string | null;
}

function relativeTime(iso: string | null, now = Date.now()): string {
  if (iso === null) return 'never';
  const delta = new Date(iso).getTime() - now;
  const future = delta > 0;
  const absolute = Math.abs(delta);
  const [amount, unit] = absolute < 60 * 60 * 1000
    ? [Math.max(1, Math.floor(absolute / (60 * 1000))), 'm']
    : absolute < 24 * 60 * 60 * 1000
      ? [Math.floor(absolute / (60 * 60 * 1000)), 'h']
      : [Math.floor(absolute / (24 * 60 * 60 * 1000)), 'd'];
  return future ? `in ${amount}${unit}` : `${amount}${unit} ago`;
}

const statusDot = (status: UserTokenView['status']): string =>
  status === 'active' ? 'bg-accent' : status === 'expired' ? 'bg-danger' : 'bg-faint';

/** The user's machines: every token minted for/claimed by this account, with revoke. */
export default function TokensPanel({ tokens: initial = [] }: { tokens?: UserTokenView[] }) {
  const { confirmAction, confirmation } = useConfirmation();
  const { data } = usePageData<{ tokens: UserTokenView[] }>('/api/my/tokens');
  const tokens = data?.tokens ?? initial;

  if (tokens.length === 0) return null;

  return (
    <section>
      {confirmation}
      <div className={PANEL}>
        <table className="w-full table-fixed border-collapse text-left text-sm">
          <thead>
            <tr>
              {(
                [['name', ''], ['status', 'w-16 sm:w-24'], ['expires', 'w-16 sm:w-24'], ['last used', 'w-20 sm:w-24'], ['action', 'w-20 sm:w-28']] as const
              ).map(([h, w]) => (
                <th key={h} className={`px-2 py-2.5 sm:px-4 ${w}`}>
                  <MicroLabel>{h}</MicroLabel>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {tokens.map((t, i) => (
              <tr
                key={t.id}
                aria-label={`Token row ${t.name ?? t.id}`}
                className={`${TABLE_ROW} reveal`}
                style={{ animationDelay: `${i * 40}ms` }}
              >
                <td className="px-2 py-2 sm:px-4">
                  <span className="flex min-w-0 items-center gap-2">
                    <span
                      aria-label={`Token ${t.name ?? t.id} ${t.status} status dot`}
                      className={`h-1.5 w-1.5 shrink-0 rounded-full ${statusDot(t.status)}`}
                    />
                    <span className="min-w-0 truncate">{t.name ?? <span className="text-faint">(unnamed)</span>}</span>
                  </span>
                </td>
                <td aria-label={`Token ${t.name ?? t.id} status`} className="px-2 py-2 text-xs text-muted sm:px-4">
                  {t.status}
                </td>
                <td aria-label={`Token ${t.name ?? t.id} expires`} className="whitespace-nowrap px-2 py-2 text-xs text-muted sm:px-4">
                  {relativeTime(t.expires_at)}
                </td>
                <td aria-label={`Token ${t.name ?? t.id} last used`} className="whitespace-nowrap px-2 py-2 text-xs text-muted sm:px-4">
                  {relativeTime(t.last_used_at)}
                </td>
                <td className="px-2 py-2 sm:px-4">
                  {t.status === 'revoked' ? (
                    <span className="text-xs text-faint">—</span>
                  ) : (
                    <Button
                      variant="danger"
                      aria-label={`Revoke token ${t.name ?? t.id}`}
                      onClick={() => void confirmAction({ title: `Revoke “${t.name ?? t.id}”?`, description: 'Agents using this token will stop working immediately. This cannot be undone.', action: 'Revoke token', confirmLabel: 'Confirm revoke', danger: true }, async () => {
                        const res = await fetch(`/api/my/tokens/${t.id}`, { method: 'DELETE' });
                        if (res.ok) window.location.reload();
                        else throw new Error('Could not revoke that token. Try again.');
                      })}
                    >
                      <span className="flex items-center gap-1"><Ban size={11} /> revoke</span>
                    </Button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// services/app/solid/components/TokensPanel.tsx
/* @jsxImportSource solid-js */
import { createSignal, For, Show, type JSX } from 'solid-js';
import { Ban } from 'lucide-solid';
import { usePageData } from '../web/use-page-data';
import { MicroLabel, PANEL, TABLE_ROW } from './ui';
import { ConfirmDialog } from './ConfirmDialog';

interface UserTokenView { id: string; name: string | null; status: 'active' | 'expired' | 'revoked'; created_at: string; deleted_at: string | null; expires_at: string | null; last_used_at: string | null }
function relativeTime(iso: string | null): string { if (iso === null) return 'never'; const delta = new Date(iso).getTime() - Date.now(); const magnitude = Math.abs(delta); const [amount, unit] = magnitude < 3600000 ? [Math.max(1, Math.floor(magnitude / 60000)), 'm'] : magnitude < 86400000 ? [Math.floor(magnitude / 3600000), 'h'] : [Math.floor(magnitude / 86400000), 'd']; return delta > 0 ? `in ${amount}${unit}` : `${amount}${unit} ago`; }

export function TokensPanel(): JSX.Element {
  const page = usePageData<{ tokens: UserTokenView[] }>('/api/my/tokens');
  const [selected, setSelected] = createSignal<UserTokenView | null>(null);
  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal('');
  const revoke = async () => {
    const token = selected(); if (!token || busy()) return;
    setBusy(true); setError('');
    const response = await fetch(`/api/my/tokens/${token.id}`, { method: 'DELETE' }).catch(() => null);
    setBusy(false);
    if (!response?.ok) { setError('Could not revoke that token. Try again.'); return; }
    setSelected(null);
    await page.refresh(true);
  };
  return <Show when={page.data()?.tokens.length}><section>
    <Show when={selected()}>{token => <ConfirmDialog title={`Revoke “${token().name ?? token().id}”?`} description="Agents using this token will stop working immediately. This cannot be undone." action="Revoke token" confirmLabel="Confirm revoke" danger busy={busy()} error={error()} onCancel={() => setSelected(null)} onConfirm={() => void revoke()} />}</Show>
    <div class={PANEL}><table class="w-full table-fixed border-collapse text-left text-sm"><thead><tr><For each={['name', 'status', 'expires', 'last used', 'action']}>{heading => <th class="px-2 py-2.5 sm:px-4"><MicroLabel>{heading}</MicroLabel></th>}</For></tr></thead><tbody><For each={page.data()?.tokens}>{token => <tr aria-label={`Token row ${token.name ?? token.id}`} class={`${TABLE_ROW} reveal`}><td class="px-2 py-2 sm:px-4"><span aria-label={`Token ${token.name ?? token.id} ${token.status} status dot`} class={`mr-2 inline-block h-1.5 w-1.5 rounded-full ${token.status === 'active' ? 'bg-accent' : token.status === 'expired' ? 'bg-danger' : 'bg-faint'}`} />{token.name ?? '(unnamed)'}</td><td aria-label={`Token ${token.name ?? token.id} status`} class="px-2 py-2 text-xs text-muted sm:px-4">{token.status}</td><td aria-label={`Token ${token.name ?? token.id} expires`} class="px-2 py-2 text-xs text-muted sm:px-4">{relativeTime(token.expires_at)}</td><td aria-label={`Token ${token.name ?? token.id} last used`} class="px-2 py-2 text-xs text-muted sm:px-4">{relativeTime(token.last_used_at)}</td><td class="px-2 py-2 sm:px-4"><Show when={token.status !== 'revoked'} fallback={<span class="text-xs text-faint">—</span>}><button type="button" aria-label={`Revoke token ${token.name ?? token.id}`} onClick={() => setSelected(token)} class="inline-flex items-center gap-1 text-xs text-danger"><Ban size={11} />revoke</button></Show></td></tr>}</For></tbody></table></div>
  </section></Show>;
}
