// services/app/components/WorkspaceCreate.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ChevronDown, Database, FilePlus2, FolderPlus, Plus, Trash2, X } from 'lucide-react';
import GetStarted from '@/components/GetStarted';

type CreateKind = 'artifact' | 'folder';

function CreateDialog({
  kind,
  parentId,
  onClose,
  onCreated,
}: {
  kind: CreateKind;
  parentId: string | null;
  onClose: () => void;
  onCreated: () => void;
}) {
  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const panel = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
      if (event.key !== 'Tab' || !panel.current) return;
      const stops = [...panel.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled])')];
      if (stops.length === 0) return;
      const first = stops[0];
      const last = stops[stops.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener('keydown', onKey);
    };
  }, [onClose]);

  const createFolder = async (event: React.FormEvent) => {
    event.preventDefault();
    const title = name.trim();
    if (!title || busy) return;
    setBusy(true);
    setError('');
    const response = await fetch('/api/my/artifacts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ format: 'folder', title, parent_id: parentId }),
    }).catch(() => null);
    setBusy(false);
    if (!response?.ok) {
      setError('Could not create the folder. Try again.');
      return;
    }
    onClose();
    onCreated();
  };

  const artifact = kind === 'artifact';
  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-3 sm:p-8">
      <button
        type="button"
        aria-label="Close create dialog by clicking outside"
        onClick={onClose}
        className="absolute inset-0 cursor-default border-0 bg-black/45 p-0 backdrop-blur-[2px]"
      />
      <div
        ref={panel}
        role="dialog"
        aria-modal="true"
        aria-label={artifact ? 'Create new artifact' : 'Create new folder'}
        className={`relative z-10 flex max-h-[calc(100svh-24px)] w-full flex-col overflow-hidden rounded-[9px] border border-edge-bright bg-surface shadow-2xl ${artifact ? 'max-w-3xl' : 'max-w-md'}`}
      >
        <header className="flex items-start gap-4 border-b border-edge px-4 py-4 sm:px-6">
          <div className="min-w-0">
            <h2 className="flex items-center gap-2 font-mono text-sm font-semibold text-fg">
              {artifact ? <FilePlus2 aria-hidden="true" size={15} className="text-accent" /> : <FolderPlus aria-hidden="true" size={15} className="text-accent" />}
              {artifact ? 'New artifact' : 'New folder'}
            </h2>
            <p className="mt-1 font-sans text-xs text-muted">
              {artifact ? 'Connect an agent, then tell it what you want to make.' : 'Folders keep related artifacts and data files together.'}
            </p>
          </div>
          <button
            type="button"
            aria-label="Close create dialog"
            autoFocus={artifact}
            onClick={onClose}
            className="ml-auto inline-flex h-7 w-7 shrink-0 cursor-pointer items-center justify-center rounded-[4px] text-muted transition-colors hover:bg-raised hover:text-fg"
          >
            <X size={15} />
          </button>
        </header>

        {artifact ? (
          <div className="overflow-y-auto px-4 py-4 sm:px-6 sm:py-5">
            {parentId && (
              <p className="mb-4 rounded-[5px] border border-edge bg-raised px-3 py-2 font-mono text-[10px] text-muted">
                create inside this folder with <code className="text-fg">parent_id: &quot;{parentId}&quot;</code>
              </p>
            )}
            <GetStarted heading={false} frame={false} />
          </div>
        ) : (
          <form onSubmit={createFolder} className="px-4 py-5 sm:px-6">
            <label htmlFor="workspace-folder-name" className="block font-mono text-[10px] tracking-[0.12em] text-muted uppercase">
              Folder name
            </label>
            <input
              id="workspace-folder-name"
              autoFocus
              required
              value={name}
              onChange={(event) => setName(event.target.value)}
              placeholder="e.g. Research"
              className="mt-2 h-9 w-full rounded-[5px] border border-edge bg-bg px-3 font-mono text-xs text-fg placeholder:text-faint focus:border-accent focus:outline-none"
            />
            {error && <p role="alert" className="mt-2 font-mono text-[10px] text-danger">{error}</p>}
            <div className="mt-5 flex justify-end gap-2 border-t border-edge pt-4">
              <button
                type="button"
                onClick={onClose}
                className="cursor-pointer rounded-[5px] border border-edge bg-transparent px-3 py-1.5 font-mono text-[11px] text-muted transition-colors hover:border-edge-bright hover:text-fg"
              >
                cancel
              </button>
              <button
                type="submit"
                disabled={!name.trim() || busy}
                className="inline-flex cursor-pointer items-center gap-1.5 rounded-[5px] border border-accent bg-accent px-3 py-1.5 font-mono text-[11px] text-bg transition-opacity disabled:cursor-default disabled:opacity-40"
              >
                <FolderPlus aria-hidden="true" size={13} />
                {busy ? 'creating…' : 'create folder'}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>,
    document.body,
  );
}

/** The homepage's single creation door: choice first, details second. */
export default function WorkspaceCreate({ onCreated, parentId = null }: { onCreated: () => void; parentId?: string | null }) {
  const [open, setOpen] = useState(false);
  const [dialog, setDialog] = useState<CreateKind | null>(null);
  const root = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const close = (event: MouseEvent) => {
      if (!root.current?.contains(event.target as Node)) setOpen(false);
    };
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setOpen(false);
    };
    window.addEventListener('mousedown', close);
    window.addEventListener('keydown', closeOnEscape);
    return () => {
      window.removeEventListener('mousedown', close);
      window.removeEventListener('keydown', closeOnEscape);
    };
  }, [open]);

  const choose = (kind: CreateKind) => {
    setOpen(false);
    setDialog(kind);
  };

  return (
    <div ref={root} className="relative z-30 lg:border-b lg:border-edge lg:pb-3">
      <div className="relative">
        <button
          type="button"
          aria-label="Create"
          aria-expanded={open}
          aria-haspopup="menu"
          onClick={() => setOpen((value) => !value)}
          className="group flex h-9 w-full cursor-pointer items-center rounded-[5px] border border-accent bg-accent px-3 font-mono text-xs font-semibold text-bg transition-[filter] hover:brightness-105"
        >
          <Plus aria-hidden="true" size={15} strokeWidth={2} />
          <span className="ml-2">Create</span>
          <ChevronDown aria-hidden="true" size={14} className={`ml-auto transition-transform ${open ? 'rotate-180' : ''}`} />
        </button>

        {open && (
          <div role="menu" aria-label="Create menu" className="absolute inset-x-0 top-[calc(100%+0.35rem)] z-40 overflow-hidden rounded-[6px] border border-edge-bright bg-surface p-1 shadow-xl">
            <button
              type="button"
              role="menuitem"
              onClick={() => choose('artifact')}
              className="flex w-full cursor-pointer items-center gap-2 rounded-[4px] px-2.5 py-2 text-left font-mono text-[11px] text-fg transition-colors hover:bg-accent-soft hover:text-accent"
            >
              <FilePlus2 aria-hidden="true" size={14} />
              New artifact
            </button>
            <a
              href="/datasets/new"
              role="menuitem"
              aria-label="Create dataset"
              onClick={() => setOpen(false)}
              className="flex w-full cursor-pointer items-center gap-2 rounded-[4px] px-2.5 py-2 text-left font-mono text-[11px] text-fg no-underline transition-colors hover:bg-accent-soft hover:text-accent"
            >
              <Database aria-hidden="true" size={14} />
              New dataset
            </a>
            <button
              type="button"
              role="menuitem"
              onClick={() => choose('folder')}
              className="flex w-full cursor-pointer items-center gap-2 rounded-[4px] px-2.5 py-2 text-left font-mono text-[11px] text-fg transition-colors hover:bg-accent-soft hover:text-accent"
            >
              <FolderPlus aria-hidden="true" size={14} />
              New folder
            </button>
          </div>
        )}
      </div>

      <nav aria-label="Workspace shortcuts" className="mt-2 grid grid-cols-2 gap-1">
        <a href="/assets" aria-label="Assets" className="flex h-7 items-center justify-center gap-1.5 rounded-[4px] border border-edge bg-raised px-2 font-mono text-[11px] text-muted no-underline transition-colors hover:border-edge-bright hover:text-accent">
          <Database aria-hidden="true" size={13} strokeWidth={1.7} />
          Assets
        </a>
        <a href="/trash" aria-label="Trash" className="flex h-7 items-center justify-center gap-1.5 rounded-[4px] border border-edge bg-raised px-2 font-mono text-[11px] text-muted no-underline transition-colors hover:border-edge-bright hover:text-accent">
          <Trash2 aria-hidden="true" size={13} strokeWidth={1.7} />
          Trash
        </a>
      </nav>

      {dialog && <CreateDialog kind={dialog} parentId={parentId} onClose={() => setDialog(null)} onCreated={onCreated} />}
    </div>
  );
}

// services/app/solid/components/WorkspaceCreate.tsx
/* @jsxImportSource solid-js */
import { createSignal, Show, type JSX } from 'solid-js';
import { Portal } from 'solid-js/web';
import ChevronDown from 'lucide-solid/icons/chevron-down';
import Plus from 'lucide-solid/icons/plus';
import FilePlus2 from 'lucide-solid/icons/file-plus-2';
import FolderPlus from 'lucide-solid/icons/folder-plus';
import FileUp from 'lucide-solid/icons/file-up';
import DatabasePlus from 'lucide-solid/icons/database-plus';
import Database from 'lucide-solid/icons/database';
import Trash2 from 'lucide-solid/icons/trash-2';
import { pageDataChanged } from '@/web/page-data-events';
import GetStarted from './GetStarted';
import { DialogShell } from '@/solid/components/DialogShell';
import { popupDismiss } from '@/lib/islands/kit/popup-dismiss';

const ITEM = 'group flex w-full cursor-pointer items-center gap-2.5 rounded-[4px] px-2.5 py-2 text-left font-mono text-[11.5px] text-fg no-underline hover:bg-accent-soft hover:text-accent';
type Kind = 'artifact' | 'folder';
export default function WorkspaceCreate(props: { onCreated: () => void; parentId?: string | null }): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [dialog, setDialog] = createSignal<Kind | null>(null);
  const [name, setName] = createSignal('');
  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal('');
  let root!: HTMLDivElement;
  let button!: HTMLButtonElement;
  const announce = popupDismiss(open, () => setOpen(false), () => button, () => root);
  const choose = (kind: Kind) => { setOpen(false); setDialog(kind); };
  const createFolder = async (event: SubmitEvent) => {
    event.preventDefault();
    const title = name().trim(); if (!title || busy()) return;
    setBusy(true); setError('');
    const response = await fetch('/api/my/artifacts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ format: 'folder', title, parent_id: props.parentId ?? null }) }).catch(() => null);
    setBusy(false);
    if (!response?.ok) { setError('Could not create the folder. Try again.'); return; }
    pageDataChanged(); props.onCreated(); setDialog(null); setName('');
  };
  return <div ref={root} class="relative z-30 lg:border-b lg:border-edge lg:pb-3">
    <button ref={button} type="button" aria-label="Create" aria-expanded={open()} aria-haspopup="menu" onClick={() => { if (!open()) announce(); setOpen(value => !value); }} class="group flex h-9 w-full items-center rounded-[5px] border border-accent bg-accent px-3 font-mono text-xs font-semibold text-bg"><Plus size={15} /><span class="ml-2">Create</span><ChevronDown size={14} class="ml-auto" /></button>
    <Show when={open()}><div role="menu" aria-label="Create menu" class="absolute inset-x-0 top-[calc(100%+0.35rem)] z-40 rounded-[6px] border border-edge-bright bg-surface p-1 shadow-xl"><button type="button" role="menuitem" class={ITEM} onClick={() => choose('artifact')}><FilePlus2 size={14} />Artifact</button><button type="button" role="menuitem" class={ITEM} onClick={() => choose('folder')}><FolderPlus size={14} />Folder</button><div class="mt-1 border-t border-edge pt-1"><span class="block px-2.5 pt-1.5 pb-1 font-mono text-[9.5px] uppercase tracking-[0.14em] text-faint">assets</span><a role="menuitem" href={props.parentId ? `/files/new?parent_id=${encodeURIComponent(props.parentId)}` : '/files/new'} class={ITEM}><FileUp size={14} />File</a><a role="menuitem" href="/datasets/new" class={ITEM}><DatabasePlus size={14} />Dataset</a></div></div></Show>
    <nav aria-label="Workspace shortcuts" class="mt-2 grid grid-cols-2 gap-1"><a href="/assets" aria-label="Assets" class="flex h-7 items-center justify-center gap-1.5 rounded border border-edge bg-raised font-mono text-[11px] text-muted"><Database size={13} />Assets</a><a href="/trash" aria-label="Trash" class="flex h-7 items-center justify-center gap-1.5 rounded border border-edge bg-raised font-mono text-[11px] text-muted"><Trash2 size={13} />Trash</a></nav>
    <Show when={dialog()}>{kind => <Portal mount={document.body}><DialogShell onClose={() => setDialog(null)} initialFocus="[autofocus]"><div class="fixed inset-0 z-[100] flex items-center justify-center p-3"><button type="button" aria-label="Close create dialog by clicking outside" onClick={() => setDialog(null)} class="absolute inset-0 bg-black/45" /><div role="dialog" aria-modal="true" aria-label={kind() === 'artifact' ? 'Create new artifact' : 'Create new folder'} class={`relative z-10 w-full rounded-[9px] border border-edge-bright bg-surface shadow-2xl ${kind() === 'artifact' ? 'max-w-3xl' : 'max-w-md'}`}><header class="flex items-center justify-between border-b border-edge p-4"><h2 class="font-mono text-sm font-semibold">New {kind()}</h2><button type="button" aria-label="Close create dialog" onClick={() => setDialog(null)}>×</button></header><Show when={kind() === 'folder'} fallback={<div class="p-5"><Show when={props.parentId}><p class="mb-3 font-mono text-xs">create inside this folder with <code>parent_id: &quot;{props.parentId}&quot;</code></p></Show><GetStarted heading={false} frame={false} /></div>}><form onSubmit={event => void createFolder(event)} class="p-5"><label for="workspace-folder-name" class="block font-mono text-xs">Folder name</label><input id="workspace-folder-name" autofocus required value={name()} onInput={event => setName(event.currentTarget.value)} class="mt-2 w-full rounded border border-edge bg-bg p-2 font-mono text-xs" /><Show when={error()}><p role="alert" class="text-danger">{error()}</p></Show><div class="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)}>cancel</button><button type="submit" disabled={!name().trim() || busy()} class="rounded bg-accent px-3 py-1 text-bg">{busy() ? 'creating…' : 'create folder'}</button></div></form></Show></div></div></DialogShell></Portal>}</Show>
  </div>;
}
