// services/app/components/ArtifactEditor.tsx
'use client';

/**
 * The owner's gate into editing, mounted BY the artifact page (/a/<id>) when
 * edit mode is on — a mode of that page, not a page of its own.
 *
 * Everything below it is one editor, because there is one document format:
 * InPlaceEditor, which makes the document the page is already showing
 * source. What remains here is the part that is NOT editing —
 * deciding whether this browser may write at all:
 *
 *   one GET /api/my/artifacts/<id>, authorized by whichever browser credential
 *   the cookie carries (account session or agent session), else the locked
 *   card below — there is no credential to paste, and nothing to paste it into.
 *
 * There is NO save button: changes persist through the concurrent-edit
 * protocol shortly after they stop arriving, and every way OUT drains first
 * (the flush ref below, published up to the page).
 */
import { type DocumentRuntimeRef } from '@/lib/story-runtime/document-endpoint';
import { Home, Lock } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import InPlaceEditor from '@/components/InPlaceEditor';
import type { StoryEditSelection } from '@/lib/story-runtime/contract';
import type { StoryIslandDataflow } from '@/lib/story-runtime/contract';
import { LINK, PANEL } from '@/components/ui';
import type { EditorFlushRef } from '@/lib/story/use-live-edits';

interface Loaded {
  id: string;
  title: string | null;
  markup: string | null;
  theme: string | null;
  version: number;
  /** Head pointer of the edit protocol — every edit this session sends carries it. */
  edit_id: string;
  template?: string | null;
  colorMode?: string | null;
  /**
   * Present when the editor was SEEDED from the page (which holds it); the read
   * API does not return it, so on the background-load path this is undefined and
   * the draft compile supplies the sheet instead.
   */
  compiledCss?: string | null;
  refs?: Array<{ id: string; kind: string }>;
  /** Present when SEEDED from the page: the document's server-run dataflow (InPlaceEditor's EditorArtifact). */
  dataflow?: StoryIslandDataflow | null;
}


/**
 * What the PAGE already rendered. Passing it in means entering edit mode shows
 * the document immediately instead of blanking while the editor re-fetches
 * what the server just sent — the round trip was the whole "flash".
 */
interface EditorSeed {
  id: string;
  title: string | null;
  markup: string | null;
  theme: string | null;
  colorMode?: string | null;
  template?: string | null;
  /**
   * The artifact's STORED stylesheet. Without it the canvas renders unstyled
   * until the editor's own draft compile answers — and the page launching the
   * editor already has the right sheet in hand, so there is nothing to wait for.
   */
  compiledCss?: string | null;
  version: number;
  edit_id: string;
  refs?: Array<{ id: string; kind: string }>;
  dataflow?: StoryIslandDataflow | null;
}

export default function ArtifactEditor({ id, seed, onExit, flushRef, frameRef, runtimeRef, sessionNonce, initialSelectionPath = null, onComment, onLeftInsetChange, onRightInsetChange, rightInset = 0 }: {
  id: string;
  seed?: EditorSeed;
  onExit: () => void;
  /** The live document's iframe — editing happens IN it, so it is never remounted. */
  frameRef?: { current: HTMLIFrameElement | null };
  runtimeRef?: DocumentRuntimeRef;
  /** The document's session secret, learned by the page when it announced itself. */
  sessionNonce: string | null;
  /** View-mode text selection to restore once the edit runtime is ready. */
  initialSelectionPath?: string | null;
  /** Comment on the selected node — the page owns the composer and the drain. */
  onComment?: (selection: StoryEditSelection) => void;
  /** The editor's left rail and panel; the PAGE reserves the width, the editor decides it. */
  onLeftInsetChange?: (px: number) => void;
  /** The inspector's reserved width, so the page can narrow the document for it. */
  onRightInsetChange?: (px: number) => void;
  rightInset?: number;
  /**
   * Where the mounted editor publishes its drain, so the page can empty it
   * before unmounting — the back button leaves edit mode without ever pressing
   * `done`, and an unmount cancels the debounced save.
   */
  flushRef?: EditorFlushRef;
}) {
  const [art, setArt] = useState<Loaded | null>(seed ?? null);
  const [locked, setLocked] = useState(false);

  // True until the background load has confirmed write access once.
  const seedRef = useRef(!!seed);

  /**
   * ONE endpoint, because there is one browser credential. `/api/my/*`
   * answers for an account session and for the agent-session cookie alike
   * (lib/agent-session), each in its own scope.
   */
  const load = useCallback(async () => {
    try {
      const res = await fetch(`/api/my/artifacts/${id}`);
      if (!res.ok) {
        setLocked(true);
        return;
      }
      setArt((await res.json()) as Loaded);
      setLocked(false);
      seedRef.current = false;
    } catch {
      // A load that cannot even reach the server falls to the unlock prompt,
      // never an unhandled rejection from the mount effect.
      setLocked(true);
    }
  }, [id]);

  useEffect(() => {
    void load();
  }, [load]);

  /**
   * The editor's drain, published to the page. The editing itself lives one
   * level down, so this is a pass-through — but the page must hold a stable
   * ref either way, since it unmounts the editor without asking who it is.
   */
  const childFlush = useRef<(() => Promise<void>) | null>(null);
  useEffect(() => {
    if (!flushRef) return;
    flushRef.current = () => childFlush.current?.() ?? Promise.resolve();
    return () => { flushRef.current = null; };
  }, [flushRef]);

  /**
   * The locked state: someone opened `#edit` on a document they cannot write.
   * A CARD in the middle of the page rather than a heading in the corner — this
   * is a dead end, and a dead end should look deliberate and offer its exits.
   */
  if (locked) {
    return (
      <main className="mx-auto mt-16 max-w-md px-6 pb-24">
        <div className={`${PANEL} px-6 py-5`}>
          <div className="flex items-center gap-2">
            <Lock size={13} className="shrink-0 text-muted" />
            <h1 className="font-mono text-sm font-semibold text-fg">this document is locked</h1>
          </div>
          <p className="mt-3 font-sans text-sm leading-relaxed text-muted">
            Only its owner can edit it.{' '}
            {/* Back to THIS artifact in edit mode, via the fragment — the shared
                link is unchanged by it. */}
            <a
              href={`/login?callbackUrl=${encodeURIComponent(typeof window === 'undefined' ? '/' : `${window.location.pathname}#edit`)}`}
              className={LINK}
            >
              log in
            </a>{' '}
            if it&apos;s on your account.
          </p>
          {/* Says what is NOT locked: anyone who can read the page can keep
              reading it — only writing needs the account that owns it. Without
              this line "locked" reads as "you cannot see this either". */}
          <p className="mt-3 font-mono text-[11px] leading-relaxed text-faint">
            reading stays open to anyone with the link — only editing needs the account it belongs to.
          </p>
        </div>

        {/* The two ways out, since neither is reachable from a locked editor:
            the document itself (drop the #edit fragment — no navigation), and home. */}
        <div className="mt-4 flex items-center justify-between font-mono text-xs">
          <button
            type="button"
            aria-label="View this document without editing"
            onClick={onExit}
            className="cursor-pointer rounded-[4px] border border-edge px-2 py-1 text-muted hover:border-edge-bright hover:text-fg"
          >
            view this document
          </button>
          <a
            href="/"
            aria-label="Go home"
            className="inline-flex items-center gap-1.5 rounded-[4px] border border-edge px-2 py-1 text-muted no-underline hover:border-edge-bright hover:text-fg"
          >
            <Home size={12} /> go home
          </a>
        </div>
      </main>
    );
  }

  if (!art) return <p className="mt-10 text-xs text-faint">loading…</p>;

  return (
    <InPlaceEditor
      frameRef={frameRef} runtimeRef={runtimeRef}
      sessionNonce={sessionNonce}
      art={{
        id: art.id,
        version: art.version,
        edit_id: art.edit_id,
        title: art.title,
        theme: art.theme,
        template: art.template ?? null,
        colorMode: art.colorMode ?? null,
        markup: art.markup ?? '',
        refs: art.refs ?? [],
        compiledCss: art.compiledCss ?? null,
        dataflow: art.dataflow ?? null,
      }}
      flushRef={childFlush}
      initialSelectionPath={initialSelectionPath}
      onComment={onComment}
      rightInset={rightInset}
      onDone={onExit}
      onLeftInsetChange={onLeftInsetChange}
      onRightInsetChange={onRightInsetChange}
    />
  );
}

// services/app/solid/editor/ArtifactEditor.tsx
/* @jsxImportSource solid-js */
/**
 * components/ArtifactEditor in SOLID — the gate into editing, mounted by the document page when edit
 * mode is on. It decides whether this browser may write at all (one `backend.load()`, authorized by
 * whichever browser credential the cookie carries), else the locked card; otherwise it is the
 * in-place editor over the page's adopted document, seeded with what the page already holds.
 */
import { createSignal, onMount, Show, type JSX } from 'solid-js';
import House from 'lucide-solid/icons/house';
import Lock from 'lucide-solid/icons/lock';
import type { ArtifactBackend } from '@/lib/artifact-backend/types';
import InPlaceEditor, { type EditorArtifact, type InPlaceEditorProps } from './InPlaceEditor';

export type ArtifactEditorProps = Omit<InPlaceEditorProps, 'art'> & {
  id: string;
  backend: ArtifactBackend;
  /** What the page already holds; absent, the editor waits for the load. */
  seed?: EditorArtifact;
  onExit: () => void;
};

export default function ArtifactEditor(props: ArtifactEditorProps): JSX.Element {
  const [art, setArt] = createSignal<EditorArtifact | null>(props.seed ?? null);
  const [locked, setLocked] = createSignal(false);
  // The locked card is this session's whole editor: the page's entry chrome and loading bar end with it.
  const lock = () => { setLocked(true); props.onEditorMount?.(); props.onEditorReady?.(); };
  onMount(() => {
    void props.backend.load().then((head) => {
      if (!head) { lock(); return; }
      setLocked(false);
      if (!art()) setArt({ ...head, template: head.template ?? null, colorMode: head.colorMode ?? null, markup: head.markup ?? '', refs: head.refs ?? [], compiledCss: null, dataflow: null });
    }).catch(lock);
  });
  return (
    <Show when={!locked()} fallback={
      <main class="mx-auto mt-16 max-w-md px-6 pb-24">
        <div class="rounded-[6px] border border-edge bg-surface px-6 py-5">
          <div class="flex items-center gap-2">
            <Lock size={13} class="shrink-0 text-muted" />
            <h1 class="font-mono text-sm font-semibold text-fg">this document is locked</h1>
          </div>
          <p class="mt-3 font-sans text-sm leading-relaxed text-muted">
            Only its owner can edit it.{' '}
            <a href={`/login?callbackUrl=${encodeURIComponent(`${window.location.pathname}#edit`)}`} class="text-accent no-underline hover:underline underline-offset-4">log in</a>{' '}
            if it&apos;s on your account.
          </p>
          <p class="mt-3 font-mono text-[11px] leading-relaxed text-faint">reading stays open to anyone with the link — only editing needs the account it belongs to.</p>
        </div>
        <div class="mt-4 flex items-center justify-between font-mono text-xs">
          <button type="button" aria-label="View this document without editing" onClick={() => props.onExit()}
            class="cursor-pointer rounded-[4px] border border-edge px-2 py-1 text-muted hover:border-edge-bright hover:text-fg">view this document</button>
          <a href="/" aria-label="Go home" class="inline-flex items-center gap-1.5 rounded-[4px] border border-edge px-2 py-1 text-muted no-underline hover:border-edge-bright hover:text-fg"><House size={12} /> go home</a>
        </div>
      </main>
    }>
      <Show when={art()} fallback={<p class="mt-10 text-xs text-faint">loading…</p>}>
        {(loaded) => <InPlaceEditor {...props} art={loaded()} onDone={props.onExit} />}
      </Show>
    </Show>
  );
}
