// services/app/solid/editor/GridEdit.tsx
/** @jsxImportSource solid-js */
/**
 * lib/story-runtime/edit/grid-edit in SOLID, WITHOUT react-grid-layout's component: tiles are
 * positioned by the same arithmetic RGL uses at margin [0,0] (x·colWidth, y·rowHeight), moved by
 * pointer or keyboard, and every staged layout goes through RGL's own kernel (moveElement + vertical
 * compact) so the rects handed to `onLayout` (via lib/story-ui/grid-layout diffLayouts) are the ones
 * react-grid-layout would produce. Escape cancels a drag or a staged keyboard move; Enter commits one.
 *
 * Tiles are keyed by identity (`key`), so a tile's DOM survives its AST path changing.
 */
import { createMemo, createSignal, For, onCleanup, onMount, Show, untrack, type JSX } from 'solid-js';
import { diffLayouts, type GridItemRect } from '@/lib/story-ui/grid-layout';
import type { StoryLayoutRect } from '@/lib/story-runtime/contract';
import { compact, moveElement, type LayoutItem } from './rgl-kernel';

export interface GridTile { key: string; path: string; rect: GridItemRect; children: () => JSX.Element }

export function GridEdit(props: { cols: number; rowHeight: number; flow?: boolean; tiles: GridTile[]; onLayout(rects: StoryLayoutRect[]): void; renderFlow: () => JSX.Element }) {
  let wrap!: HTMLDivElement;
  const [width, setWidth] = createSignal<number | null>(null);
  onMount(() => {
    const measure = () => { const w = wrap.clientWidth; if (w) setWidth(w); };
    measure();
    const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(measure);
    observer?.observe(wrap);
    window.addEventListener('resize', measure);
    onCleanup(() => { observer?.disconnect(); window.removeEventListener('resize', measure); });
  });
  // The reader's @max-2xl container rule is 42rem: below it, the reader's stacked rendering.
  const stackBelow = () => 42 * (parseFloat(getComputedStyle(document.documentElement).fontSize) || 16);
  const positioned = () => !props.flow && props.tiles.length > 0 && width() !== null && width()! >= stackBelow();
  return <div ref={wrap} class="w-full">
    <Show when={positioned()} fallback={props.renderFlow()}>
      <Positioned width={width()!} cols={props.cols} rowHeight={props.rowHeight} tiles={props.tiles} onLayout={props.onLayout} />
    </Show>
  </div>;
}

function Positioned(props: { width: number; cols: number; rowHeight: number; tiles: GridTile[]; onLayout(rects: StoryLayoutRect[]): void }) {
  const [draft, setDraft] = createSignal<LayoutItem[] | null>(null);
  const layout = createMemo(() => props.tiles.map((t) => ({ i: t.key, ...t.rect })));
  const current = () => draft() ?? layout();
  const rects = () => new Map(props.tiles.map((t) => [t.key, t.rect] as const));
  const paths = () => new Map(props.tiles.map((t) => [t.key, t.path] as const));
  const colW = () => props.width / props.cols;
  let gesture: { key: string; mode: 'move' | 'resize'; startX: number; startY: number; origin: LayoutItem; pointer: number } | null = null;

  const stage = (key: string, fn: (item: LayoutItem, all: LayoutItem[]) => LayoutItem[]) => {
    const next = current().map((r) => ({ ...r }));
    const item = next.find((r) => r.i === key);
    if (item) setDraft(compact(fn(item, next), 'vertical', props.cols));
  };
  const commit = () => {
    const next = draft(); setDraft(null);
    if (!next) return;
    const changed = diffLayouts(next, rects());
    if (changed.length) props.onLayout(changed.map((c) => ({ path: paths().get(c.astPath)!, x: c.x, y: c.y, w: c.w, h: c.h })));
  };
  const cancel = () => { gesture = null; setDraft(null); };
  // A layout change from the SOURCE (another writer, an undo) abandons whatever was staged.
  createMemo((previous: string | undefined) => { const now = JSON.stringify(layout()); if (previous !== undefined && previous !== now) cancel(); return now; });
  const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape' && (gesture || draft())) { event.preventDefault(); cancel(); } };
  document.addEventListener('keydown', onKey, true);
  onCleanup(() => document.removeEventListener('keydown', onKey, true));

  const keyAction = (event: KeyboardEvent, key: string, resize = false) => {
    if (event.key === 'Escape') { event.preventDefault(); cancel(); return; }
    if (event.key === 'Enter' && draft()) { event.preventDefault(); commit(); return; }
    const delta = event.key === 'ArrowLeft' ? [-1, 0] : event.key === 'ArrowRight' ? [1, 0] : event.key === 'ArrowUp' ? [0, -1] : event.key === 'ArrowDown' ? [0, 1] : null;
    if (!delta) return;
    event.preventDefault(); event.stopPropagation();
    stage(key, (item, all) => {
      if (resize) { item.w = Math.max(1, Math.min(props.cols - item.x, item.w + delta[0]!)); item.h = Math.max(1, item.h + delta[1]!); return all; }
      return moveElement(all, item, Math.min(props.cols - item.w, Math.max(0, item.x + delta[0]!)), Math.max(0, item.y + delta[1]!), true, false, 'vertical', props.cols);
    });
  };
  const start = (event: PointerEvent, key: string, mode: 'move' | 'resize') => {
    if (event.button !== 0) return;
    const origin = current().find((r) => r.i === key); if (!origin) return;
    event.preventDefault();
    (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId);
    gesture = { key, mode, startX: event.clientX, startY: event.clientY, origin: { ...origin }, pointer: event.pointerId };
  };
  const move = (event: PointerEvent) => {
    const g = gesture; if (!g || event.pointerId !== g.pointer) return;
    const dx = Math.round((event.clientX - g.startX) / colW()), dy = Math.round((event.clientY - g.startY) / props.rowHeight);
    const base = layout().map((r) => (r.i === g.key ? { ...g.origin } : { ...r }));
    const item = base.find((r) => r.i === g.key)!;
    if (g.mode === 'resize') {
      item.w = Math.max(1, Math.min(props.cols - item.x, g.origin.w + dx)); item.h = Math.max(1, g.origin.h + dy);
      setDraft(compact(base, 'vertical', props.cols));
    } else {
      setDraft(compact(moveElement(base, item, Math.min(props.cols - item.w, Math.max(0, g.origin.x + dx)), Math.max(0, g.origin.y + dy), true, false, 'vertical', props.cols), 'vertical', props.cols));
    }
  };
  const end = (event: PointerEvent) => { if (!gesture || event.pointerId !== gesture.pointer) return; gesture = null; commit(); };
  const rows = () => current().reduce((m, r) => Math.max(m, r.y + r.h), 1);
  const rectOf = (key: string) => current().find((r) => r.i === key);

  const keys = createMemo(() => props.tiles.map((t) => t.key), undefined, { equals: (a, b) => a.length === b.length && a.every((k, i) => k === b[i]) });
  return <div class="mx-grid-positioned" style={{ position: 'relative', height: `${rows() * props.rowHeight}px` }} onDragStart={(e) => e.preventDefault()} onPointerMove={move} onPointerUp={end} onPointerCancel={() => cancel()}>
    {/* Keyed by IDENTITY (the string key), not by the tile object: a tile whose AST path moved keeps
        its DOM. Its content is rendered once per identity and updates through its own reactivity —
        the Solid shape of React's "same key, re-render the element". */}
    <For each={keys()}>{(key) => {
      const tile = () => props.tiles.find((t) => t.key === key)!;
      const r = () => rectOf(key)!;
      const content = untrack(() => tile().children());
      return <div data-mx-grid-tile={key} style={{ position: 'absolute', left: `${r().x * colW()}px`, top: `${r().y * props.rowHeight}px`, width: `${r().w * colW()}px`, height: `${r().h * props.rowHeight}px`, transition: gesture ? 'none' : 'left .15s, top .15s' }}>
        {content}
        <button type="button" class="mx-grid-grip" aria-label={`Move GridItem ${tile().path}`} onPointerDown={(e) => start(e, key, 'move')} onKeyDown={(e) => keyAction(e, key)}>⠿</button>
        <span role="button" tabIndex={0} aria-label="Resize positioned tile" class="mx-grid-resize" onPointerDown={(e) => start(e, key, 'resize')} onKeyDown={(e) => keyAction(e, key, true)} />
      </div>;
    }}</For>
  </div>;
}

// services/app/lib/story-runtime/edit/grid-edit.tsx
'use client';

/**
 * Dragging and resizing a `<Grid>`'s tiles, in the document.
 *
 * It has to happen here: react-grid-layout works in PIXELS, and only the
 * document knows how wide its own columns are — the grid sits inside whatever
 * gutter and measure the author gave it. So the drag is local and the RESULT
 * travels: a set of rects the page writes back into the source, exactly as it
 * writes back a paragraph.
 *
 * Ported from the canvas's GridAdapter. The one real change is where the width
 * comes from: there it was the canvas's fixed measure, here it is the element's
 * own, re-read when the window changes.
 */
import {
  cloneElement,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ReactElement,
  type KeyboardEvent,
} from 'react';
import RGL, { type Layout } from 'react-grid-layout';

import { Grid, gridItemChildren, type GridProps, type GridItemProps } from '@/components/kit/grid';
import { diffLayouts, gridCols, gridItemRect, gridRowHeight, type GridItemRect } from '@/lib/story-ui/grid-layout';
import { STORY_GRID_EDIT_CSS } from '@/lib/story-ui/grid-css';
import { AST_PATH_ATTR } from '@/lib/story-ui/ast-path';
import type { StoryLayoutRect } from '../contract';

interface GridEditProps {
  props: Record<string, unknown>;
  /** Report the rects a drag or resize produced. Several at once: compaction moves siblings. */
  onLayout: (rects: StoryLayoutRect[]) => void;
}

export function GridEdit({ props, onLayout }: GridEditProps) {
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const [width, setWidth] = useState<number | null>(null);

  useLayoutEffect(() => {
    const measure = () => {
      const w = wrapRef.current?.clientWidth;
      if (w) setWidth((prev) => (prev === w ? prev : w));
    };
    measure();
    const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(measure);
    if (wrapRef.current) observer?.observe(wrapRef.current);
    window.addEventListener('resize', measure);
    return () => {
      observer?.disconnect();
      window.removeEventListener('resize', measure);
    };
  }, []);
  // The document re-renders around us; re-measure after each one.
  useEffect(() => {
    const w = wrapRef.current?.clientWidth;
    if (w) setWidth((prev) => (prev === w ? prev : w));
  });

  const gridProps = props as unknown as GridProps;
  const astPath = props[AST_PATH_ATTR];
  const nCols = gridCols(gridProps.cols);
  const rh = gridRowHeight(gridProps.rowHeight);
  const items = gridItemChildren(gridProps.children).filter(
    (el: ReactElement) => typeof (el.props as Record<string, unknown>)[AST_PATH_ATTR] === 'string',
  );
  // Nothing addressable to drag: render it as the reader sees it.
  // The reader's @max-2xl container rule is 42rem. Reuse its stacked
  // rendering below that width; responsive presentation never writes geometry.
  const stackBelow = 42 * (parseFloat(getComputedStyle(document.documentElement).fontSize) || 16);
  if (gridProps.mode === 'flow' || items.length === 0 || width === null || width < stackBelow) {
    return (
      <div ref={wrapRef} className="w-full" {...{ [AST_PATH_ATTR]: astPath }}>
        <Grid {...gridProps} />
      </div>
    );
  }

  return (
    <PositionedGridEdit
      width={width}
      nCols={nCols}
      rh={rh}
      items={items}
      astPath={astPath}
      onLayout={onLayout}
      wrapRef={wrapRef}
    />
  );
}

/** Positioned interaction is isolated from the flow renderer and public component vocabulary. */
function PositionedGridEdit({
  width,
  nCols,
  rh,
  items,
  astPath,
  onLayout,
  wrapRef,
}: {
  width: number;
  nCols: number;
  rh: number;
  items: ReactElement[];
  astPath: unknown;
  onLayout: GridEditProps['onLayout'];
  wrapRef: React.RefObject<HTMLDivElement | null>;
}) {
  const [draft, setDraft] = useState<Layout[] | null>(null);
  const cancelled = useRef(false),
    activeGesture = useRef(false);
  const itemKey = (el: ReactElement) =>
    String((el.props as Record<string, unknown>).id ?? el.key ?? (el.props as Record<string, unknown>)[AST_PATH_ATTR]);
  const paths = new Map(
    items.map((el) => [itemKey(el), (el.props as Record<string, unknown>)[AST_PATH_ATTR] as string]),
  );
  const rects = new Map<string, GridItemRect>(
    items.map((el: ReactElement) => [itemKey(el), gridItemRect(el.props as Record<string, unknown>, nCols)]),
  );
  const layout: Layout[] = [...rects].map(([i, r]) => ({ i, ...r, resizeHandles: ['se' as const] }));
  const current = draft ?? layout;
  // RGL publicly exports the same collision/compaction kernel it uses for pointer moves.
  const utils = (
    RGL as typeof RGL & {
      utils: {
        moveElement(
          layout: Layout[],
          item: Layout,
          x: number,
          y: number,
          user: boolean,
          prevent: boolean,
          compact: string,
          cols: number,
        ): Layout[];
        compact(layout: Layout[], type: string, cols: number): Layout[];
      };
    }
  ).utils;
  const cancel = () => {
    if (!activeGesture.current && !draft) return;
    cancelled.current = true;
    activeGesture.current = false;
    setDraft(null);
    document.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
  };
  useEffect(() => {
    const key = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Escape' && (activeGesture.current || draft)) {
        e.preventDefault();
        cancel();
      }
    };
    document.addEventListener('keydown', key, true);
    return () => document.removeEventListener('keydown', key, true);
  });
  const sourceGeometry = JSON.stringify(layout),
    previousGeometry = useRef(sourceGeometry);
  useLayoutEffect(() => {
    if (previousGeometry.current !== sourceGeometry) {
      cancel();
      previousGeometry.current = sourceGeometry;
    }
  }, [sourceGeometry]);
  const commit = (next: Layout[]) => {
    activeGesture.current = false;
    setDraft(null);
    if (cancelled.current) {
      cancelled.current = false;
      return;
    }
    const changed = diffLayouts(next, rects);
    if (changed.length > 0) {
      onLayout(changed.map((c) => ({ path: paths.get(c.astPath)!, x: c.x, y: c.y, w: c.w, h: c.h })));
    }
  };

  const keyAction = (event: KeyboardEvent, path: string, resize = false) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      cancel();
      return;
    }
    if (event.key === 'Enter' && draft) {
      event.preventDefault();
      commit(draft);
      return;
    }
    const delta =
      event.key === 'ArrowLeft'
        ? [-1, 0]
        : event.key === 'ArrowRight'
          ? [1, 0]
          : event.key === 'ArrowUp'
            ? [0, -1]
            : event.key === 'ArrowDown'
              ? [0, 1]
              : null;
    if (!delta) return;
    event.preventDefault();
    event.stopPropagation();
    cancelled.current = false;
    const next = current.map((r) => ({ ...r })),
      item = next.find((r) => r.i === path);
    if (!item) return;
    if (resize) {
      item.w = Math.max(1, Math.min(nCols - item.x, item.w + delta[0]));
      item.h = Math.max(1, item.h + delta[1]);
      setDraft(utils.compact(next, 'vertical', nCols));
    } else
      setDraft(
        utils.compact(
          utils.moveElement(
            next,
            item,
            Math.min(nCols - item.w, Math.max(0, item.x + delta[0])),
            Math.max(0, item.y + delta[1]),
            true,
            false,
            'vertical',
            nCols,
          ),
          'vertical',
          nCols,
        ),
      );
  };
  return (
    <div
      {...{ [AST_PATH_ATTR]: astPath }}
      className="w-full"
      ref={wrapRef}
      /*
       * A tile drag is a react-grid-layout MOUSE drag; any NATIVE drag starting
       * inside it is a hijack — an embed title is an <a href>, natively
       * draggable, so dragging a tile by its title dragged the LINK too (URL
       * ghost, drop-navigation).
       */
      onDragStartCapture={(e) => e.preventDefault()}
    >
      {/* RGL's structural CSS, inside this document — head styles never reach it. */}
      <style data-mx-grid-css="">{STORY_GRID_EDIT_CSS}</style>
      <RGL
        width={width}
        cols={nCols}
        rowHeight={rh}
        margin={[0, 0]}
        containerPadding={[0, 0]}
        compactType="vertical"
        layout={current}
        onDragStart={() => {
          cancelled.current = false;
          activeGesture.current = true;
        }}
        onResizeStart={() => {
          cancelled.current = false;
          activeGesture.current = true;
        }}
        onDrag={(next) => setDraft(next.map((r) => ({ ...r })))}
        onResize={(next) => setDraft(next.map((r) => ({ ...r })))}
        resizeHandle={(axis, ref) => (
          <span
            ref={(element) => {
              if (typeof ref === 'function') ref(element);
              else if (ref) (ref as { current: HTMLElement | null }).current = element;
            }}
            role="button"
            tabIndex={0}
            aria-label="Resize positioned tile"
            className={`react-resizable-handle react-resizable-handle-${axis}`}
            onKeyDown={(event) => {
              const path = event.currentTarget.parentElement
                ?.querySelector(`[${AST_PATH_ATTR}]`)
                ?.getAttribute(AST_PATH_ATTR);
              if (path) {
                const key = [...paths].find(([, p]) => p === path)?.[0];
                if (key) keyAction(event, key, true);
              }
            }}
          />
        )}
        onDragStop={commit}
        onResizeStop={commit}
        draggableHandle=".mx-grid-grip"
        draggableCancel="[contenteditable],input,textarea,select,button:not(.mx-grid-grip)"
        isDraggable
        isResizable
      >
        {items.map((el: ReactElement) => {
          const path = (el.props as Record<string, unknown>)[AST_PATH_ATTR] as string;
          // RGL positions this wrapper; the cloned tile stops positioning itself.
          return (
            <div key={itemKey(el)}>
              {cloneElement(el as ReactElement, { editing: true } as Partial<GridItemProps>)}
              <button
                type="button"
                className="mx-grid-grip"
                aria-label={`Move GridItem ${path}`}
                onKeyDown={(event) => keyAction(event, itemKey(el))}
              >
                ⠿
              </button>
            </div>
          );
        })}
      </RGL>
    </div>
  );
}
